exercises/word-count/canonical-data.json

As countwords actually consists of two words, its correct name is `countWords`.

word-count: Use camel-case for property name

---

exercises/clock/canonical-data.json

This exercise does not directly test adding or subtracting negative minutes.  I thought it prudent to revise the comment at the top of the testdata to reflect this recent change to the exercise.

clock: remove mention of negative minutes in comment

---

exercises/roman-numerals/canonical-data.json

closes #1138
adds a test case for input value 49, which contains two substrings that need to be normalized, ("XXXX" should be "XL" and "VIIII" should be "IX".

roman-numerals: add test case for input value 49 to test double-normalization

---

exercises/rna-transcription/metadata.yml

closes #1078 and is meant to replace #1133.
This exercise is currently designed around the Complement Transcription idea, but the source_url (in metadata.yml) was pointing to a site that describes the T -> U transcription method.

rna-transcription: provide more accurate source info

---

exercises/two-bucket/description.md

Looks like the link in two-bucket READMEs to http://lindsaylevine.com/ doesn't seem to work anymore.
I've had a quick look and http://lindsay.engineer is a website that does seem to work, though I am not 100% sure if it is the same person or not! I've removed the link for now and replaced with a full name, though if other people know that the other website is actually correct then I'm happy to update it to that too :slightly_smiling_face:

two-bucket: remove broken link

---

exercises/prime-factors/canonical-data.json

prime-factors: apply "input" policy

---

exercises/run-length-encoding/canonical-data.json

run-length-encoding: apply "input" policy

---

exercises/robot-simulator/canonical-data.json

robot-simulator: apply "input" policy

---

exercises/robot-simulator/canonical-data.json

This is a follow up to PR #1163.  I had missed moving `"instructions":` into `"input":`.

robot-simulator: move "instructions": into "input":

---

exercises/protein-translation/description.md

There was a misspelled STOP codon in the readme of the Protein
Translation exercise.
The spelling has been corrected and the codon has also been
added to the following paragraph to clarify the meaning.

Protein-translation: Fix codon spelling in description

---

.travis.yml
README.md

I have noticed that in the README we instruct people to use node/npm. Yet we use Yarn to install our dependencies.
So I figured it would make sense to drop any mention of node/npm and instead use yarn. Yarn provides everything we need and we wouldn't be asking people to install two tools for one job.

problem-specifications: Replace use of node/npm with yarn

---

exercises/complex-numbers/canonical-data.json

For some reason, there was no test for exp(a + bi) where a + bi has both a real part and an imaginary part. This PR adds such a test with exact values that are simple to define (requiring no rounded values).
Proof:
```
e^(ln(2) + PI * i) = e^ln(2) * e^(PI * i)
e^ln(2) = 2
e^(PI * i) = cos(PI) + isin(PI) = -1 + 0i = -1
e^(ln(2) + PI * i) = 2 * -1 = -2
```

complex-numbers: exponential of complex number

---

exercises/scale-generator/canonical-data.json

My first pass at closing #583.
I removed a couple inessential naming tests that the Python on Ruby implementations had and a ginormous pile of overly-detailed tests the Elixir implementation had.

scale-generator: add canonical data

---

.travis.yml
canonical-schema.json
old-schema.json

The strict version of #1072: Enforces that we will not forget to remove the USE_OLD_SCHEMA file.
If it is present, use the old schema, else use the new schema.
This plan is proposed in:
#998
Its merits are that it allows us to:
* Track progress by simply counting number of USE_OLD_SCHEMA file.
* Verify, as each PR is made, that each JSON file intending to use new
schema does in fact validate.
* Otherwise we have to manually run a schema check at periodic
intervals.
* Keep compatibility with old schema, to support moving over one file at
a time instead of all at once.
Note that old-schema.json is the same canonical-schema.json as is
currently on master.
The intention is that when all exercises use the new schema, **the
commit "travis: Choose schema based on USE_OLD_SCHEMA file" can/should …

travis: Choose schema based on USE_OLD_SCHEMA file (strict)

---

exercises/all-your-base/canonical-data.json

the previous version was not properly testing that input base was validated
passing the "empty list" test would also pass this test
fixed in elixir here: exercism/elixir#389

all-your-base: improve "input base is one" test

---

exercises/bowling/canonical-data.json

Currently, there are no tests confirming that a game with bonus rolls for a spare or strike in the 10th frame is complete. This PR adds a case for both spare and strike, attempting to roll an additional ball after the bonus rolls have been completed, expecting an error to be raised upon the roll attempt.
For confirmation that these are not currently tested for, the [current example solution in the Python track](https://github.com/exercism/python/blob/f6f9279e7725e8bb891a34d439cf9075c69760d5/exercises/bowling/example.py) passes all existing tests, but fails these new tests.

bowling: add tests for rolling after bonus rolls

---

exercises/grains/canonical-data.json

grains 1.1.0
As proposed and accepted in https://github.com/exercism/problem-specifications/issues/996
```ruby
have_input = false
ARGF.each_line { |l|
if l.include?('version')
ver = l.split(?")[3]
ver_components = ver.split(?.).map(&:to_i)
ver_components[1] += 1
ver_components[2] = 0
l[ver] = ver_components.join(?.)
end
have_input &&= !l.include?('"description"')
first_non_space = l.index(/\S/)
if l.include?('"input"')
have_input = true
input = l.split(?:).last.to_i
puts ' ' * first_non_space + '"input": {'
puts ' ' * first_non_space + '  "square": ' + input.to_s
puts ' ' * first_non_space + '},'
next
end
puts ' ' * first_non_space + '"input": {},' if l.include?('"expected"') && !have_input
puts l
}
```

grains: Move input (square) to input object

---

exercises/pig-latin/description.md

I'm a programming instructor and the current rules of this exercise did not provide enough detail for my students to really understand what is expected of the code they need write. Reached out to the Gitter exercism support channel and @kotp suggested I contribute to the documentation.

pig-latin: improve documentation

---

exercises/react/canonical-data.json

Depending on the language and implementation, a possible solution for callback values is to simply append the new value to the callback's value list. This is incorrect behavior, but no test verifies that the callback only contains 1 value per input. This PR adds a test that does just that.

react: check callback values after multiple value changes

---

exercises/house/canonical-data.json

Closes #1200.
* Bump version
* Remove redundant reasons for separating a verse into strings
* Transform the output to the same format as twelve-days

house: transform output to array of whole sentence

---

exercises/go-counting/canonical-data.json
exercises/go-counting/description.md

Closes #560 
Here is a canonical data file for the go-counting exercise. I have a couple questions:
Why are some parts highlighted in red? Also should I specify that the expected territory should be a set and not an array?

go-counting: Updating documentation

---

exercises/isbn-verifier/canonical-data.json

Set new test case to be **3-598-P1581-X**.
It should avoid solutions to pass - when inside characters (P) is treat as 0.
3 * 10 + 5 * 9 + 9 * 8 + 8 * 7 + 0 * 6 + 1 * 5 + 5 * 4 + 8 * 3 + 1 * 2 + 10 * 1 = 264
264 is divisible by 11.
Closes #1212

Replace test case - "invalid character in isbn". 

---

exercises/bracket-push/canonical-data.json

Some incorrect solutions return `true` as soon as brackets are matched. Check out this solution in Python which can pass all current tests:
```python
bracket_dict = {"(": ")", "[": "]", "{": "}"}
def brackets_match(opening_bracket, closing_bracket):
return bracket_dict[opening_bracket] == closing_bracket
def is_paired(input_string):
bracket_stack = []
for char in input_string:
if char in bracket_dict.keys():
bracket_stack.append(char)
elif char in bracket_dict.values():
try:
top_of_stack = bracket_stack.pop()
except IndexError:
return False
return brackets_match(top_of_stack, char)
return bracket_stack == []
```
Clearly `return brackets_match(top_of_stack, char)` within the `for` loop is wrong, so it will fail test cases where brackets are partially paired, like `{[])`.

bracket-push: Add test case "partially paired brackets"

---

exercises/isbn-verifier/canonical-data.json

isbn-verifier: adding test case for 0 < length < 10

---

exercises/crypto-square/description.md

Ambiguity in the original wording, especially "empty spaces", has led to much confusion, including a Rust implementation that got this requirement wrong.

crypto-square: Clarify rectangular output requirement in description.md

---

exercises/react/canonical-data.json

react 1.3.0
Consider an implementation that stops looking for cells to fire
callbacks on after it has found any single cell that has callbacks. That
would fail this test.

react: Test callbacks on multiple cells

---

exercises/react/canonical-data.json

react 2.0.0
expect_callback_values is often not precise enough about which
`set_value` calls should result in which callbacks being called or not
called. "callbacks can be added and removed" is the worst offender,
expecting a `[32, 42]` from callback2 only after both `set_value` have
fired.
That means for all we know, maybe an implementation:
* magically manages to predict the future and calls the callback twice
on the first `set_value`, with the correct value, and then zero times
on the second `set_value`.
* calls the callback zero times on the first `set_value`, but twice
on the second `set_value`.
To remedy this, we observe that the only time callbacks might be called
is if there was a `set_value`. So, let's explicitly associate our
callback expectations along with each `set_value`.

react: Fold expect_callback_values into set_value

---

exercises/series/canonical-data.json
exercises/series/description.md

Resolves #584 by implementing canonical data for `series`.
I've noticed that lots of implementations expect the output to be a list of lists of integers rather than a list of strings:
- [F#](https://github.com/exercism/fsharp/blob/master/exercises/series/SeriesTest.fs)
- [Java](https://github.com/exercism/java/blob/master/exercises/series/src/test/java/SeriesTest.java)
- [Haskell](https://github.com/exercism/haskell/blob/master/exercises/series/test/Tests.hs)
However, I would argue that a list of strings is more reasonable, particularly given the current description, which mentions substrings. Some tracks have implemented it this way:
- [Go](https://github.com/exercism/go/blob/master/exercises/series/series_test.go)
- [Ruby](https://github.com/exercism/ruby/blob/master/exercises/series/ser …

series: Improve documentation

---

exercises/pov/canonical-data.json

I've seen solutions that always hit root node, even when the shortest path should not. So here is a test for that.

pov: add test for paths not involving root

---

exercises/crypto-square/description.md

per #1208.  Quotes (`"`) added to indicate relevant white space in description.

crypto-square: add quotes to indicate relevant whitespace

---

exercises/bracket-push/description.md

fixes #1178
Rewording now indicates that the input string `may` have instead of `will` have.

bracket-push: remove ambiguity in description

---

exercises/list-ops/canonical-data.json

list-ops: clarify purpose of concat function

---

exercises/forth/canonical-data.json

All solutions I have seen don't support "recursive" word definitions and/or word "versioning". New test case will check both situations.

forth: add test for multiple word redefinition

---

exercises/isbn-verifier/canonical-data.json

isbn-verifier: add a test case that would be accepted by an implementation where an invalid character is simply dropped

---

exercises/luhn/canonical-data.json

https://github.com/exercism/problem-specifications/blob/master/exercises/luhn/description.md

luhn: add a test case

---

exercises/word-search/canonical-data.json

There is no mention of the value `-1` anywhere in the canonical data, so this comment line can be removed.

word-search: Remove unneeded exception case comment

---

exercises/say/description.md

When I first read this README I skimmed past the `extension` section since it said "if you're on a Mac", and I'm using Linux. I'm glad I took the time to find an alternative, it was really fun, and I wanted to make sure others will be made aware of it too.
I'd be happy to receive feedback on the construction of the sentence. I'm sure it can be improved.

Say: Add 'espeak' reference to README

---

exercises/simple-cipher/canonical-data.json

Can anyone clarify the CI building output for me? I see that is failing but I didn't understand why. 
As I understood from the [canonical-data.json specification](https://github.com/exercism/problem-specifications#test-data-format-canonical-datajson), I should be able to nest `cases ` keywords.
For this problem in specific, there is a test case where we don't assert, but we use a match test to check a property against a regex, so I used a `match` key for it.
Closes #586

simple-cipher: Add canonical-data.json

---

exercises/isbn-verifier/canonical-data.json

I was too hasty when I merged #1251.  I missed that version had not been updated.

isbn-verifier: testdata bump version

---

exercises/simple-cipher/canonical-data.json

Closes #1250 
To summarize, a face-value translation of the canonical data results in failure, because in the canonical data no substring length is specified for cipher.key. Thus, when then full string is used, the length of the actual value is much greater than the length of the expected value.

simple-cipher: specify substring length for symbolic values

---

exercises/isbn-verifier/canonical-data.json

This commit adds an input that will be incorrectly validated by
algorithms that don't explicitly check the length of their inputs, as
discussed in #1199 and #993.
For example, if an algorithm only checks the first (or last) ten
digits of the input, ignoring leftovers, it will pass the current test
suite even though it doesn't correctly implement the spec.
closes #1199

isbn-verifier: Crafted input to catch more incorrect algorithms

---

exercises/isogram/canonical-data.json

A solution in the C track used a char[4] array instead of an unsigned
int to keep track of seen letters. This caused it to check for
duplicates only in the first 8 letters, and it passed the test suite.
This goes along with PR exercism/c#314.

Isogram: Check for duplicates at the end of the alphabet.

---

exercises/saddle-points/canonical-data.json

There is a test for multiple saddle points in a column, but there is no test for multiple points in a row.
These changes rename the existing test to indicate it tests for saddle points in a column and adds a test for multiple points in a row.

Saddle-points: Add test for multiple saddle-points in a row

---

exercises/protein-translation/canonical-data.json

Since all tests assume the inputs to be valid.

Remove error-related comment from protein-translation

---

exercises/atbash-cipher/canonical-data.json

I think it needed tests for decoding with incorrect spacing in the ciphertext.
This mirrors some tests that we put in the affine-cipher problem's [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/affine-cipher/canonical-data.json).
I also updated the version from `1.1.0` to `1.2.0`.

Atbash-cipher: Add tests for decoding input with incorrect spacing

---

exercises/anagram/canonical-data.json

The comment is referring to a `string argument cases` key which was removed in PR https://github.com/exercism/problem-specifications/pull/308

anagram: Remove comment from canonical data

---

exercises/bob/canonical-data.json

I ran across a solution that passed the tests but violated the spirit of
the tests. The student was checking for shouting by checking for:
* the absence of lower case letters AND
* (a string ending in `!` OR
* a string without numbers)
This means that "1,2,3!" would be shouting, but "JUST 1 NUMBER"
wouldn't, which seems to violate the spirit of tests titled:
* shouting numbers
* shouting with no exclamation mark
---
Should a test be added for this case, or is changing test descriptions to be more clear enough?

bob: improve test descriptions re: absence of letters

---

exercises/acronym/canonical-data.json

A solution on the C track only worked because all the acronyms were shorter than 8 letters. Specifically, the student allocated a buffer the size of a char pointer, instead of a buffer n characters long.

Acronym: add long instance case to canonical-data.json

---

exercises/collatz-conjecture/canonical-data.json

It seemed like this description shouldn't be capitalized so that it would fit with the style of the other cases in this problem.

collatz-conjecture: fix capitalized description

---

exercises/markdown/canonical-data.json

I recently reviewed a nicely refactored solution for the markdown exercise, but I noticed that while the original code passes for the tests I'm suggesting, the student's newly refactored code did not. It's not the student's fault, since the existing tests all passed, but I think these additional ones may be helpful.
I suggested these tests to the student, who was able to rework the code in a second iteration and make them pass.
My reasoning was that it's entirely reasonable to have a header where the text has a hash in it (like `# My C# Header` and that shouldn't be interpreted as an H2 header.
What does everyone think? If it's too much, or gets away from the goals of this exercise too much, I'm fine with leaving them out.

markdown: Extra tests to ensure markdown symbols are not incorrectly interpreted

---

exercises/bob/canonical-data.json

Encountered a submission where someone was addressing `OK` and `DMV` as acronyms and excluding those specifically when checking for shouting.

bob: Modify test case to include acronym in shouting

---

exercises/affine-cipher/canonical-data.json

It was brought to my attention while implementing a generator in the Ruby track that I did not follow the proper convention in the cases that return an error.

affine-cipher: fixed expected policy for errors

---

exercises/book-store/canonical-data.json

The current "two groups of four" test allows solutions to pass if they add books to groups in the order in which they appear in the list, which doesn't work in general. I saw two solutions in a row which pass the tests as-is but fail this new test, because adding books 2 and 3 to the first group of four will prevent making a second one.
fixes #1215

book-store: Add test case to thwart list-order greedy solutions

---

exercises/anagram/canonical-data.json

I find `anagrams` to be a generic name for a method or function. I think the property should be description of either the action or the result.
Since the property is about returning a list of anagrams found of a given word, I think `findAnagrams` would be alright.

anagram: Change property to be more descriptive

---

exercises/isogram/canonical-data.json

new clean commit here.
see notes from closed #1305.
closes #1303

Isogram: add test for duplicate if the second is upper case

---

exercises/isogram/canonical-data.json

There are very talented students who exploit every loophole of the test suite. This guy forgot to look at the first and the last character, and still managed to pass all existing tests! (I like the originality of comparing strchr() with strrchr(), though)
```
for (size_t i = 1; i < len - 1; i++)
{
// If the fist occurence of a character is not the last,
// that's not an isogram.
if (strchr(str, str[i]) != strrchr(str, str[i]))
{
return false;
}
}
```

isogram: adding testcase with same first and last character

---

exercises/bob/canonical-data.json

In the Bob exercise it says:
> Bob's conversational partner is a purist when it comes to written
> communication and always follows normal rules regarding sentence
> punctuation in English.
But in the unit test the following input is fed to `responseFor`:
"\nDoes this cryogenic chamber make me look fat?\nno"
This is a rhetorical question, and by the expected value, this is deemed
to not be an actual question, which is very reasonable. But if Bob's
conversational partner is a punctuation purist, it should at least end
with a period.
I found this when exercising the Haskell track and wanting to grab the
last character that `isPunctuation`, but had to go with `not . isSpace`
(like the reference solution). But this really sounds wrong when I think
about it: I actually want the last …

Bob: Fix grammatical error in testdata

---

exercises/crypto-square/description.md
exercises/dominoes/description.md
exercises/simple-cipher/description.md

Ran a spell check on the Rust exercises.
exercism/rust#656

crypto-square, dominoes, simple-cipher: Fix misspellings

---

exercises/grains/canonical-data.json

Fixes https://github.com/exercism/problem-specifications/issues/1309. 
Also, modified the comments so that it reflects the current state of how the error is indicated.

Grains: Fixed canonical data to have standard error indicator

---

exercises/acronym/canonical-data.json

Add test case for input where, when splitting via the specified delimiter characters, empty strings in the resulting "word" list might trigger out of bound errors.

Acronym: Add test for edge case

---

exercises/phone-number/canonical-data.json

…11-digit numbers with invalid area/exchange codes
closes #1320

phone-number: add cases to test data that cover invalid use of "1" or "0"

---

exercises/largest-series-product/canonical-data.json

Closes https://github.com/exercism/problem-specifications/issues/1310

largest-series-product: Canonical-data now has standard error indicators

---

exercises/robot-simulator/canonical-data.json

Several cases do not have completely clear "expected" results documented.  Some of the exercises did not indicate what compass direction was related to "x" or "y", those cases were removed as follow on cases did clearly indicate compass direction association.  Also cases that only changed direction, without advancing, were not checking that the expected position was still the same as the input position.

robot-simulator: remove ambiguity from test data

---

exercises/change/canonical-data.json

change 1.3.0
As proposed in
https://github.com/exercism/problem-specifications/issues/1313
https://github.com/exercism/problem-specifications/issues/905#issuecomment-330184896
In contrast to the proposal in
https://github.com/exercism/problem-specifications/issues/336#issuecomment-280231149
Although -1 is a sentinel value, the sentinel value had been overloaded
in this JSON file to mean two separate conditions:
* "Can't make target" (ostensibly, we might be able to make the target
with a different set of coins)
* "Target is negative" (no matter what coins we provide, this target is
always invalid)
To make clear that these two conditions are different, we use an error
object describing each.
This error object was defined in
https://github.com/exercism/problem-specifications/issues/401
Note …

change: Use error object instead of sentinel -1

---

exercises/binary-search/canonical-data.json

binary-search 1.2.0
As discussed in
https://github.com/exercism/problem-specifications/issues/1312
Although -1 is a sentinel value, using this sentinel value is not the
usual course of action in some languages. In using an error object, we
avoid giving the wrong idea that we are requiring the use of the
sentinel value.
This error value was defined in
https://github.com/exercism/problem-specifications/issues/401
Of course, languages that wish to use a sentinel value may continue to
do so; this commit is not intended to decree that sentinel values are
forbidden.
Neither is this commit decreeing that all languages must represent this
condition as an error; it is simply a declaration that this condition
bears enough consideration that we'll represent it with a different
type.
Closes …

binary-search: Use error object instead of sentinel -1

---

exercises/change/description.md

Closes #1283 
This makes it so that description.md matches the output expected based off [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/change/canonical-data.json).

change: modified description.md to match expected output

---

exercises/pascals-triangle/canonical-data.json

pascals-triangle: implement error object

---

exercises/ocr-numbers/canonical-data.json

ocr-numbers: implement error object

---

exercises/wordy/canonical-data.json

per #1311 proper error handling object incorporated into last two test cases.

wordy: implement "error" object

---

exercises/forth/canonical-data.json
exercises/phone-number/canonical-data.json
exercises/queen-attack/canonical-data.json
exercises/say/canonical-data.json
exercises/variable-length-quantity/canonical-data.json

per #1311
phone-number
say
variable-length-quantity
queen-attack
forth

implement error object on multiple exercises

---

exercises/pascals-triangle/canonical-data.json

case `negative rows` is out of scope for this exercise.  I would like to remove it.
I have also updated the comments to reflect that no longer do any "error" objects appear in the test data.
per comments made in #1336.

pascals-triangle:  remove case that is out of scope

---

exercises/anagram/canonical-data.json

The logical extension of Banana not being an anagram of BANANA must be that words are never anagrams of themselves, and that the test "capital word is not own anagram" only tests this for case insensitivity.
Otherwise, I'm unsure what the rule is. If the rule has to do with grammar, e.g. the first letter can be insensitive, but the rest can't, then perhaps the problem needs to be explained in the README or in the test-case "capital word is not own anagram".

anagram: words are not anagrams of themselves

---

exercises/robot-simulator/canonical-data.json

Case that I added in #1343 introduced scenario described in README.  However the description of the case was already being used by the last case....

robot-simulator: fix repeat case name conflict

---

exercises/leap/canonical-data.json

Someone thought they could write `year mod 200 = 0`. Test didn't fail.

leap 1.4.0: Add negative test: year divisible by 200, not divisible by 400

---

exercises/triangle/canonical-data.json

A wrong implementation of `is_isosceles` might look like:
let is_isosceles a b c =
is_triangle a b c &&
a = b || b = c || a = c
when the intention was:
let is_isosceles a b c =
is_triangle a b c &&
(a = b || b = c || a = c)
The current test suite doesn't catch that because of order.

triangle: More combinations of non-isosceles triangles

---

exercises/sum-of-multiples/canonical-data.json

This change addresses 0 as a possible input factor with a test case.
As I was solving this exercise on the Haskell track, Frerich pointed out that my solution didn't terminate for `sumOfMultiples [0] 1`. This was due to `[0,factor..limit-1]` producing an infinite stream of zeroes. Since the only multiple of 0 is 0 itself, the result should be 0.
The problem description is (perhaps deliberately) vague about the sign on the input types ("Given a number", "particular numbers") and the output type ("unique multiples"). But it still sort of implies that all are non-negative, since otherwise there would be infinitely many negative multiples *up to but not including that number*, given no lower bound.
I propose that we keep things simple and continue to not test for or make any rewording …

sum-of-multiples-1.3.0: the only multiple of 0 is 0

---

exercises/hamming/description.md

With reference to https://github.com/exercism/exercism/issues/4155#issuecomment-410477404 I propose making the language of this exercise easier for non-english speakers.

Hamming: Description.md, language simplification

---

exercises/grep/canonical-data.json

grep: conflicting flags

---

exercises/pythagorean-triplet/description.md

Added missing constraint to the Pythagorean triplet problem that is outlined in the linked Project Euler problem.

pythagorean-triplet: Add missing constraints to description

---

exercises/sum-of-multiples/canonical-data.json

Closes #1367.
For some reason the diff is currently showing against the 1.2.0 version, but that's not what appears to be in master (1.3.0). My only change is the addition of the `multiples of 5 primes up to 100` test case.

sum-of-multiples: handle cardinality > 3 correctly

---

exercises/sum-of-multiples/canonical-data.json

sum-of-multiples 1.3.1
As stated in our guidelines, we want descriptions that tell us why each
case is being tested:
https://github.com/exercism/problem-specifications#test-data-format-canonical-datajson
The canonical data was added in
https://github.com/exercism/problem-specifications/pull/206 during a
time when descriptions were not required.
Then, placeholder descriptions were added in
aaa47eef1af516f96cdffc0aa23b63e06367c6fd and it was acknowledged at the
time that these descriptions were purely for *schema* compliance, and
not compliance with the guidelines nor a motivation for each case.
By examining the issues that led to each case being added, it is
possible to understand the descriptions.
With more cases being added to sum-of-multiples with clear descriptions,
it's time to bring …

sum-of-multiples: describe the importance of each test

---

exercises/scale-generator/canonical-data.json

Many tracks use automatic or semiautomatic tools to assist in
implementing an exercise for that track. These tools are very
useful, but depend on certain properties of the canonical data.
One such property is that all tests with the same "property"
field should have the same signature: the same keys in the
"input" object and the same type of "expected" object.
The scale-generator exercise used to violate that property:
all tests used the "pitches" property. This PR brings it into
compliance by separating the "chromatic" tests from the
"interval" tests. These new names, in addition to aiding
test generators, are more descriptive than "pitches".

scale-generator: update test properties: one property per signature

---

exercises/simple-cipher/canonical-data.json
exercises/simple-cipher/description.md

- Mention of invalid input removed from README.
- Removed cases that test for invalid input.
These changes follow on the discussion that has taken place in  #902 and #523.  There may be some other examples regarding the discussion that I am missing.  Feel free to point them out.
This PR is intended to be an alternate solution to #1298 to replace #1316.

simple-cipher: remove checks for invalid input

---

exercises/high-scores/canonical-data.json
exercises/high-scores/description.md
exercises/high-scores/metadata.yml

An introductory Array-focused exercise me and @F3PiX worked on.
In the Ruby track, we're lacking an easy exercise with an array as a list and some list manipulations.  
This exercise is meant to fill that gap, and may be interesting for other tracks to implement as well.
We paid extra attention to the sequence of the tests, so the code is building up nicely, and at the end there should be some nice mentoring opportunities left.
It's set up for incremental progress, where students can both learn new things and implement lessons learned;  in the Ruby track, this will be the first exercise where they work with multiple methods, and the string interpolation that they know from TwoFer is here too, but now they have to prevent double spaces.   
We created the Ruby implementation …

high-scores: New exercise

---

TOPICS.txt

See exercism/exercism#4110
Stumpled upon this while implementing a new exercise.
I would suggest to keep the topics list naming conventions consistent with the topics that should be used in the config.json of each track.

topics.txt: Change topic 'mathematics' to 'math'

---

exercises/sum-of-multiples/canonical-data.json

The factor 0 is being tested since #1362. This adds a test where 0 is tested as a multiple when it isn't the only multiple. This catches errors where, if 0 is a factor, the entire result is said to be 0.

sum-of-multiples: the factor 0 does not affect the sum of multiples of other factors

---

exercises/list-ops/description.md

Adds a cursory description of each of the basic operations described in the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/list-ops/canonical-data.json) for this exercise.
Closes #1369.

list-ops: add description of basic operations

---

exercises/acronym/canonical-data.json

This is a redo of PR #1375, to be held until later review!
The current solution for Acronym doesn't account for apostrophes, it is a more rare case for acronyms but an edge case nonetheless. Is this useful?
I added a single test case and incremented the version number.

Acronym: New test case for apostrophe

---

exercises/wordy/canonical-data.json
exercises/wordy/description.md

By explicitly testing these we are making sure that the implementation
fails in an appropriate way, rather than failing in an inappropriate way
or erroneously giving an answer.
For example, in languages using an optional for their answer, ensuring
that [`None` is returned instead of panicking/aborting][1].
[1]: https://github.com/exercism/rust/pull/704#discussion_r230593072
This is beneficial because the problem is partially about building a
parser (even if very rudimentary), and it's common for parsers to have
to deal with errors like this. We may otherwise see some unfortunately
fragile parsers.
~~Intentional merge conflict for the same reason as #1382~~

wordy: test that various syntax errors are in fact syntax errors

---

exercises/wordy/canonical-data.json
exercises/wordy/description.md

It's possible to have a healthy debate about whether a problem with zero
operations really should count as in scope.
One might expect that a generically-written solution would indeed accept
such a problem.
Consider an implementation that strips away all tokens except for
numbers and the four recognised operators (ignoring the intro like "What
is"). Such an implementation would now be required to distinguish
between the valid "What is 5?" versus the invalid "What is 4 cubed"
instead of simply stripping away the "cubed" and declaring the problem
invalid because it only contains the single token `4` (for that would
also declare `What is 5?` invalid)
Note that this PR intentionally has a merge conflict to prevent accidental merges. The merge conflict is trivially resolvable if it is decided …

wordy: test that problems with zero operations give the correct answer

---

exercises/hamming/canonical-data.json

hamming: remove mention of -1 as error indication

---

exercises/bracket-push/canonical-data.json

Add test case for too many closing brackets. Without the extra
closing bracket the string is legal, so this may fail certain
stack based solutions that pass the other tests.
Resolves #1386

bracket-push: Add test case v1.5.0

---

exercises/clock/canonical-data.json

I encountered a solution that passed all provided test cases but would have failed this test.

clock: Add test case for exactly negative sixty minutes.

---

exercises/binary-search/canonical-data.json

this test can catch a solution that explicitly checks for an empty array
but fails to check if the bounds cross
plus test description tweak

binary-search: test for when l and r bounds cross

---

exercises/dnd-character/canonical-data.json
exercises/dnd-character/description.md
exercises/dnd-character/metadata.yml

Dungeons & Dragons character generation involves rolling and picking dice.
This seems like a nice and easy introduction to (pseudo-)random generators.
There were some uncertainties with regards to how to express non-unit properties in canonical data.
Also, I'm not sure if the `[Troll]` reference was correctly formatted in Markdown.

dnd-character: add new exercise

---

exercises/pythagorean-triplet/description.md

This form of the problem was ratified in the canonical data
https://github.com/exercism/problem-specifications/pull/1332
Closes https://github.com/exercism/problem-specifications/issues/1211

pythagorean-triplet: Describe problem with variable sum N

---

exercises/gigasecond/description.md

That a gigasecond is 10^9 seconds only needs to be stated once.

gigasecond: define gigasecond only once

---

exercises/wordy/canonical-data.json

wordy 1.5.0
In keeping with [1.3.0][], we want to test that these fail in an
expected way rather than an unexpected way.
[1.3.0]: https://github.com/exercism/problem-specifications/pull/1383
For example, imagine a language that uses an optional as the answer. We
would want to make sure an implementation written in that language would
return `None`, rather than (say) accessing an out-of-bounds index due to
always assuming that the inputs will have at least three space-separated
elements (of the form "What is X...?").

wordy: Test question `What is?` because it's too short

---

README.md

README.md: Add instruction for exercise glyph creation

---

CONTRIBUTING.md

History
=======
When discussing creating a new exercise, there's the question of any
timing dependencies between the problem-specifications repo and the
track-specific repos.
Recall that it was once required that the problem-specifications PR be
merged first, because READMEs are generated; if the problem
specification did not exist, the README generation would fail and the
student experience would be negatively impacted.
Since https://github.com/exercism/meta/issues/15, READMEs are no longer
generated but included in the track-specific repos, so the absolute
dependency ("must not") no longer applies.
Discussed in https://github.com/exercism/problem-specifications/pull/1384
Change and motivation
=====================
Change the "must not" to a suggestion.
I've written down all reasons …

CONTRIBUTING: Explain reasons for track dependencies on this repo

---

exercises/sgf-parsing/canonical-data.json

Based on [this comment](https://github.com/exercism/problem-specifications/pull/1269#discussion_r206646675) I gathered, that it is OK to add an explicit field

sgf-parsing: Added an explicit 'children' field in the 'node without properties' test case

---

exercises/hamming/canonical-data.json

hamming: remove redundant test cases

---

exercises/sgf-parsing/description.md

Was confused the first time I have read the example of the SGF format, since there are three properties (`FF`, `C` and `SZ`), but the description mentions only two

sgf-parsing: Added the description of the missing SZ property in the SGF format example

---

exercises/dnd-character/canonical-data.json

I came across an implementation that simply randomized each property whenever it was called, something like:
```
class Character():
def strength():
return randint(3, 18)
```
These values should be calculated only once each. Checking one twice should verify that this is the case.

dnd-character: add test for one-time ability init

---

exercises/dnd-character/metadata.yml

Currently, the exercise shows up as 'Dnd Character' when 'DND Character' would be more appropriate.
I don't need to bump any version number for this change, right?

dnd-character: Add title to metadata

---

exercises/luhn/canonical-data.json

From [luhn: add test case with non-digit at the end](https://github.com/exercism/go/pull/1186):
> Problem: I had a student only include the digits before the first invalid character. There was no test that failed his solution.
> Solution: Added a test that should return false but does not if the student takes only the numbers up to first non-digit.

luhn: non-digit at end is invalid

---

exercises/matrix/canonical-data.json
exercises/matrix/description.md

Matrix indices are usually defined so that (1, 1) is the top left entry, not (0, 0). See for example any linear algebra textbook or [wikipedia](https://en.wikipedia.org/wiki/Matrix_(mathematics)#/media/File:Matrix.svg):
Even in programming, this notation is more commonly used in the context of matrices, not 2d arrays, (e.g. in Matlab, Fortran, Julia, ...) than a 0-based matrix notation.
It's less confusing for a student if the canonical definition and notation is used, so this PR changes the `canonical-data` and `description` accordingly.

matrix: Switch to canonical notation of matrix indices

---

exercises/phone-number/canonical-data.json

Alphanumerics didn't seem to make much sense as it's only the letters that are the issue here.

phone-number: improve error message for letters

---

exercises/saddle-points/canonical-data.json
exercises/saddle-points/description.md

The description for 'Saddle Point' illustrates what a saddle point is by showing an example matrix:
```text
0  1  2
|---------
0 | 9  8  7
1 | 5  3  2     <--- saddle point at (1,0)
2 | 6  6  7
```
Because there are at least two completely reasonable coordinate systems which could apply here, `(1,0)` is ambiguous (does it mean "column 0, row 1", which is in fact correct, or "row 1, column 0"?)
This PR makes it unambiguous:
```text
0  1  2
|---------
0 | 9  8  7
1 | 5  3  2     <--- saddle point at column 0, row 1, with value 5
2 | 6  6  7
```
Fixes #313.
This is also a good complement to the test data, which specifies:
```json
"expected": [
{
"row": 1,
"column": 0
}
```

saddle-point: use unambiguous coordinates

---

exercises/acronym/canonical-data.json

Many regular expression libraries have a way to detect word boundaries,
but their definition of word characters includes underscores.
`\b` and `\w` metacharacters were designed to detect programming language keywords,
and it is a common mistake to use them to match words in natural languages.

Acronym: add underscore test case

---

exercises/rest-api/canonical-data.json

Resolves #1439 by adding a test case when the previous lender becomes the borrower and borrows the same amount as the current balance thus zeroing the balances and removing the respective owes and owed_by for both parties.   This exercises some necessary code for this case that was previously not covered.  In zeroing balances it is self consistent with the previous two exercises that change balances and whom is owed/owes.

rest-api - add new test "lender owes borrower same as new loan"

---

exercises/rest-api/canonical-data.json

User balance of test "lender owes borrower same as new loan" is not formatted as the previous cases. For example "lender has negative balance" has an expected user balance of zero formatted as "0.0" as all other values while the last test has zero formatted as "0".

REST-API: Update expected user balance of last test

---

exercises/darts/canonical-data.json

I was just mentoring an exercise where the students solution treated the target as a square (as opposed to a circle), and was surprised that it nevertheless passed the tests.
I found that they only (except for one, that accidentially works still) use coordinates where one of them is `0`, which also works if the solution calculates scores as if the target was a square.
I also noticed that, while the target is supposed to be a circle centered at `(0, 0)`, so that there are valid target areas with negative coordinates, there are no test cases that provide negative coordinates at all.

darts: augment test suite

---

exercises/hamming/canonical-data.json

Add an extra test case about one empty strand based on the discussion in exercism/haskell#796 to avoid wrong recursion solution.

Hamming: Add a test case to avoid wrong recursion solution

---

exercises/high-scores/canonical-data.json

In Ruby the test for HighScores#personalTop is 
```ruby
def test_personal_top
scores = [50, 30, 10]
expected = [50, 30, 10]
assert_equal expected, HighScores.new(scores).personal_top
end
```
I solve exercises purely from the tests, and this test didn't give me any information about what the method actually does. I think the method should be called "personalTopThree" and the input for the first test should be an array with greater than three numbers.

Rename personalTop to personalTopThree

---

exercises/list-ops/canonical-data.json

The following implementation of `reverse` passes all existing tests but fails the new test:
```Python
def append(base_list, to_append):
if isinstance(to_append, list):
for x in to_append:
base_list.append(x)
else:
base_list.append(to_append)
return base_list
def length(base_list):
return foldl(lambda a, b: a + 1, base_list, 0)
def foldr(function, base_list, acc):
while length(xs):
acc = function(base_list.pop(), acc)
return acc
def reverse(base_list):
return foldr(lambda b, a: append(a, b), base_list, [])
```

list-ops: add test case for reversing nested lists

---

exercises/high-scores/canonical-data.json
exercises/high-scores/description.md

After the discussion on #1456, @F3PiX and I suggest removing the `report` method entirely. That's the single change in this PR.
closes #1456

high-scores: Remove report method

---

exercises/resistor-color/canonical-data.json
exercises/resistor-color/description.md
exercises/resistor-color/metadata.yml

The main purpose of this exercise is to add a very simple, array-based exercise that can serve as a very gentle introduction to arrays. As such, it has no error handling and the array is fixed.
There will be an issue opened relating to this PR later.
Closes #1458

resistor-color: add new exercise

---

exercises/simple-cipher/canonical-data.json

I just come across a solution for the "Simple Cipher" exercise from a student, which could encode messages longer than the key but failed to _decode_ messages longer than the key, and yet, because we haven't a test to cover this, all tests would pass giving an illusion of correctness.
This pull request adds a test to also check that a message longer than the key can be decoded.

simple-cipher: test that messages longer than the key can be decoded

---

exercises/simple-cipher/canonical-data.json

#1460 erroneously named a property `plaintext`. This fixes it to `ciphertext`.
Also the version bump is made a major bump according to versioning guidelines.

simple-cipher: Fix property name and major bump

---

exercises/leap/canonical-data.json

This adds a new test that will fail if students use `year % 2 === 0` instead of `year % 4 === 0`.

leap: Add test case for year divisible by 2 but not by 4

---

exercises/two-fer/description.md

The table table with examples in the two-fer readme is center aligned this is not very readable. This PR makes the table left aligned.

two-fer: Left align example table for description.

---

exercises/rational-numbers/canonical-data.json

Currently there's only a test for a negative num, but not a negative den.

rational-numbers: add abs test case for den < 0

---

exercises/triangle/canonical-data.json

Proposed fix to https://github.com/exercism/csharp/issues/1253
The current [Test] names confused me when I was doing the exercise. It was also difficult to see which tests failed, because of long method names combined with a small window with the test results.
This PR changes the "Returns_true_if_the_triangle_is_equilateral_false_if_any_side_is_unequal" style in favour of a pattern that follows "equilateral_triangle_returns_false_if_any_side_is_unequal".

triangle: Add clarity to test descriptions

---

exercises/darts/metadata.yml

I think 'excersie' is meant to be 'exercise'

Darts: Correct typo in metadata

---

exercises/darts/canonical-data.json

The current tests allow an erroneous-but-passing solution where the sum of the absolute values of the coordinates of the dart are compared to the radius thresholds (ie return 5 if `abs(x) + abs(y)` is greater than 1 but less than or equal to 5), rather than the calculated distance of the dart from the origin. Thanks to [grwkremilek](https://exercism.io/tracks/python/exercises/darts/solutions/fd550c5405d64d84be3312566b300e1b) for the find.

darts: add tests to disallow absolute addition

---

exercises/allergies/canonical-data.json

The canonical-data for allergies wasn't in a format consistent with other exercises, and relied on a comment that explained that some of the expected results were actually an array of answers with the expectation that each one was a separate test. This is not possible to detect automatically and differentiate it from tests that expect array results. (I can only assume that other tracks which generate have hand edited their results).
Looking at how all the current tracks have interpreted the spec,  they have all specified an  "allergicToItem: 'eggs' forScore: 1"  type of approach... so I propose modifying the json use sub cases to specify each one individually (this is done for lots of other exercises already).
I think this is the simplest approach - otherwise we need to adjust the schema …

Allergies: Modified canonical description to make it generatable

---

exercises/markdown/canonical-data.json

Adds a tests for unordered lists with surrounding content; many solutions I've seen are not properly closing an unordered list when there's content below the list's final item.

markdown: unordered lists with surrounding content

---

exercises/armstrong-numbers/canonical-data.json

[`0` is also an Armstrong number](https://en.wikipedia.org/wiki/Narcissistic_number) and needs to be tested for explicitly if students are using a base 10 logarithm to calculate the number of digits for which `0` is a case that needs special handling.

Zero is an Armstrong number and requires specific testing

---

exercises/queen-attack/canonical-data.json

There is a flaw in the Queen Attack test suite that causes the most naive implementation that makes the tests green to actually be incomplete.
The tests for "third diagonal" (2, 2 and 1, 1) and "fourth diagonal" (2, 2 and 5, 5) actually test for the same diagonal (A1 to H8) and are fulfilled by the condition `row1 = column1 && row2 = column2`. This does not cover the parallels of that diagonal, however, so if there was an additional test for (0, 6) and (1, 7) that would still be red.
This is fixed by replacing the redundant "fourth diagonal" test values with said (0, 6) and (1, 7), which will require the condition to be changed to `row1 - column1 = row2 - column2`, thus covering all diagonals from "top left" to "bottom right".
That said, the tests for "first diagonal" and "second …

Correct Queen Attack test values

---

exercises/forth/canonical-data.json

The error msg expectations don't match other similar error patterns and so it breaks auto generated tests

Forth - Corrected minor typos in the error msgs

---

exercises/yacht/canonical-data.json

simple implementations checking only uniques will otherwise pass the test suite.
I submitted a solution with
```
case YachtCategory.BigStraight:
return dice.OrderBy(x => x).Distinct().Count() == 5 && dice.Max() == 6 ? 30 : 0;
```
which incorrectly identifies 6, 5, 4, 3, 1 as a big straight.

yacht: Add "No pairs but not a big straight" test case

---

exercises/luhn/canonical-data.json

Currently the test have only valid numbers (a) without spaces, (b) with
an even number of spaces, or (c) where all digits are 0.
That allows an approach where you iterate from left to right, starting
with a factor of `2 - length(number) % 2`
In Python:
```python
class Luhn(object):
def __init__(self, card_num):
self.card_num = card_num
def is_valid(self):
sum = 0
digit_count = 0
factor = 2 - len(self.card_num) % 2
for c in self.card_num:
if c == ' ': continue
if not ('0' <= c <= '9'): return False
digit_count += 1
digit = int(c) * factor
if digit > 9: digit -= 9
sum += digit
factor = 3 - factor
return digit_count > 1 and sum % 10 == 0
```
Adding a test case where a valid number has an odd number of spaces can
catch that invalid approach.

Luhn: Add a test with an odd number of spaces

---

exercises/connect/description.md

The canonical test input is now similar to what is shown in the description, but the description says it isn't. Fixes #1435.

Connect: remove obsolete sentence from description

---

exercises/luhn/canonical-data.json

luhn: Update non-ASCII test case

---

exercises/reverse-string/canonical-data.json

Currently the tests have only odd sized strings. That allows an approach
to pass that does not work on even sized strings:
```cpp
std::string reverse_string::reverse_string(std::string str)
{
if (str.size())
for (auto a = str.begin(), b = str.end() - 1; a != b; ++a, --b)
std::swap(*a, *b);
return str;
}
```
The problem is `!=` instead of `<`.
Adding a test with an even sized string catches that invalid approach.

reverse-string: Add a test with an even-sized word

---

exercises/etl/canonical-data.json

This reverts commit 0df9a334ac622c63ed47be1ccb30c751265ad4ae.
I have confirmed that no JSON version change is needed

Revert "ETL descriptions too long"

---

exercises/anagram/description.md

- Add definition of anagram
- Improve readability
Fixes #1528

Improve anagram problem statement

---

exercises/robot-simulator/canonical-data.json

[Edit] Some language tracks (e.g. Pharo) individually identify tests.  To auto-create these identifiers during code generation, the only data currently available is the canonical data "description" field.  Some tracks insert this field directly into their generated code as a comment, and the "descriptions" are suitably verbose for that purpose.  However such verbosity generates some very long identifiers (e.g. >150 characters).  
Issue #1473 proposed to adding a distinct "identifier" field.  Back-pressure there directed me to first try compressing "descriptions" to suit "identifier" generation.  This PR is a trial at doing that - minimizing description length without losing information.  However even if no substantive information is lost, I such compression may compromise the readability …

Robot simulator descriptions too long

---

exercises/etl/canonical-data.json

Such a long test is really a comment, not a description to be used as a test identifier.
Make it so, per #1473

ETL descriptions too long

---

exercises/darts/canonical-data.json

Cover the edge case where a student might only think to check if `distance > 0` rather than `>= 0`, or similar.

[Darts] Add additional edge case

---

.travis.yml
OPTIONAL-KEYS.txt
README.md
bin/check_optional
canonical-schema.json

This adds the [most-liked](https://github.com/exercism/problem-specifications/issues/1492#issuecomment-481125708) implementation of an optional key. See #1492, #1496 for more info.
Ideally this should be a draft PR, but I wanted CI to run to spot potential issues.

[RFC] Add 'optional' key to canonical-schema

---

exercises/word-count/description.md

Improves the description of `word-count` to address issues described in #1539, #1461 and #869.
Removing ambiguity from the meaning of a "word" should reduce the amount of churn for students, and also clarify that tests are _not_ required for English anachronisms and vernacular _not_ covered by the explicit definition.
Please chime in if anything about my wording could be improved.

word-count: improve description

---

exercises/pangram/canonical-data.json

The purpose of the "description" field is to derive identifiers for naming generated test methods, but some descriptions have tended to verbosity ending up with long identifiers (up to 150 characters). Such long method names are harder for students to work with and also are awkward for some IDE GUIs.
Issue #1473 proposed adding a separate "identifier" field, but I was required to first try improving "descriptions" to better suit "identifier" generation. This PR aims to slim down the generated identifiers without losing substantive information about the test.
To start with,  "Check if the given string is a pangram" is a rather banal redundant description unworthy of nesting.

pangram: Slim down descriptions to generate better test identifiers 

---

exercises/darts/canonical-data.json

The purpose of the "description" field is to derive identifiers for naming generated test methods, but some descriptions have tended to verbosity ending up with long identifiers (up to 150 characters).  Such long method names are harder for students to work with and also are awkward for some IDE GUIs.
Issue #1473 proposed adding a separate "identifier" field, but the consensus there was to first try improving "descriptions" to better suit "identifier" generation.    This PR attempts to slim down the generated identifiers without losing substantive information about the test.
For the longest descriptions here, I couldn't recognize the significance of...
```
dart whose coordinates sum to > 1 but whose radius to origin is <= 1
```
While considering a shorter alternative, it helped …

[Darts] Slim down generated method names

---

exercises/etl/canonical-data.json

This supersedes stale PR #1485. (It was easier to redo off HEAD than resolve conflict there)
Background - In practical terms for test generation, the the number of "input" elements is the number of parameters of the function-under-test.  Considering the following as an example which specifies a function with three parameters as input...
[all-your-base Canonical-data](https://github.com/exercism/problem-specifications/blob/master/exercises/all-your-base/canonical-data.json#L19-L23)
```
{
"description": "single bit one to decimal",
"property": "rebase",
"input": {
"inputBase": 2,
"digits": [1],
"outputBase": 10
},
```
This is reflected by several language implementations:
[all-your-base CSharp](https://github.com/exercism/csharp/blob/master/exercises/all-your-base/AllYourBaseTest.cs#L25) …

ETL: input elements define function parameter count

---

exercises/anagram/canonical-data.json

Add two test cases to catch some weird solutions where all words are rejected if the matched words have different case.
Original PR on the cpp track: exercism/cpp#297

Anagram - add test cases for differently-cased words

---

exercises/circular-buffer/canonical-data.json

This change is intended to make the initial clear test case a little more strict - testing the overwrite and read fail capability after clearing as well.
The test case was also moved because it now uses overwrites and duplicating the test case didn't seem reasonable.
Original PR on the C++ track: exercism/cpp#296
This is an edge case that could happen when the clear alters the way the end of container is handled, as shown in the above PR. However, as also discussed, it is currently very specific and could be accidentally circumvented.

Circular buffer - add test case for initial clear wrapping

---

exercises/resistor-color-trio/canonical-data.json
exercises/resistor-color-trio/description.md
exercises/resistor-color-trio/metadata.yml

resistor-color-trio: add exercise

---

exercises/resistor-color-duo/description.md

See https://github.com/exercism/problem-specifications/issues/1471
The current stories for Resistor Color and Resistor Color Duo raised some questions, as collected in the issue mentioned above.
Recap of the wishlist:
- Avoid the word 'encoding' 
- Don't make the listing of the color and its value look like a dictionary.
- Make it more explicit that a color band has a numeric value _and_ a position.
This commit is addressing these, and will be adapted for the other exercises in the series. 
The original story has been written by the product team, to make it an exemplar for future descriptions, so let's keep that as is.

Fix story Resistor Color Duo

---

exercises/word-count/canonical-data.json

This should catch cases when only up to either the first word's or second word's length of characters are compared, counting substrings from the beginning under the same word.
[Original thread in the track-c channel on Slack](https://exercism-team.slack.com/archives/CATCU7LSJ/p1563419221002800)

Word count - add test case for substrings from the beginning of words

---

exercises/raindrops/description.md
exercises/raindrops/metadata.yml

Currently the description.md implies a solution where the student generates _all_ factors of a number and then tests for membership within that set; that's a frustrating and unnecessary wild good chase for a beginner, and I've had multiple students trip up on it. This updates to be a little less ambiguous and to add some informational links.

raindrops: simplify description.md

---

exercises/high-scores/canonical-data.json

This PR adds a new property to HighScores that returns a boolean indicating whether the latest score is the personal best.
This was suggested by @F3PiX ~who will update this description with more details soon.~
Update:
A previous version of the exercise had a 'report' method, that contained a boolean check. The `report` was removed when it proved to be a burden to mentor without adding enough learning value. 
This explicit boolean method brings back the boolean. :yay:
I chose to name the property `latestIsPersonalBest` in part because we will name the method `latest_is_personal_best?` in Ruby, but I can change it to something like `isLatestPersonalBest` if people think it's better for the other tracks.
@SleeplessByte @ErikSchierboom

high-scores: Add latestIsPersonalBest method

---

exercises/resistor-color-duo/canonical-data.json
exercises/resistor-color-duo/description.md

This PR aims to fix a basic implementation bug whereby any additional colors are also used in the calculation.

resistor-color-duo: add test case to ignore additional colors

---

exercises/resistor-color-duo/description.md

Resistor-color-duo: Update description for version 2.1

---

OPTIONAL-KEYS.txt
exercises/resistor-color-trio/canonical-data.json

This PR adds an additional test case for an invalid color. As not every track might want to implement this, I've added an optional key named `"error"`.
This PR is intended to be used in the track anatomy project, and as such, targets the `trackanatomy` branch.
Edit (Maud):

Resistor color trio: test invalid color

---

exercises/matrix/canonical-data.json

In javascript the following wrong implementation passes all previous test cases but not the new one
```
export class Matrix {
constructor(string) {
this._rows = string
.split('\n')
.map(row => row.split(' ').map(Number))
this._columns = this._rows
.map((_, i) => this._rows.map(row => row[i]))
}
get rows() {
return this._rows
}
get columns() {
return this._columns
}
}
```

Matrix: Add test case

---

exercises/leap/canonical-data.json

leap 1.6.0
Some implementations unexpectedly pass the entire test suite:
* Replacing 4 with 499, 998, or 1996
* Replacing 100 with 5, 10, or 20
* Replacing 100 with 3, 6, 12, 15, 30, 60, 75, 150, 300 
* Replacing 400 with 125, 250, 500, 1000, or 2000
Adding these test cases would correctly point out that these solutions
are incorrect.
I think it's a bit unusual since no student is going to write such an
implementation except a student deliberately trying to slip past the 
tests.
Or maybe a student trying to micro-optimise? Maybe they are trying to
test whether division by small numbers is faster than division by large
numbers?
But discussion participants have deemed that the cost of three tests is
worth the benefit of reducing mental overhead of mentors, since such
solutions have in fact …

leap: Add years that refute some unusual factors

---

exercises/paasio/metadata.yml

See how it is currently listed as Paasio:
http://exercism.io/tracks/go/exercises/paasio
http://exercism.io/tracks/rust/exercises/paasio
Given that the game is about input/output statistics for a
platform-as-a-service, "PaaS I/O" seems a better way than the default.

paasio: Title as "PaaS I/O" instead of default "Paasio"

---

exercises/robot-name/description.md

While working on exercism/perl5#328, I noticed that the description of robot-name mixed singular and plural.  This PR changes robot-name/description.md to use singular forms consistently throughout.  I also changed "boot up" to "turn on" in hopes of making it easier for non-native English speakers to understand the text.
This is my first contribution to this project - thank you for considering this PR!

robot-name description: singular "robot"

---

CONTRIBUTING.md

I noticed a dead link in the Contributing guide.
This fixes it by pointing to the Website repo instead.

Fix broken link to website contributing document

---

exercises/connect/description.md

Replaced "rhombus" with "parallelogram" to clarify that the game's board height and width must not be the same. Closes #1597

connect: Replaced rhombus with parallelogram

---

exercises/minesweeper/description.md

Updates the board example to remove the need for a border that doesn't match the test data and clarifies a couple small points in the description.md.
If merged:
Resolves #1555
Closes #1594

minesweeper: remove border

---

exercises/list-ops/canonical-data.json

Per #1609, this change makes the ordering of inputs implied by the description match the inputs as they are actually supplied.

list-ops: change order in append test case description

---

exercises/bob/canonical-data.json

Resolves #1630
Updates two cases to use less offensive language on input data.

Bob: Cleans up language on a couple of test cases

---

exercises/luhn/canonical-data.json

I saw a student accidentally pass the test suite just by checking the parity (divisibility by 2) of the final sum instead of the divisibility by 10. A lot of algorithms involve checking of parity so I can see such mistakes slipping in from time to time.
The only two proper numbers that are not valid in the test suite sum to 41 and 57.
Initially, I thought about testing all the possible remainders using the simplest inputs of `01` through to `09` but maybe that's beyond the purpose to provide a sane yet fairly straightforward test coverage.
Anyway, I think it's a good idea to test at least one proper number that is not valid and has an even remainder.

luhn: check a number with an even remainder

---

exercises/two-bucket/description.md

There has been confusion over the reuse of the word "one" in both the descriptions of the bucket ("Bucket one") and the moves ("Move from one bucket"). This removes that confusion, which will help reduce misunderstanding, especially amongst non-native English speakers.
With reference to https://github.com/exercism/exercism/issues/5205#event-3090216965

[two-bucket] Make valid moves clearer

---

exercises/scale-generator/description.md

The interval described is an augmented *second*, not an augmented first.
Added also its composition in terms of steps for completeness.
Fixes #1642
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

scale-generator: fix name of augmented interval

---

exercises/simple-linked-list/metadata.yml

Previous web.archive.org link pointed to the book homepage.
Change it to point to simple-linked-list page.
Previous: https://github.com/exercism/problem-specifications/pull/1648

Fix metadata source_url for simple-linked-list exercise

---

exercises/simple-cipher/description.md

The test suite is testing against the key having only lowercase letters, not alphanumeric.

simple-cipher: Update description.md

---

exercises/pangram/canonical-data.json

I received one solution where it was only checked whether there are exactly 26 letters (case sensitive)
This would result in that `a...m A...M` is a pangram for example.
Also fails if there are more than 26 letters when counting i.e o and O as two different ones.

Pangram: check case insensitive behavior

---

exercises/pangram/canonical-data.json

Reverts exercism/problem-specifications#1658

Revert "Pangram: check case insensitive behavior"

---

exercises/robot-name/metadata.yml

gSchool.it is now a domain parking spot

robot-name: remove dead link

---

.github/workflows/ci.yml

This makes it easier to tell what test failed without leaving the PR view. It also clarifies what "Run JS tests" actually does.
Before: 
After:
---
@iHiD This would require changing the required check to `required-files` and `schema-validation`.

CI: Clean up workflow and clarify what "JS tests" are

---

exercises/list-ops/canonical-data.json

Subsequent to #1611 (which is itself pursuant to #1609), this will complete the permutation of the possible use cases for appending lists.
This is addition is from the suggestion of @petertseng in https://github.com/exercism/problem-specifications/issues/1609#issuecomment-542440691
Probably should be held until #1560 is resolved however, so adding the hold label already myself 😃

list-ops: add append case

---

exercises/diffie-hellman/canonical-data.json

There are some languages where the syntax `1 .. p` includes the endpoints.
For example, the Nim code:
```Nim
for i in 1 .. 3:
echo i
```
shows the output:
```
1
2
3
```
Therefore "in range 1 .. p" would have been especially confusing, given that it was intended to **exclude** the endpoints.
So let's use the wording from the `description.md`:
https://github.com/exercism/problem-specifications/blob/126568d7bddcb0696a3a4202030b240866a41889/exercises/diffie-hellman/description.md#L13-L14

diffie-hellman: Reword 'in range 1 .. p'

---

exercises/run-length-encoding/canonical-data.json

This makes it more consistent with another test:
https://github.com/exercism/problem-specifications/blob/ea119358dde6e7c3ce5673a5d939bb4976a80d88/exercises/run-length-encoding/canonical-data.json#L53-L54
Both forms are correct, but "lowercase" is more common. See:
https://english.stackexchange.com/questions/59409
We probably don't need to mandate an exercism-wide style for this, but I think it should at least be consistent within an exercise. The other exercise that is inconsistent within its `canonical-data.json` is `isogram`. 
Here are the relevant occurances of "lower":
```
acronym/canonical-data.json
18:          "description": "lowercase words",
affine-cipher/canonical-data.json
6:    "* Decoding from affine cipher to all-lowercase-mashed-together English" …
```

run-length-encoding: 'lower case' -> 'lowercase'

---

exercises/isbn-verifier/canonical-data.json

Most of the test descriptions just used 'isbn', so let's be consistent and avoid "International Standard Book Number number" (https://en.wikipedia.org/wiki/RAS_syndrome)

isbn-verifier: 'isbn number' -> 'isbn'

---

exercises/perfect-numbers/canonical-data.json
exercises/perfect-numbers/description.md
exercises/perfect-numbers/metadata.yml

There is no convention whether zero is a natural number, so let's avoid
the issue.
For example, see:
- https://mathworld.wolfram.com/NaturalNumber.html
- https://en.wikipedia.org/wiki/Natural_number
- https://math.stackexchange.com/questions/283/is-0-a-natural-number
The previous wording of
```
"description": "Zero is rejected (not a natural number)",
```
could be especially jarring for some tracks. For example, Nim defines
`Natural` and `Positive` types, and `Natural` includes 0. See:
- https://nim-lang.github.io/Nim/system.html#Natural
Note, the other exercises that mention "natural" are:
```
difference-of-squares/description.md
1:Find the difference between the square of the sum and the sum of the squares of the first N natural numbers.
3:The square of the sum of the first ten natural …
```

perfect-numbers: 'natural number' -> 'positive integer'

---

exercises/grains/canonical-data.json

The top-level `description` of all these cases was:
```
"description": "returns the number of grains on the square",
```
but each test-level `description` contained only a number.
The comments in `tests.toml` are generated only from the test-level
`description`, and so the comments there will now be more informative
the previously seen:
```toml
[canonical-tests]
"9fbde8de-36b2-49de-baf2-cd42d6f28405" = true
"ee1f30c2-01d8-4298-b25d-c677331b5e6d" = true
"10f45584-2fc3-4875-8ec6-666065d1163b" = true
"a7cbe01b-36f4-4601-b053-c5f6ae055170" = true
"c50acc89-8535-44e4-918f-b848ad2817d4" = true
"acd81b46-c2ad-4951-b848-80d15ed5a04f" = true
"c73b470a-5efb-4d53-9ac6-c5f6487f227b" = true
"1d47d832-3e85-4974-9466-5bd35af484e3" = true
"61974483-eeb2-465e-be54-ca5dde366453" = true …
```

grains: Be more verbose in test-level descriptions

---

STYLE-GUIDE.md

As discussed in a few PRs in the last few days, I'd like to add a style guide that we can use as a guide for grammatical/language changes in descriptions etc. These should avoid debates on language, as all discussions can defer to this document, and in cases where this document does not document a style and there is not consensus, an executive decision can be made, added to this document, and then adhered to moving forward.
To get the ball rolling, I propose having a `STYLE-GUIDE.md` file, with a guidance and example for each point. I've put this together as a rough PR to get discussion started.
Please consider it both from the general case (how the style guide should work) and the specific points in this PR.

Add Style Guide

---

exercises/square-root/canonical-data.json
exercises/square-root/description.md
exercises/square-root/metadata.yml

An exercise to calculate the square root of natural numbers.
The tests allow an implementation that is simplified because they do only require natural roots less than 256.
https://github.com/exercism/c/pull/408

Square-Root: Add new exercise

---

.github/workflows/ci.yml

This is useful for debugging CI or when working on a branch before opening a PR

CI: Add workflow_dispatch as manual trigger

---

package.json
yarn.lock

A dependabot alert raised by GitHub on my fork of this repo: https://github.com/artamonovkirill/problem-specifications/network/alert/yarn.lock/minimist/open
Also, the same vulnerability is reported by `yarn audit`:
```
yarn audit v1.22.10
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3                                    │
├───────────────┼────────────────────────────────────────────────────────── …
```

security: CVE-2020-7598

---

exercises/grade-school/canonical-data.json

Diff:
```diff
- "description": "Adding more student adds them to the sorted roster",
+ "description": "Adding more students adds them to the sorted roster",
```

grade-school: Fix typo in test description

---

exercises/queen-attack/canonical-data.json

Diff:
```diff
- "description": "can not attack",
+ "description": "cannot attack",
```

queen-attack: Fix typo in test description

---

README.md
workflows/README.md
workflows/ci.yml
workflows/configlet.yml
workflows/pr.ci.yml

Based on all the feedback I got from @SaschaMann, I've created a baseline set of workflows anyone can use. This is meant to set-up the correct triggers and files, NOT the actual CI (how to run the test/how to do x y z).
1. I'm not looking for a long debate on how to optimise these further. This is meant to be an easy way for maintainers to get started with GitHub Actions, without having to do the research themselves. I invite further optimisations to be PR-ed in.
2. This is not a _great_ place for these files, but it's a good place for discoverability. Recommended by @iHiD , so we're good on that.
3. I'm perfectly fine with changing wording, but please make a suggestion so it can be applied quickly, and then we can merge it in and make further improvements in future PRs.
4. I'm not …

Add workflow recommendations and templates

---

exercises/rational-numbers/description.md

This makes the given formulas easier to read, by using `a₁` instead of `a1` etc.
I don't know if this is covered by #1560, please turn it into a draft if it is.

rational-numbers: Make formulas more readable

---

exercises/two-bucket/canonical-data.json

~~**This is a non-bugfix change to an exercise; accordingly, it is currently under embargo.** Please keep this in mind when taking actions on this pull request.~~ Embargo has been lifted.
1. A test where the goal is too large.
The student solution would need to either:
* (If searching the state space) Notice that there are no further states
to be visited, and yet the solution has not been reached.
* Notice that the goal is larger than the larger bucket, therefore can 
be rejected immediately.
2. A test where the goal is not too large yet still can't be reached
The student solution would need to either:
* (If searching the state space) Notice that there are no further states
to be visited, and yet the solution has not been reached.
* Notice that the goal is not divisible by the GCD of the …

two-bucket: test inability to reach the goal

---

CONTRIBUTING.md

While reading the guide, I found words that couldn't be moved even if I clicked on the words that appeared to be linked. If you have the right link, let me know and I'll fix it. First I deleted it.

Remove linkless words

---

exercises/change/canonical-data.json

In JavaScript we've had this testcase to kick-off the exercise, input and output, without needing to write an actual algorithm. Adding it here for completeness.

change: add simplest test case

---

exercises/prime-factors/canonical-data.json

I checked the commit history and conversations on why these exist in JavaScript. They don't really catch edge cases of the _final_ implementation, but they do provide stepping stones when building the implementation.

prime-factors: add further variations

---

exercises/list-ops/canonical-data.json

The notation `(x, y) => x + y` for `foldl` and `foldr` is ambigious. Yes, there is a mathy standard for fold, but the fact is that this ordering is not consistent across languages, nor is it well known.
This attempts to make it completely un-ambigious what each parameter means, but since they _were_ ambiguous, it's technically a breaking change.

list-ops: reimplement ambiguous tests

---

exercises/hamming/canonical-data.json

fixes #1761 
I note that removing test cases does not show up as a change for the canonical data syncer. Is this an issue?

Hamming: remove tests that don't make sense per 1761

---

exercises/grade-school/canonical-data.json

Commit 03529d08e743 (#1735) added a new test case for the `grade-school`
exercise, but the UUID added was version 1 rather than version 4. This
was not caught by CI because the regex in the schema validator was
too permissive (fixed by #1759).
Some reasons to prefer version 4 UUIDs:
- Version 4 is the right version for a fully random and unique
identifer; we don't want to indicate anything about the machine that
generated the UUID, and version 1 UUIDs have a timestamp and MAC
address component.
- All of the other UUIDs currently in `problem-specifications` are valid
version 4 UUIDs.
- `configlet uuid` generates a version 4 UUID.
- A reader familiar with the UUID specification (RFC 4122) might see a
version 1 UUID and infer that the timestamp or MAC address component
is useful, causing …

grade-school: Change a UUID to be version 4

---

canonical-schema.json

Commit cea02afb494a (#1676) added a UUID to each test case. However, the
regex pattern that it added to the canonical schema was too permissive,
meaning that CI would pass on a PR that added, for example, a version 1
UUID (see #1735).
Changes:
- Use `a-f` instead of `a-z`
- The third group must start with `4`.
- The fourth group must start with `8`, `9`, `a` or `b`.
I also tried to improve the description.
Pinging @SleeplessByte.
Note: The schema validation CI check is expected to fail until we merge https://github.com/exercism/problem-specifications/pull/1760 and rebase this PR on top.

canonical-schema: Fix UUID regex pattern

---

.github/workflows/ci.yml

The SCENARIOS.txt scenarios should be in sync with the scenarios in the schema. See #1758.
For an example of a failing check, see: https://github.com/ErikSchierboom/problem-specifications/pull/2/checks?check_run_id=1655228871

[CI] Verify that scenarios are defined in schema

---

SCENARIOS.txt
canonical-schema.json

When working with canonical data, I often found that one of the first criteria for me to decide whether I want a test case to be implemented is whether it does error handling. In some cases, error handling fits the exercise well, in others less so. While one _can_ figure this out by looking at the structure of the `expected` value, it might be convenient to also add a scenario to these error test cases to allow for easy filtering. Let me know what you think.

Add error scenario

---

SCENARIOS.txt
canonical-schema.json
exercises/diffie-hellman/canonical-data.json

JavaScript has a test case to test if the algorithm is side-effect free, or has the appearance that it is. 
- Tracks that have a functional implementation may test if running the same function twice in succession generates the same result (not this test case)
- Tracks that have an object-oriented approach may test if running the same method with different input generates the correct result (which it arguably wouldn't if p or g were mutated in the process)

diffie-hellman: add immutability / purity test case

---

CONTRIBUTING.md

Now that we have [proper docs](https://github.com/exercism/docs/blob/main/anatomy/tracks/config-json.md) for the `config.json` file, we can use them in our docs. The existing contents was not only outdated, but also incorrect (there has never been a "problems" field as far as I can recall).

Update track configuration file documentation

---

exercises/roman-numerals/canonical-data.json

Fixes #1769 
There were cases where the descriptions where the data did not numerically match the descriptions, such as
```json
"description": "1000 is a single M",
"input": {
"number": 1024
},
"expected": "MXXIV"
```
1. Leave as-is
2. Change the description to match the data
2. Change the data to match the description
There is a slight semantic difference between 2 and 3 if you consider that what this case is testing is not just explicitly that 1024 is MXXIV, but that absent any other test to the effect it also implicitly tests that 1000 is M as the original description states.
I chose 2 as it accurately describes what the test is doing, but 3 is probably as valid a change

Improve descriptions to make sense per #1769

---

README.md

Initially, we decided that the description should also be immutable. However, in practice this lead to quite some unnecessary churn. As we expect changing the description will very rarely lead to issues, we'll make it mutable and deal with issues when they occur.

Indicate that description is mutable

---

README.md
exercises/affine-cipher/description.md
exercises/etl/description.md
exercises/grep/description.md
exercises/rest-api/description.md
exercises/spiral-matrix/description.md
exercises/tournament/description.md

This brings markdown files in line with our new spec (https://github.com/exercism/docs/pull/38) in terms of secondary headers.
@ErikSchierboom will script-PR a `#` header to all exercises seperately.

Bring markdown files in line with new heading spec

---

exercises/hamming/canonical-data.json

I realised that #1762 does not normalize the error messages, it just makes them the same
Additionally, took the opportunity to normalize descriptions to use first strand/second strand, rather than a mix of that and left strand/right strand

hamming: normalize error messages

---

exercises/anagram/canonical-data.json

Exercism has now renamed the main branch of every repo from `master` to
`main`, which makes it logically consistent to also remove references to
`master` in exercise tests. The only one was in the `anagram` exercise:
https://github.com/exercism/problem-specifications/blob/ef9e1e17c84721ee6e9d5a65c8dd3ba2122eac91/exercises/anagram/canonical-data.json#L14-L23 
This commit adds a test case that tries to stay close to the one that it
reimplements, maintaining these properties:
- the `subject` is a six-letter word
- the `candidates` are three six-letter words
- the first and last `candidates` as anagrams
- the non-anagram has one letter in common with the `subject`
Minor hypothetical benefit: if all tracks magically changed to use this test
case it would make it easier to search for 'master' …

anagram: reimplement test case containing 'master'

---

exercises/isogram/canonical-data.json

This test case was inspired by a solution I saw on the Go track that passes the tests but has a bug. This new test case makes the tests fails for that bug. The solution goes like this:
```go
func IsIsogram(inp string) bool {
input := strings.ToLower(inp)
dict := map[rune]int{}
for _, r := range input {
_, found := dict[r]
if found {
if r == '-' || r == ' ' {
break
}
return false
} else {
dict[r] = 0
}
}
return true
}
```
Here the student is using a map as a set to keep track of duplicates, which is standard for this exercise. However they are breaking early if the character is `'-'` or `' '` and is a duplicate, in which case they return `true`. The problem with this solution happens if the string has two or more hyphens (or two spaces) and a character after the second hyphen (or space) …

isogram: add test case with repeated letters and two hyphens

---

exercises/acronym/canonical-data.json
exercises/alphametics/canonical-data.json
exercises/book-store/canonical-data.json
exercises/etl/canonical-data.json
exercises/food-chain/canonical-data.json
exercises/gigasecond/canonical-data.json
exercises/house/canonical-data.json
exercises/isogram/canonical-data.json
exercises/micro-blog/canonical-data.json
exercises/nucleotide-count/canonical-data.json
exercises/ocr-numbers/canonical-data.json
exercises/pascals-triangle/canonical-data.json
exercises/phone-number/canonical-data.json
exercises/prime-factors/canonical-data.json
exercises/protein-translation/canonical-data.json
exercises/rotational-cipher/canonical-data.json
exercises/secret-handshake/canonical-data.json
exercises/trinary/canonical-data.json

The canonical data for `isogram` and `prime-factors` contain nesting, but as there is only one level of nesting, this does not add any value.﻿
This can break test generators, but as everything is still in flux anyway, I think this is a good time to do this.
Note: please don't squash merge to retain the individual commits

Remove unneeded nesting

---

README.md

The current documentation for `tests.toml` files was still referring to the obsolete canonical data syncer. This PR updates the documentation to use configlet's `sync` command instead. It also updates the contents of the example `tests.toml` file to the latest spec.
Closes https://github.com/exercism/configlet/issues/124

Update sync documentation

---

exercises/sgf-parsing/description.md

We were adding this exercise to Elixir (finally) and we noticed that the description is a bit... mean? condescending? I'm not sure if this comment is necessary for the understanding of the exercise. If it is, I guess it could be said a bit nice: "which is not an optimal place to play"?

Remove mean comment from sgf-parsing description

---

exercises/pythagorean-triplet/description.md

`**` is not commonly used for exponentiation. I went with `²` but `^` would also be a more common choice than `**`. In v3, this should probably be updated to use Mathjax/KaTeX notation instead. (see https://github.com/exercism/website/issues/476)

pythagorean-triplets: Fix maths notation in instructions

---

exercises/grade-school/canonical-data.json

Fixes #1763, see the discussion there for explanation

grade-school: fix student cannot be in multiple grades logic

---

exercises/markdown/canonical-data.json

As discussed in issue #1812, markdown exercise would benefit with more
extensive tests to ensure learners write dynamic code, capable of
handling all header depths there is.
To ensure their code is not too dynamic, I added the h7 level. It does
not exist in the HTML specification and therefore should be equal to the
input.
Resolves #1812.

exercises/markdown: add extensive header parsing tests

---

exercises/two-fer/metadata.toml
exercises/two-fer/metadata.yml

Because it would be possible otherwise to generate title "Two Fer" by automatic exercise generator. Proper title punctuation is taken from description.md.

Two-fer: add title to metadata

---

exercises/raindrops/description.md

I saw this little error while doing the exercise. I am hoping this reads a bit easier!
Going from:
`The simplest way to test if a one number is a factor of another is`
to 
`The simplest way to test if one number is a factor of another is`

fix typo for bash raindrops exercise

---

exercises/luhn/canonical-data.json

A new positive test case with odd number of digits and non-zero first digit.
I have seen a solution in Golang which passes all the tests for Luhn containing odd number of digits and never reads the first digit.
It happens because in all such cases the first digit is zero . This test case will fix the problem.

Luhn: A new test case with odd number of digits

---

exercises/affine-cipher/description.md

Hi, I have tried to clean up the instructions to this exercise a bit and possibly make them a bit more informative by:
* Changing the markdown text from plain to `code` for important values to let them stand out
* Adding the Encryption and Decryption section headers for improved clarity
* Adding guidance about digits and spaces as inputs to match the test cases
* Updating the Decryption formula to avoid exponent ambiguity
* Updated the MMI property formula to be more consistent with the resource (Wiki), and subjectively easier to grasp
* Adding a hint about what coprimes (or relative primes) are for improved clarity
* Removing one example of MMI which seemed to be redundant
Please review the proposed updates and let me know what you think - they are subjective so it's perfectly fine if …

affine-cipher: Updates to the exercise instructions file

---

exercises/grade-school/canonical-data.json
exercises/grade-school/description.md

Example implementation here: https://github.com/exercism/c/pull/683
Fixes #1824
Wasn't sure how to replace the existing `grade-school` exercise so have just used `grade-school2` (should this be `grade-school-2`?) as had been suggested in slack (https://exercism-team.slack.com/archives/CARRG4MNC/p1628017550027100?thread_ts=1627502454.403900&cid=CARRG4MNC)
If accepted the intention is that the existing `grade-school` should be deprecated as the spec is too problematic. 
I can add that as part of this PR if there is an agreed method?

Fix grade-school

---

exercises/resistor-color-duo/canonical-data.json

With "black" as first band.
Perhaps instructions should also be updated, as not every output is two-digit?

Resistor-color-duo: one-digit solution

---

exercises/grep/description.md

Notice that our [canonical-data.json](https://github.com/exercism/problem-specifications/blob/main/exercises/grep/canonical-data.json) already has tests matching this
requirement, as it is part of the Unix `grep`'s behaviour; this is
simply documenting the existing requirement.
This was mentioned in
https://github.com/exercism/problem-specifications/issues/1873, though
it is not the main thrust of that issue, so this doesn't close that
issue.
I do not want to make a habit of splitting up two PRs to the same exercise (this and #1876) so granularly and using more of reviewers' valuable time in doing so, but my specific reason for that here is that the two changes are actually quite independent of one another and I actually believe one of them will need far more revision than the other, and …

grep: Specify prefix with multiple files

---

exercises/grep/description.md

The type implied by "single string" is not part of the essence of this
problem. Some tracks wish to ask for an ordered collection of lines,
rather than a single string containing the lines, and it seems that
there is no reason for the specification to forbid this.
The specific word "output" could also be misunderstood to mean "print on
standard output", though we're not yet currently aware of any track
tests that do indeed require this.
Closes https://github.com/exercism/problem-specifications/issues/1873

grep: remove mentions of "output" and "single string"

---

README.md

For context, watch the weekly call from today.

Add reviewing info

---

exercises/yacht/description.md

This was the only `description.md` file that did not begin with
`# Description`.
---
@ErikSchierboom do we want this change? 
PR #1782 added `# Description` to the `description.md` of every exercise in `problem-specifications` apart from `yacht`, which already had a top-level header.
On `main`:
```
$ cd problem-specifications/exercises
$ find -name 'description.md' | wc -l
135
$ rg --glob 'description.md' '# Description' --files-with-matches | wc -l
134
$ rg --glob 'description.md' '# Description' --files-without-match
yacht/description.md
```

yacht: Make top-level header consistent

---

exercises/zipper/canonical-data.json

This PR adds a case to the Zipper canonical data. The new case checks whether the zipper implementation can find its way back to the top node from deep within the tree.
Resolves #1872

Add left, right, up, up case to zipper canon

---

exercises/roman-numerals/canonical-data.json

1 (I) and 6 (VI) are already in the tests.
These seems useful to have if/when people tackle the problem one symbol at a time.

roman-numerals: Add test cases with exactly one occurence of all symbols in decreasing order

---

exercises/flatten-array/canonical-data.json

JavaScript has these additional tests that do two things:
- provide better stepping stones (TDD)
- test null values are not handled differently when there is nothing to flatten

flatten-array: add intermediate TDD-supporting tests

---

exercises/scale-generator/canonical-data.json
exercises/scale-generator/description.md

The problem has been explained in
https://github.com/exercism/problem-specifications/issues/1640:
All previous cases only required N notes from N intervals, but that
meant the last interval was completely ignored.
That causes confusion (what is the last interval there for?).
To fix this, all tests with the `interval` property have to be
reimplemented.
The `tonic` and `intervals` inputs are the same as the original.
The `expected` is the same as the original, except with an additional
last note indicated by the last interval, which was previously
ignored.
In conjunction with https://github.com/exercism/problem-specifications/pull/1884,
closes https://github.com/exercism/problem-specifications/issues/1640

scale-generator: Require N+1 notes from N intervals

---

exercises/matching-brackets/canonical-data.json

These are up-streamed test cases from exercism/rust#946 to catch bugs discovered in this https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1661c960aaf13f061dbeb747a587cece matching-brackets rust implementation that where not caught with the preexisting testcases.
As explained in the [other pull request](https://github.com/exercism/rust/pull/946) these test cases handle bugs related to implementations not quitting when there is a error in situations such as isolated mismatched brackets or closing brackets when the stack is empty.

Add testcases to matching-brackets

---

exercises/collatz-conjecture/canonical-data.json

The Collatz Conjecture holds only for positive integers. Whilst for strongly-typed languages such as Rust, the compiler ensures that the input must be an integer, for dynamically-typed languages (e.g. Python) or languages in which there is no integer type (e.g. TypeScript), the input must be explicitly tested. This commit adds a test case for a positive non-integer and modifies the expected error message from 'Only positive numbers are allowed' to 'Only positive integers are allowed' so that the student can test the input using a single if statement.

Collatz Conjecture: test for non-integers

---

CONTRIBUTING.md

I am providing these changes to make it easier for a new contributor (like me) to find necessary information.
I have questions about 3 links in this file:
1. **"The Website" in the top section:** The Contributing guide doesn't exist, and the repo (https://github.com/exercism/website) is not accepting contributions. I linked to the README in case the website opens up in the future. Was that the right choice?
2. **"The Exercises API" in the top section:** I found a link that resolves, but is the API not a thing? Should I remove this line?
3. **"Test Data Versioning":** There is text in `CONTRIBUTING.md` that is not on https://github.com/exercism/problem-specifications/blob/main/CONTRIBUTING.md about test data versioning. It looks like that section is also in `README.md`, but not on …

Fix links in CONTRIBUTING.md.

---

exercises/atbash-cipher/description.md

In the canonical-data.json, there are some test cases with numbers.
However, it is not clearly described how to deal with them in the description.md content.
So I made some changes for it. Hopefully it could help to refine the description.

Atbash Cipher: Refine the exercise description

---

exercises/isbn-verifier/canonical-data.json

Add a test case to cover the scenario where an invalid character is
nested inside an otherwise valid ISBN.
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

isbn-verifier: Enhance invalid characters test

---

exercises/isbn-verifier/canonical-data.json

One (3132P34035) tests what happens if the invalid character is ignored
after checking length, the other (3598P215088) tests what happens if the
invalid character is ignored before checking length.
These are two different incorrect implementations, and they get the
correct answer on the other tests. So only including one of the two
would fail to reject the other, and tracks would lose coverage.
Therefore, my recommendation is that tracks include both tests.
I have delivered the full recommendation in
https://github.com/exercism/problem-specifications/pull/1898#issuecomment-1002061905
Instead of having one reimplement the other, distinguish the two by
description.

isbn-verifier: Distinguish two different invalid character tests

---

exercises/queen-attack/canonical-data.json

This is an extra test case for the queen attack exercise. It catches an issue with an erroneous diagonal check that the existing tests do not catch.
The PR I submitted to the Rust track was already merged (https://github.com/exercism/rust/pull/1398). The maintainer suggested I should add this test case here as well.
This is my first PR to this particular project, and my second PR on Github ever, so I appreciate constructive feedback on how to improve.
I started with a condition of
```rust
self.row + self.column == other.row + other.column
```
for the `/` diagonal check, and
```rust
self.row - self.column == other.row - other.column
```
for the `\` diagonal check.
The latter obviously fails when column > row [edit: because I chose unsigned integers as row and column, and Rust will panic on …

queen-attack: Add test case to catch an incomplete diagonal check

---

exercises/forth/canonical-data.json

Originally a part of
https://github.com/exercism/problem-specifications/pull/1742
---
My commentary: I'm ambivalent about this change, but if automated formatting does this, then that seems fine to keep it.

forth: format: expected errors on their own line

---

exercises/rational-numbers/canonical-data.json

Fixes #1909 .  Any feedback welcome!
Note I have not ran the schema check.  Relying on CI.

`rational-numbers` Add additional test cases

---

exercises/affine-cipher/description.md

Markdown guidelines applied
- Affine description: One sentence per line
- Reference style links for Affine

Affine markdown style guide applied

---

exercises/largest-series-product/description.md

Closes https://github.com/exercism/problem-specifications/issues/1910
We established the tests for window size 0 via
https://github.com/exercism/problem-specifications/pull/170
Window size 0 has caused questions in the past, including but not
limited to:
* https://github.com/exercism/problem-specifications/issues/1638
* https://github.com/exercism/go/issues/349
We have comments on the test cases, but it's not necessarily the case
that everyone will see those comments.
Let's try adding the reasoning to the description.

largest-series-product: Describe window size 0

---

exercises/accumulate/canonical-data.json

Fix(accumulate): remove extra `)` in `canonical-data.json`

---

README.md

The templates have been moved to the docs a while ago in #1792.

Remove mention of workflows from README

---

STYLE-GUIDE.md

The style guide "redirect" link seems to be broken. Linked to what I assume is the correct file in the docs repo
Old link: https://github.com/exercism/docs/blob/main/contributing/standards/style-guide.md
New link: https://github.com/exercism/docs/blob/main/building/markdown/style-guide.md

Docs(style-guide): Fix broken link to style-guide.md

---

exercises/anagram/description.md

closes #1556, affects exercism/rust#86, exercism/rust#690

updated description of anagrams exercise

---

exercises/rational-numbers/canonical-data.json

According to the issue exercism/elixir#1052

rational-numbers: additional test for abs value

---

exercises/word-search/canonical-data.json

The author of this commit thinks that concatenation is highly unlikely,
but the wrapping might be useful to check in languages that allow
negative indices.

word-search: Add cases checking for concatenation and wrapping

---

.github/workflows/action-format.yml

Depends on https://github.com/exercism/problem-specifications/pull/1917 to be merged
This is almost a carbon copy of the [workflow that the JavaScript track uses](https://github.com/exercism/javascript/blob/main/.github/workflows/action-format.yml).
@iHiD This repo now needs access to the SSH deploy key, like the `javascript` track.

Add action to format code

---

exercises/rational-numbers/description.md

The current instructions fail to mention that a reduced rational number should always be rendered in standard form (without any negative value at the denominator).

Reduced rational nr. should be in standard form.

---

exercises/scale-generator/description.md

This PR switches hash symbols (`#`) to the sharp symbols (`♯`) and use of `b` to the flat symbol (`♭`) in the `description.md`.
This seems more "musically" accurate, or more domain-correct.
On the other hand, it causes a divergence between the `description.md` and the `canonical-data.json`.
I thought about updating the `canonical-data.json` also, but that may cause issues for any language for which UTF-8 is non-trivial.
What do you think?

scale-generator: use flat and sharp symbols

---

README.md

Second part of https://github.com/exercism/docs/issues/264
The configlet section in the README did not fit with the latest configlet release anymore. Configlet can now update more files and the command changed a bit. I tried to adapt the README accordingly and added a link to the full documentation.
I didn't do a general overhaul here, I mainly changed it so it fits the new configlet release.
cc @ee7

Update configlet part in README

---

exercises/phone-number/canonical-data.json

Because the area code is not allowed to start with 0 or 1, inputs designed to elicit other errors should not use area codes that start with either of those digits.

phone number: only one problem per test input

---

exercises/bank-account/description.md

These additional notes are, while useful in general, not something we should be adding to a single exercise. For that a track can used its shared files.

bank-account: remove additional notes

---

.github/workflows/ci.yml
bin/check_key_order.rb
exercises/accumulate/canonical-data.json
exercises/anagram/canonical-data.json
exercises/book-store/canonical-data.json
exercises/collatz-conjecture/canonical-data.json
exercises/darts/canonical-data.json
exercises/diffie-hellman/canonical-data.json
exercises/grade-school/canonical-data.json
exercises/hamming/canonical-data.json
exercises/high-scores/canonical-data.json
exercises/largest-series-product/canonical-data.json
exercises/list-ops/canonical-data.json
exercises/luhn/canonical-data.json
exercises/phone-number/canonical-data.json
exercises/saddle-points/canonical-data.json
exercises/scale-generator/canonical-data.json
exercises/triangle/canonical-data.json

This PR makes the order of the keys in the `canonical-data.json` files consistent and adds a CI check to verify its order.
This is just a minor improvement, so if people are not convinced this is useful, I'm happy to not go through with this.
See https://github.com/ErikSchierboom/problem-specifications/runs/5158116886?check_suite_focus=true for an example of the output.
Closes https://github.com/exercism/problem-specifications/issues/1705

Reorder keys

---

exercises/allergies/canonical-data.json

Added test case. As mentioned in instructions(https://github.com/karstenj/problem-specifications/blob/main/exercises/allergies/description.md) the program shall only report the eggs (1) allergy for a given score of 257. This case is currently not fully covered by the existing test cases.

Exercise allergies test case

---

exercises/go-counting/canonical-data.json
exercises/ocr-numbers/canonical-data.json
exercises/saddle-points/canonical-data.json
exercises/scale-generator/canonical-data.json

this commit was made by having prettier format these files and
committing portions of the changes.
For now we want prettier to continue to ignore these files, but
eventually the plan would be to use prettier but to reformat specific
portions.
The portions in this commit are *not* the portions we would want to
reformat, so for these specific portions we are satisfied to accept
prettier's changes.

auto-format portions of some JSON files

---

exercises/allergies/canonical-data.json

race condition between
"Exercise allergies test case"
https://github.com/exercism/problem-specifications/pull/1969
and
"allow prettier to format more files"
https://github.com/exercism/problem-specifications/pull/1966
Since this file is now being formatted by prettier, the test case added
in the latter PR must be formatted according to prettier.
Otherwise, as will be observable from any PR after
https://github.com/exercism/problem-specifications/pull/1966, CI fails
on main.
There are alternate approaches, such as directing format-array to always
format `expected` with one item on each line, but it doesn't seem like
this is particular important for the `allergies` exercise.

allergies: format

---

exercises/word-count/canonical-data.json

As per [issue 1977](https://github.com/exercism/problem-specifications/issues/1977), if the user's code was unable to correctly handle words with multiple letters after an apostrophe, e.g. "they've" (a plausible error one might make with a regex, for example), the previous version of the "with apostrophes" test, which only included the word "don't", would not detect the bug (and none of the other tests would detect it, either).
This change is a reimplement of the "with apostrophes" test to now include the word "you're" as part of the input, so if the user's code has a bug and incorrectly handles such words, the new version of the test will fail appropriately, and expose it.

Add reimplement of "with apostrophes" test

---

exercises/pangram/description.md

This makes it easier for tracks to add additional test cases that aren't ascii without having to deal with manually syncing the instructions.
I think this is in line with the vast majority of exercises where the inputs aren't described in too much detail.

pangram: remove overly specific description

---

exercises/isbn-verifier/description.md

This PR is based on the discussion of [this issue.](https://github.com/exercism/problem-specifications/issues/1975)
When using the default code blocks with the text language, the subscript characters are removed. I switched them to block quotes to preserve the subscripts and everything looks good because it is only text anyways. Let me know if this violates a standard somewhere

updated the ISBN description for additonal clarity

---

exercises/yacht/canonical-data.json

The current tests for "fives" only include a negative test where the score is 0. This PR adds a test for fives that has a score.

Add test to Yacht to ensure fives are handled

---

bin/format-array.rb
exercises/state-of-tic-tac-toe/canonical-data.json
exercises/state-of-tic-tac-toe/description.md
exercises/state-of-tic-tac-toe/metadata.toml

This is based on the research exercise julia-1-a
Extensions of this might be possible in the future, hence tic-tac-toe may not be ideal as a slug, so I'm going with state-of-tic-tac-toe.

Add exercise: state-of-tic-tac-toe

---

exercises/poker/canonical-data.json

Ensures ranking based on adding pair values with equal
weight does not erroneously rank different two-pair
hands as equivalent.
Found an exemplar implementation that ranks two pair hands by summing the two face values. This test case will mean an update to the exemplar is needed in order to be correct.

Add new test case for Poker

---

exercises/anagram/canonical-data.json

Short version:
The focal question of this commit:
**Should determining set membership be case-insensitive?**
If yes, this commit makes it so.
If no, this commit should be rejected.
Long version:
In https://github.com/exercism/problem-specifications/pull/1928 it was
codified that the input `candidates` is a set of words. Recall that a
set contains no duplicates.
Recall that ever since July 2013, it has been the intent of this
exercise that determining whether two words are anagram of each other
should be case-insensitive:
https://github.com/exercism/exercism/commit/bf3e0117c584b0b2b8b2af655986ac1678b98185
Recall that ever since January 2014, it has also been the intent that
determining whether a word is an anagram of itself should be
case-insensitive: …

anagram: reimplement cases where `candidates` isn't a set

---

exercises/book-store/canonical-data.json

Some numbers were in their digital form, rather than in word form.  All are words now. (i.e. "four" instead of "4", etc.)

[book-store] Made test descriptions consistent

---

.appends/.github/labels.yml

Dependabot labels its PRs with the ecosystem, which is quite useful to see at a glance which workflows are affected by a PR.
Currently, the label sync removes them after a while.
Examples:
- https://github.com/exercism/problem-specifications/pull/2008
- https://github.com/exercism/problem-specifications/pull/1995

Add Dependabot ecosystem labels

---

exercises/state-of-tic-tac-toe/canonical-data.json

In the last test, the board is
```
XXX
OOO
```
and it's clear that `X` won and `O` kept playing, but for this board:
```
XXX
OOO
XOX
```
it's impossible to determine who won "first". 
And really, it doesn't matter who won, what matters is that this is an impossible board because the players kept going after the game was won, so I'm proposing to tweak the error message to reflect that and add one more test case to justify the change.
Credits to @angelikatyborska for finding this incompleteness issue.

`state-of-tic-tac-toe`: tweak error nessage and add test case

---

exercises/isbn-verifier/canonical-data.json

Adds an `isValid` test that catches incorrect programs which treat an invalid last character as zero.
Note that there is an existing test addressing invalid last characters, but that test does not catch programs which treat such characters as zero. This is because the resulting checksum will not be divisible by 11 and hence those programs will return `false` which is the expected value.  In the new test case, the resulting checksum would be divisible by 11, hence such programs will return `true` and thus fail this test.

isbn-verifier - add  isValid test

---

exercises/state-of-tic-tac-toe/canonical-data.json

Follow-up to #2012.
It was fairly easy to come up with natural descriptions, except for the draws, so I used numbers for those two cases.

`state-of-tic-tac-toe`: unique descriptions for test cases

---

exercises/state-of-tic-tac-toe/canonical-data.json

The test case has been won by X yet there are the same number of X's and O's.
This fixes this issue: https://github.com/exercism/elixir/issues/1127

One of the test cases has too many O's

---

exercises/rectangles/canonical-data.json

Some solutions to this exercise will look for the top corners of the rectangles, making sure they are connected by a horizontal line, then go on to walk down the left and right side to find corners at the same row, in which case a rectangle is detected. These solutions sometimes fail to check that the bottom two corners are connected by a horizontal line. This test case will catch that.

rectangles: Add test for missing sides

---

exercises/state-of-tic-tac-toe/canonical-data.json

Fixes #2069.
Set the 'reimplements' key for the reimplemented test to the uuid of the previous version of the test.

Exercise state-of-tic-tac-toe: set proper value for 'reimplements' key of reimplemented test case

---

exercises/atbash-cipher/description.md

The test suite expects uppercase letters to be encoded as lowercase. Neither the instructions nor the examples address this.

Atbash Cipher: Clarify expectation for uppercase letters

---

exercises/complex-numbers/canonical-data.json

I have noticed solutions with the wrong scaling for the imaginary part of the exponential of a complex number (including in the example implementation of the Elixir track by yours truly) which went unnoticed because we only have tests with purely real results, so I would like to add this case.

Add test case for `complex-number`: exponential resulting in a number with real and imaginary part

---

exercises/triangle/canonical-data.json

To solve a bug discussed in #2072, I have made this PR. 
In short, I added a new test case to the scalene triangle part of the test cases with the name "two unadjacent sides are equal" of [3, 4, 3], while still keeping the existing "two sides are equal" test case albeit renamed.

triangle: Add new test case for scalene triangles to solve a bug [#2072]

---

exercises/word-count/description.md

With "ignored", it's unclear if punctuation separates the words or is just removed (relevant for the test case [handles cramped lists](https://github.com/exercism/problem-specifications/blob/16f11cec666076eb1f6f8f4c1fd2fc4d0852dbd6/exercises/word-count/canonical-data.json#L49)).

word-count: Less ambiguous punctuation rule

---

exercises/roman-numerals/canonical-data.json
exercises/roman-numerals/description.md

Adjust Instructions and Unit Tests to support maximum Roman numeral 3999
Issue https://github.com/exercism/go/issues/2475
Adjustment to problem specification, instructions, and unit tests to support the max val 3,999 which can be expressed in Roman numerals (without getting into the "Larger number" scenarios)

issue_2475_roman_numerals_max_3999

---

exercises/meetup/description.md

Back in 2015 we determined that we should not implement fifth, since this exercise is about scheduling regular monthly meetups.
Since not all months have a fifth week, it doesn't make sense to schedule a regular meetup on the fifth Wednesday (or whatever) of every month.
We removed the test cases, but the description was not updated to remove the reference to the 'fifth' scenario.

Fix outdated description for Meetup exercise

---

exercises/matching-brackets/canonical-data.json

Current input value for `paired and wrong nested brackets` (a0205e34-c2ac-49e6-a88a-899508d7d68e) allows for solutions where only the last opened bracket is being traced.
Current input value is `[({*]*})`.
Proposed input value is `[({}*]*)`.
<sub>"*" Used only to highlight the change.<sub>
By wrongly closing the second to last opened bracket (instead of the last one), we best cover wrongly nested brackets, because we ensure users realize they need to track all opened brackets.
I understand the most straighfoward and simple solution is to stack opened brackets and remove then when they're closed, but it's possible to green all tests by tracing brackets count and last opened bracket.
The next code is an example in ruby. It fails if the proposed input is used, but passes with the current …

matching brackets: reimplements wrong nested bracket tests

---

exercises/pythagorean-triplet/description.md

prior instruction was not clear what it actually meant at first glace, the "+ 16 = 25 = " is extraneous information. It makes it feel like there is a missing piece beyond the actual meaning of 3^2 + 4^2 = 5^2

[pythagorean-triplets] improved instruction clarity

---

exercises/sgf-parsing/canonical-data.json

11c36323-93fc-495d-bb23-c88ee5844b8c crams too much into one test case.
Split it up into multiple ones.
In addition, 11c36323-93fc-495d-bb23-c88ee5844b8c has behaviour that
violates the specification. The violation is that `\t` and `\n` (written
as `"\\t"` and `"\\n"` in the JSON string, respectively), do not hold
any sort of special significance in SGF, according to the specification:
https://www.red-bean.com/sgf/sgf4.html
Reimplement in 08e4b8ba-bb07-4431-a3d9-b1f4cdea6dab.
The reimplemented case is mostly as it was when the exercise was
originally implemented in
https://github.com/exercism/exercism/commit/7a5075bf96e2cafb29f2f883ff98b708be5594a6
and the reimplemented case is in accordance with the specification.
Note that the original case also got it wrong in that newlines should …

sgf-parsing: Add individual tests of escaping/whitespace behaviour

---

exercises/beer-song/description.md
exercises/bottle-song/description.md
exercises/grade-school/description.md
exercises/grains/description.md
exercises/isbn-verifier/description.md
exercises/triangle/description.md
exercises/wordy/description.md

The bonus points sections were a way of encouraging more discussion and exploration in v1.
Discussion:
Now that we have closed mentoring rather than open discussions it makes less sense to encourage discussion in this way. We may find other ways of encouraging discussions, but then it will be a product-level design choice rather than a textual call to action from within the exercise description.
Exploration:
We tend to want people to explore the approach to solving the problem rather than to explore how to expand the scope of the problem. As such I think it's worth deleting the exploration aspect of the bonus points sections.
Also, there are only a handful of exercises that had this sort of section, so it's also neater in terms of consistency.

Delete bonus point sections from descriptions

---

exercises/word-count/canonical-data.json

While solving the exercise I noticed that there is no test that contains quotations around a word with apostrophes, eg 'can't'.
Some naive implementations for quotation filtering might not be able to filter these quotations out correctly.
Let me know if I'm missing anything, happy to fix it :)

Word count: test with quotations for word with apostrophe

---

exercises/affine-cipher/description.md
exercises/alphametics/description.md
exercises/connect/description.md
exercises/darts/description.md
exercises/dnd-character/description.md
exercises/dot-dsl/description.md
exercises/forth/description.md
exercises/hangman/description.md
exercises/house/description.md
exercises/paasio/description.md
exercises/rest-api/description.md
exercises/sgf-parsing/description.md
exercises/simple-cipher/description.md
exercises/yacht/description.md
exercises/zipper/description.md

Use only lowercase ASCII letters and hyphens in markdown reference links.
In #2113 @wolf99 questioned the use of the "empty" reference links (example below) and wondered whether we should standardize on using `lower-case-keys` for references.
```
Something about [Alphametics][].
[Alphametics]: https://example.com/alphametics
```
I like the suggestion, so I have changed reference links that do not have this format.

Normalize reference links

---

exercises/sgf-parsing/description.md

The test case added in 3c33c249121c16aa2a7fc3398a50349d8985f752 had to be very careful to specify the difference between the two. Add it to the description as well.

sgf-parsing: Add warning about string literals

---

exercises/dot-dsl/description.md
exercises/roman-numerals/description.md

In #2118 we normalized the descriptions to follow the one sentence per line directive in the Exercism
Markdown Specification.
I missed a couple of spots and this fixes those.

Fix an accidental split line in exercise description

---

exercises/poker/canonical-data.json

Additional tests for straights with the same tests also for straight flushes. (Originally proposed in the Rust track: https://github.com/exercism/rust/pull/1555)

Additional tests for straights

---

exercises/two-bucket/metadata.toml

Follow-up from https://github.com/exercism/problem-specifications/pull/2122#discussion_r992007032

two-bucket: metadata: make title singular

---

exercises/dominoes/canonical-data.json

I believe this was a misprint. A graph that contains such a cycle is called Eulerian. See: https://mathworld.wolfram.com/EulerianGraph.html

dominoes: Fix reference to Eulerian graph in comment

---

SCENARIOS.txt
canonical-data.schema.json
exercises/gigasecond/canonical-data.json

The gigasecond test suite is a bit odd in that there are two different types for the same input.
Another oddity of the gigasecond test suite is that most of the tests don't actually add any value. If you get one passing, you get them all passing.
This adds a date scenario to the inputs that have only a date, and datetime to the ones that also include a time element.
Am I missing anything important here?

Add date and datetime scenarios to gigasecond

---

exercises/crypto-square/canonical-data.json

There is no test case for plaintext made up of just spaces and punctuation.
Mentored someone with code that pass all tests, but have a bug in this case, so wanted to add this.
This is my fires PR for exercism, hope I'm going it OK.
Closes #2130

Crypto Square: adding test for empty text after normalized

---

exercises/two-fer/metadata.toml

There was a whole discussion about whether this should be Two-fer, Two Fer, or Two-Fer.
Without the hyphenation the implication is that `fer` is a word, which it is not. And if it were a word, then we could have a whole discussion around whether or not it should be pluralized, because (clearly) there are two of them.
According to Google Ngram, `two-fer` is more common than `two fer`.
So that left us with the choice between Two-fer and Two-Fer.
The Chicago style guide suggests:
> In hyphenated compounds, capitalize the first element and
> subsequent words that are not articles, prepositions,
> coordinating conjunctions, or modifiers following musical
> key symbols (e.g., “Symphony in F-sharp Major”); however
> do not capitalize the second word if the first element is
> a prefix that could …

Change name of two-fer to Two-Fer

---

exercises/tournament/description.md

There was a new test added in #1802 that enforced the behavior of the ordering. A downstream maintainer pointed out that when there is a test enforcing behavior, then the instructions ~should~ must read *must* rather than *should*.

Change wording in tournament instructions

---

.markdownlint.jsonc
exercises/allergies/description.md
exercises/bowling/description.md
exercises/darts/description.md
exercises/diamond/description.md
exercises/dnd-character/description.md
exercises/linked-list/description.md
exercises/list-ops/description.md
exercises/micro-blog/description.md
exercises/resistor-color-duo/description.md
exercises/rna-transcription/description.md
exercises/wordy/description.md

We've had some churn due to not having documented our
preference.
This is now documented in
https://github.com/exercism/docs/pull/399

Use hyphens for bulleted lists

---

exercises/nth-prime/metadata.toml

The nth-prime exercise is inspired by problem 7 at Euler, not Problem 8. This got messed up in the http-to-https conversion in #2137.

Fix incorrect source url for nth-prime

---

SCENARIOS.txt
canonical-data.schema.json
exercises/diffie-hellman/canonical-data.json
exercises/dnd-character/canonical-data.json
exercises/simple-cipher/canonical-data.json

This PR adds the `random` scenario to identifying test cases that deal with randomness.
- scenarios: add 'random' scenario
- dnd-character: add 'random' scenario
- diffie-hellman: add 'random' scenario
- simple-cipher: add 'random' scenario

Add `random` scenario

---

exercises/meetup/description.md

There has been a lot of confusion around this exercise, especially
for people who don't speak English as their native language.
This attempts to explain very clearly where 'teenth' comes from,
and how it pertains to recurring monthly meetup schedules.
In doing this I have also made an executive decision to _not_
change the structure of the inputs (see #1069).
This is because I don't believe that adding string parsing to
get the pieces of the general description makes this exercise
more interesting or fun.
In order to keep the exercise focused on just the date munging,
this instead changes the description to match more closely how
the inputs are given.
Closes #1786.
Closes #1069.

Clarify description of meetup

---

exercises/say/description.md

The extensions described in the instructions
are not part of the spec.
Since we don't specify tests for these in the canonical-data.json
it makes more sense to delete the section.

Delete extensions in say

---

exercises/poker/metadata.toml

The original link started responding with a 404.
This was discovered by @resnickmicah, who submitted a PR
to fix this in the Rust track:
https://github.com/exercism/rust/pull/1591
I've given co-author credit to Micah here.

Fix broken link in poker metadata

---

.github/workflows/action-format.yml
.github/workflows/ci.yml
.github/workflows/rebase.yml

With CI it is good practice to pin your dependencies to a specific
version, as not doing could result in builds suddenly breaking when a
"latest" version is upgraded.

Use `ubuntu-22.04` instead of `ubuntu-latest` in GitHub Actions workflows.

---

.github/workflows/ci.yml

The `actions/setup-node` action has caching support built-in nowadays: https://github.com/actions/setup-node#caching-global-packages-data
This PR removes the custom yarn caching logic in favor of the built-in caching support.
See https://github.com/exercism/blog/pull/155 for an example where this is used.

ci: simplify yarn caching

---

exercises/phone-number/canonical-data.json

Within the North American Numbering Plan, a phone number may have 10 or 11 digits.
Currently, we have a test for a phone number with 9 digits (too few digits) and another test for a phone number with 12 digits (too many digits).
The error messages are inconsistent and somewhat confusing:
- (for the test with 9 digits): _incorrect number of digits_
- (for the test with 12 digits): _more than 11 digits_
In the first case, the error message is correctly explaining that something is wrong, but it doesn't give enough information to actually fix the problem. "incorrect number of digits". Too few? Too many? How many would be just right?
In the second case, it says that there are more than 11 digits, which is correct, but it doesn't actually say that this is a problem.
This PR changes the error …

phone-number: Use consistent error style for incorrect number of digits

---

exercises/resistor-color-trio/canonical-data.json
exercises/resistor-color-trio/description.md

[See here](https://forum.exercism.org/t/canonical-resistor-color-trio-testing-gap-values-over-1000-which-are-not-kiloohms/) for forum discussion

Resistor Color Trio: extend tests, borrowing from awk

---

exercises/palindrome-products/canonical-data.json

When I played around with palindrome-products I noticed an edge case where you could program in a particular way that would generate incorrect answers but there were no cases testing that.
To be more specific here is the solution that passes all tests for python:
```python
def smallest(min_factor, max_factor):
"""Given a range of numbers, find the smallest palindromes which
are products of two numbers within that range.
:param min_factor: int with a default value of 0
:param max_factor: int
:return: tuple of (palindrome, iterable).
Iterable should contain both factors of the palindrome in an arbitrary order.
"""
if min_factor > max_factor:
raise ValueError("min must be <= max")
result = 0
answer = []
for number_a in range(min_factor, max_factor+1):
for number_b in range(min_factor, …
```

[palindrome-products ]: Added test case which test edge case

---

exercises/roman-numerals/canonical-data.json

This reorders the cases in the roman-numerals exercise.
The old order was sort-of increasing, but with some cases
that were out of order, clumped at the end.
This makes the order consistent, sorting numerically by the
input value.
This does not affect tracks that have implemented the exercise.
It's purely a nice-to-have for tracks that are adding the exercise
through the use of a generator.
I used jq to visually verify the order:
cat exercises/roman-numerals/canonical-data.json \
| jq -r .cases[].description
Order before:
1 is I
2 is II
3 is III
4 is IV
5 is V
6 is VI
9 is IX
27 is XXVII
48 is XLVIII
49 is XLIX
59 is LIX
93 is XCIII
141 is CXLI
163 is CLXIII
402 is CDII
575 is DLXXV
911 is CMXI
1024 is MXXIV
3000 is MMM
16 is XVI
66 is LXVI
166 is CLXVI
666 is DCLXVI
1666 is MDCLXVI
3001 …

Reorder cases in roman-numerals canonical-data

---

bin/check_required_files_present

CI didn't yet account for the fact that an exercise could have an `instructions.md` file instead of a `description.md` file.
Better to fix this now than be bitten by it later :)

ci: support instructions.md file

---

exercises/gigasecond/description.md
exercises/gigasecond/instructions.md
exercises/gigasecond/introduction.md

Rework gigasecond documentation
This PR is part of our project of making our Practice Exercises more consistent and human. For more context please [see this forum thread](https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943)
We will merge this PR in roughly 72 hours, and then submit PRs to all tracks that have this exercise.
The main changes for this exercise are:
- Make it easier to understand
- Make it a bit more engaging.
- Provide more context around the idea of a gigasecond and why it is potentially interesting.
- Tone down the mathiness in an attempt to make it feel more casual, friendly, and approachable.

Rework gigasecond documentation

---

exercises/bowling/description.md

Hello!
This PR fixes a misleading description for the Bowling exercise. I didn't know the bowling rules and thought "a fill ball" means 1 fill ball.
I took the wording from @MatthijsBlom 's thread on the [forum](https://forum.exercism.org/t/clarifications-on-bowling/3050) (thank you, your thread helped me understand why my solution was wrong!)

Bowling: Clarify number of 10th frame fill balls

---

bin/check_required_files_present

there is no such variable alternate_filename. It needs to be alternative_filename instead.

check_required_files: Correctly display the name of the missing alt file

---

exercises/pangram/description.md
exercises/pangram/instructions.md
exercises/pangram/introduction.md

**This exercise is one of the focus exercises for this month's 12in23 challenge (Mechanical March).**
This PR is part of our project of making our Practice Exercises more consistent and human. For more context please [see this forum thread](https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943)
We aim to merge this PR in roughly 72 hours, and then submit PRs to all tracks that have this exercise.
The main change for this exercise is to provide a scenario that puts the exercise into a real-world context.

Rework pangram documentation

---

exercises/two-fer/instructions.md

I noticed that CI was unhappy in the javascript track when we synced this exercise.
This reformats the table so that next time we sync we don't undo the fix.
This is not a high-priority fix, so I won't be syncing it to all the tracks; it can come in as part of the next sync that brings in little fixes here and there.

Fix formatting in two-fer instructions

---

SCENARIOS.txt
canonical-data.schema.json

There are two open PRs that will have test cases intended to test a track's concurrency support:
- bank-account: https://github.com/exercism/problem-specifications/pull/2192/files
- parallel-letter-frequency: https://github.com/exercism/problem-specifications/pull/2209
I thought it might be a good idea to add a scenario for this type of test case, as some tracks won't support concurrent execution so they can safely skip them.
I'm open to any other naming suggestions.

scenarios: add `concurrent` scenario

---

.markdownlint.jsonc

Our style guide says that we want three backticks for code blocks, but to prefer (where possible) four tildes for special blocks like the exercism/caution block or exercism/note block.
The linter we use provides three options for linting:
- only backticks
- only tildes
- be consistent within a file
None of these options work for us, so we're turning off this linting rule.

Turn off markdown linting rule for code blocks

---

exercises/binary-search/instructions.md

This commit changes a potentially confusing reference to "number" and "numbers" to the generic "element" and "elements" to match the language used earlier in the description ("item" and "element"). It also specifies what should be done when "we're done" and revises the first step to avoid saying that the list should be divided.
I also use 4 tildes for the admonition to match the style guide or whatever as @SaschaMann commented about that.

Revise binary-search instructions

---

exercises/darts/canonical-data.json

From the [Exercism Style Guide][1]:
>This document acts as a Style Guide for the language and wording used in exercises.
>
>[...]
>
>All content should be written in US English, which differs from UK English in a variety of ways.
>In the future other translations may occur, but the "official" Exercism language is US English.
[1]: https://github.com/exercism/docs/blob/5828116bb6d4/building/markdown/style-guide.md#language
---
With this PR, there is no more `centre` in this repo:
```console
$ git rev-parse --short HEAD
8386de61
$ git grep centre || echo 'none'
none
```

darts: use US English in test description

---

exercises/strain/canonical-data.json

Following the discussion that happened in [this topic](https://forum.exercism.org/t/proposal-to-add-test-cases-to-the-strain-problem-spec/3961/8), this PR adds canonical data for the Strain exercise, using a list of test cases that have been implemented by the majority of the tracks.
Closes #588

Strain: Add canonical data

---

exercises/largest-series-product/description.md

This commit removes some mathematical jargon (multiplicative identity) and instead describes what should be returned.
The explanation of what the multiplicative identity is has been replaced with a short explanation (in an admonition block) of why the empty product (of numbers) is 1.

Remove ambiguity in explanation of empty product

---

exercises/largest-series-product/description.md

This PR changes the description to use double quotes instead of single quotes, which seems to be more common across languages.

largest-series-product: use double quotes for string

---

exercises/secret-handshake/instructions.md

The markdown processor seems to have choked on the link reference in the exercism note, presumably because it was missing a blank line between the main text and the reference definition.
See https://github.com/exercism/problem-specifications/pull/2219#discussion_r1143402812

Fix rendering issue in secret-handshake

---

exercises/pangram/instructions.md

Unfortunately #2215 introduced an ambiguity for some downstream implementations of this exercise that use non-ASCII inputs that shouldn't be considered part of the alphabet for the purpose of defining pangrams.
This PR is meant to clarify that only 'a':'z' are relevant to determine if a sentence is a pangram without restricting the inputs to those characters.
See also: https://github.com/exercism/julia/pull/614

pangram: Clarify instructions

---

exercises/rna-transcription/instructions.md
exercises/rna-transcription/introduction.md

This PR is part of our project of making our Practice Exercises more consistent and human. For more context please [see this forum thread](https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943)
We aim to merge this PR in roughly 72 hours, and then submit PRs to all tracks that have this exercise.
The main change is to frame the exercise within the context of a story.

Rework rna-transcription documentation

---

exercises/largest-series-product/instructions.md
exercises/largest-series-product/introduction.md

**This exercise is one of the focus exercises for 12in23.**
This PR is part of our project of making our Practice Exercises more consistent and human. For more context please [see this forum thread](https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943)
We aim to merge this PR in roughly 72 hours, and then submit PRs to all tracks that have this exercise.
The main change is to frame the exercise within the context of a story.
**NOTE:** I removed the bit about the empty product. Talking to Jeremy we concluded that we could simplify the description of this exercise immensely if we remove the one test case for the empty product, and we decided that this is a trade-off that we want to make.
Once this PR is merged, and the downstream …

Rework largest-series-product documentation

---

.github/workflows/ci.yml

Now that Dependabot will update these comments whenever the version is updated, we should put these in so that we humans (who cannot easily understand SHAs) can easily tell at a glance what version is being used, instead of having to figure it out from the SHA.
https://github.blog/changelog/2022-10-31-dependabot-now-updates-comments-in-github-actions-workflows-referencing-action-versions/

workflows/ci: Label all SHAs with their corresponding version

---

bin/check_required_files_present

After an initial implementation in https://github.com/exercism/problem-specifications/pull/2203, ensuing discussion in https://github.com/exercism/problem-specifications/pull/2211 tells us that in fact we only want to allow two possibilities:
1. legacy format: Only description.md exists
2. new format: Only instructions.md and introduction.md exist.
Previously, no check for introduction was present, so one has to be added.
If a an exercise has files that cause it to be a mix of the two formats, that shouldn't be allowed either.

check_required_files: Only allow legacy or new formats

---

bin/fetch-configlet

The fetch-configlet script in this repo was outdated. Update it to [the upstream version][1], which has many improvements.
Closes: #2258
[1]: https://github.com/exercism/configlet/blob/85745ac34f7c/scripts/fetch-configlet

bin/fetch-configlet: sync with upstream

---

exercises/sum-of-multiples/instructions.md

The docs diverged from the current state of the tests by including the upper limit

Revert changes to not include upper limit for sum-of-multiples

---

bin/check_required_files_present
bin/reorder-keys

* Prefer `[[` over `[`
* Expand tabs to 4 spaces
* Quote variables uniformly in `"${var}"` format
* Use `local` for function variables
* Prefer lowercase variable names for non-readonly variables
* Replace `let` with `$((`

Tidy shell scripts in ./bin

---

.github/workflows/ci.yml
.lycheeignore

Add link checking for markdown in CI

---

exercises/pig-latin/description.md

Context: https://forum.exercism.org/t/pig-latin-ch-in-chair-is-not-consonant-cluster/6285
> maybe try to use those confusing terms as little as possible until fully understand them. the fact that there are different definitions for consonant clusters and consonant digraphs on different websites further proves that there is no reason to continue using them.

Pig Latin: Remove use of "constant clusters"

---

exercises/killer-sudoku-helper/description.md

Hi there. We're moving various parts of our image hosting behind a CDN, and so various links to images are changing. This PR updates the urls we automatically found in this repository. If you come across any more links pointing to `exercism-v3-icons.s3.eu-west-2.amazonaws.com` or `dg8krxphbh767.cloudfront.net`, please change those to `assets.exercism.org` too. Thanks!

Use `assets.exercism.org` subdomain

---

exercises/resistor-color-trio/description.md

I think the intent here was to use the `resistor-color-duo` slug. Although I'm now wondering if this should just be replaced by the exercise name. Students would probably recognize Resistor Color Duo easier than `resistor-color-duo`.

Resistor Color Trio: Typo fix in description.md

---

exercises/darts/description.md

Depends on https://github.com/exercism/images/pull/17

[darts] Add scoreboard image

---

exercises/knapsack/description.md

The description of the knapsack problem has been updated quite a few times, resulting in two inconsistencies:
- The text references `wi` and `vi`, but they don't appear in the example input
- The example input uses JSON-esque formatting, but without linebreaks, rendering as
This PR simplifies the description, and puts the example input into a code block to preserve formatting.

Update knapsack description

---

exercises/accumulate/metadata.toml
exercises/binary-search-tree/metadata.toml
exercises/clock/metadata.toml
exercises/meetup/metadata.toml
exercises/strain/metadata.toml

Currently not logged in users are only allowed to see pages for single tweets. They are not allowed to see profile pages for example. I'm not allowed to access [https://twitter.com/jeg2](https://twitter.com/jeg2). And scripts aren't allow to access anything. `curl -I` on a valid tweet URL always returns 403. Thus Twitter is no longer appropriate to use as sources for anything.
Twitter links are also blocking https://github.com/exercism/problem-specifications/pull/2294
All the `http` instead of `https` are intentional - those are old websites that do not use SSL.

Remove or replace all Twitter links

---

exercises/anagram/canonical-data.json

The input for the anagram function is supposed to be a list containing single word strings, as in all other test cases. This test case has multiple words in the same string, separated by whitespace.

Change anagram test case input

---

exercises/custom-set/canonical-data.json

We should have a test case where a set is instantiated with a slice containing duplicate values.
motivated by:
https://github.com/exercism/rust/issues/1275

[custom-set] Add test for deduplication

---

exercises/phone-number/description.md

Context: https://forum.exercism.org/t/nanp-phone-numbers/7179/1
This shouldn't change any tests, so I think it's pretty safe to merge.

Phone number: Correct the format

---

exercises/pop-count/metadata.toml

Exercises should be named after their story, not their implementation details.
I'd also like to change the slug, but I'll leave that for another day.

Rename "Pop Count" to "Eluid's Eggs"

---

exercises/poker/canonical-data.json

Ensure that high cards are checked in the correct order (high ranking cards down to low ranking cards). Tests previously succeeded even when comparing lowest ranking spare cards first (e.g. "3H JS" beats "2C 5H" even when comparing "3H" vs. "2C").
Two tests added to ensure hands with pairs and triplets of the same rank are checked for high cards down to the last card.

Poker: Make high card tests more robust

---

exercises/pop-count/metadata.toml

#2335 changed `pop-count`'s title from Pop Count to Eliud's Eggs, but the config.json blurb spells it as Eluid. The introduction and exercise title uses Eliud.

Typo in Eluid's Eggs metadata blurb

---

exercises/scale-generator/.deprecated

We're deprecating the `scale-generator` exercise as it has been a source of confusion for many students.
Unfortunately, there is no clear path to improving this exercise, hence us deprecating the exercise.
See https://forum.exercism.org/t/scale-generator-tests/8236/1

Deprecate `scale-generator` exercise

---

exercises/dnd-character/canonical-data.json

This reimplements test case `2ca77b9b-c099-46c3-a02c-0d0f68ffa0fe` in the DnD Character exercise to verify that *every* ability is calculated only once, instead of only the `strength` ability.
This change was proposed in https://github.com/exercism/java/pull/2548 and it made sense to me to add it to the canonical data.

Reimplement test case in DnD Character

---

package.json
validate.js
yarn.lock

closes #2283
`ajv-cli` is unmaintained. It gets flagged with a security vulnerability and a [PR which would fix that](https://github.com/ajv-validator/ajv-cli/pull/227) has existed without response for close to a year.
The underlying library `ajv` seems to be less unmaintained. It had its last release about nine months ago.

Replace unmaintained ajv-cli with custom script

---

exercises/perfect-numbers/description.md

Thanks @MatthijsBlom 🌷
See : https://github.com/exercism/problem-specifications/pull/2318#discussion_r1318979534

[perfect-numbers] backticks on math and removed parens

---

exercises/anagram/canonical-data.json

forum post for discussion:
https://forum.exercism.org/t/more-unicode-tests-in-problem-specifications/9347

anagram: Add unicode tests

---

exercises/reverse-string/canonical-data.json

[forum post](https://forum.exercism.org/t/more-unicode-tests-in-problem-specifications/9347)

reverse-string: Add unicode tests

---

exercises/eliuds-eggs/canonical-data.json
exercises/eliuds-eggs/instructions.md
exercises/eliuds-eggs/introduction.md
exercises/eliuds-eggs/metadata.toml

The `pop-count` exercise should really have been named `eliuds-eggs`.
To help migrate to this new name in a non-breaking way, we're not renaming `pop-count` but instead have both of them temporarily.
Once all tracks have been updated (we'll do a bulk PR), we can remove the obsolete `pop-count` exercise.

Add `eliuds-eggs` exercise

---

exercises/alphametics/description.md
exercises/alphametics/metadata.toml
exercises/darts/description.md
exercises/darts/metadata.toml
exercises/flatten-array/description.md
exercises/go-counting/description.md
exercises/nucleotide-codons/description.md
exercises/nucleotide-codons/metadata.toml
exercises/parallel-letter-frequency/description.md

Some proposed wording changes to avoid use of "write a function"/"create a function".
PR for Issue #2396

Exercises no longer ask developers to 'write a function' (#2396)

---

exercises/protein-translation/canonical-data.json

The codon AAA maps to the amino acid lysine. While it is not listed in the exercise instructions, users should be free to implement the translation for all amino acids.
Since we cannot delete tests, this is done by making another test reimplement the incorrect one.
[Link to discussion on the forum](https://forum.exercism.org/t/incorrect-test-in-protein-translation/10616).

protein-translation: remove incorrect test

---

exercises/resistor-color-duo/description.md

A connection word is missing between these two independent clauses.

Grammar fix in resistor color duo instructions

---

exercises/killer-sudoku-helper/description.md

Noticed image alternative text not being "Single Sentence per Line" for proposed addition to TCL track.
Inspiration: exercism/tcl#267

Image alternate text: single sentence per line

---

exercises/bank-account/instructions.md
exercises/go-counting/description.md
exercises/nucleotide-codons/description.md
exercises/poker/description.md
exercises/yacht/metadata.toml

After looking at the Yacht exercise metadata,I noticed a few lowercase Wikipedia references so I fixed that. In the process, I also noticed bank-account had a grammatical issue.

wikipedia to Wikipedia

---

exercises/protein-translation/canonical-data.json

When `AUG` and `AUG` (also `UUA` and `AUG`) are combined, they contain a substring that potentially matches a STOP codon.  A naive implementation may falsely match the non-STOP sequence as a STOP codon.
This simple test covers a gap in the current suite.
```
AUGAUG
^^^ - not a STOP codon
UUAAUG
^^^ - not a STOP codon
```

fix: prevent matching STOP in a valid non-STOP sequence

---

exercises/zebra-puzzle/instructions.md
exercises/zebra-puzzle/introduction.md

From [the forum](http://forum.exercism.org/t/suggested-change-to-zebra-exercise/11847).

Banish the smokers from the zebra puzzle

---

exercises/luhn/description.md

[Luhn algorithm] Replace _ with arrows

[Luhn algorithm] Replace _ with arrows

---

exercises/forth/canonical-data.json

This will ensure that students are popping numbers off the correct end of the stack (for languages without a builtin Stack type).
From: http://forum.exercism.org/t/new-tests-for-forth-exercise-canonical-data/13045

Forth: additional tests for "combined arithmetic" category

---

exercises/hamming/metadata.toml

The metadata mentions 'Hamming difference', which doesn’t formally exist. It has been changed to 'Hamming distance' to ensure consistency across the exercise.

hamming: Change 'difference' to 'distance' in metadata

---

exercises/square-root/description.md
exercises/square-root/instructions.md
exercises/square-root/introduction.md

Moving generally applicable information from the Python specific addendum as per https://forum.exercism.org/t/moving-generic-instructions-from-python-addendum-to-overall-problem-specification/13678/1 and https://forum.exercism.org/t/square-root-exercise-instructions-could-be-clearer/13664/11
See also https://github.com/exercism/python/pull/3815/files

Update square-root description.md

---

exercises/bob/canonical-data.json

Using multiple sentences is a bit ambiguous in this exercise, in general. This is especially so, if we follow a sentence with a
question mark by a sentence with a dot.
To avoid that ambiguity gettting in the way of showcasing the intended way to handle multi-line queries, let this example use just one sentence, but let it spread over multiple lines.
Disucssion: https://forum.exercism.org/t/bob-exercise-text-should-mention-linebreak-handling/13582/17
@SleeplessByte

bob: Let multiple line question example be one sentence

---

exercises/protein-translation/canonical-data.json
exercises/protein-translation/description.md

Closes https://github.com/exercism/problem-specifications/issues/1639
Related [forum discussion](https://forum.exercism.org/t/protein-translation-wording-should-be-changed-in-the-exercise-description/13157)

Rename "proteins"->"amino acids" in protein-translation description table

---

exercises/complex-numbers/description.md

This pull request updates the description file for the **Complex Number** exercise, as discussed in the [forum thread](https://forum.exercism.org/t/guidance-needed-for-adding-new-test-cases-for-complex-number-exercise/13649/13). The changes reflect the updated description with no objections raised during the discussion.

Update the description for the complex-numbers exercise

---

exercises/grade-school/description.md

This PR follows [this discussion on the forum](https://forum.exercism.org/t/improve-grade-school-description/13694). A complete list of the changes and their rationale can be seen there.

Improve `grade-school` description

---

exercises/knapsack/instructions.md
exercises/knapsack/introduction.md

Reverts exercism/problem-specifications#2472
Sorry about all this!

Revert "Revert "Knapsack: Make Bob a Sherpa""

---

exercises/pig-latin/canonical-data.json

I’m seeing some solutions that do this:
* if word starts with a vowel or “xr” or “yt”, then return word + “ay” 
* else if word contains “qu” then ...
Those solutions will fail for a word like “liquid”
https://forum.exercism.org/t/new-qu-test-for-pig-latin/14052

New "qu" test for Pig Latin

---

exercises/dominoes/instructions.md
exercises/dominoes/introduction.md

Forum thread
https://forum.exercism.org/t/a-story-for-the-dominoes-exercise/14116

Add a story to the dominoes exercise

---

exercises/luhn/instructions.md
exercises/luhn/introduction.md

Forum thread
https://forum.exercism.org/t/a-story-for-the-lunh-exercise/14262

Add a story to the luhn exercise

---

exercises/grains/metadata.toml
exercises/leap/metadata.toml
exercises/say/metadata.toml

https://forum.exercism.org/t/substitute-broken-links-in-problem-specifications/14793/2
Seems Coderanch is blocking our link vetting script  so CI is failing.

Convert Coderanch links to Internet Archive links

---

exercises/sublist/canonical-data.json

See https://forum.exercism.org/t/broken-links-for-problem-specifications-ci/14902. This should make the link checker CI pass.

Update broken link for sublist exercise

---

exercises/affine-cipher/description.md

See http://forum.exercism.org/t/rotational-cipher-atbash-cipher-affine-cipher-the-english-alphabet-is-not-the-latin-roman-alphabet/15618/16.

Roman to Latin in `affine-cipher`

---

exercises/flatten-array/canonical-data.json
exercises/flatten-array/description.md

Forum
https://forum.exercism.org/t/flatten-array-mentions-both-lists-and-arrays/15849
Summary:
* Null-like values are optional according to the specifications; this has been clarified in the instructions.
* Added a clarification in the instructions that some tracks may contain data of different types.
* Replaced all references to lists with arrays in both the instructions and tests.
* Reimplemented tests that previously referred to lists in their descriptions; they now refer to arrays.
* Updated example in instructions with a more complex case.

flatten-array: Replace references to lists with arrays, and revise instructions

---

exercises/relative-distance/canonical-data.json
exercises/relative-distance/instructions.md
exercises/relative-distance/introduction.md
exercises/relative-distance/metadata.toml

This is an idea I proposed on [Discord ](https://discord.com/channels/854117591135027261/1344967617391231020/1344970101618905148) as a reaction to @ErikSchierboom's call for exercises.

feat: add pathfinding exercise

---

exercises/swift-scheduling/canonical-data.json
exercises/swift-scheduling/instructions.md
exercises/swift-scheduling/introduction.md
exercises/swift-scheduling/metadata.toml

This is a proposal to add new date-based exercise. The primary goal is to have more date-based exercises. This exercise requires students to convert strings to dates, and will need to add date arithmetic. I'm open to any improvements, so please consider this a starting point.
As a PoC, I've implemented it in C#: https://github.com/exercism/csharp/pull/2397

Add `swift-scheduling` exercise

---

exercises/saddle-points/instructions.md

Forum
https://forum.exercism.org/t/saddle-points-issue-with-grid-display/16044
Summary: Removed the text inside the code block to prevent issues with text wrapping and marked the saddle point differently. The explanation below the grid is already sufficient to clarify what is happening.

Fix grid display in saddle-points exercise

---

exercises/baffling-birthdays/canonical-data.json
exercises/baffling-birthdays/instructions.md
exercises/baffling-birthdays/introduction.md
exercises/baffling-birthdays/metadata.toml

This exercise combines two subjects that I feel we are still lacking exercises for:
1. Dates
2. Randomness
I've created a sample C# implementation for reference: https://github.com/exercism/csharp/pull/2402

Add `baffling-birthdays` exercise

---

exercises/largest-series-product/canonical-data.json

Discussed in https://forum.exercism.org/t/largest-series-product-span-can-be-equal-to-the-length-of-the-input/

largest-series-product: span must not exceed string length

---

exercises/eliuds-eggs/introduction.md

See https://forum.exercism.org/t/incorrect-base-10-value-in-eliuds-eggs-example-2/16007/2.

Correct displayed number in `eliuds-eggs`

---

exercises/phone-number/instructions.md

https://forum.exercism.org/t/phone-number-instructions-are-confusing/16865
In the introduction, we reference users submitting phone numbers that need to be cleaned up. However, in the instructions, user-entered reads like these numbers are coming from standard input, which would be a track-specific implementation detail. Removing this piece doesn't make the instructions less clear.

Update `phone-number` instructions

---

exercises/split-second-stopwatch/canonical-data.json
exercises/split-second-stopwatch/instructions.md
exercises/split-second-stopwatch/introduction.md
exercises/split-second-stopwatch/metadata.toml

This PR is intended as a starting point for a discussion on adding a new practice exercise.
The exercise's goal is to have students work with time, as well as deal with a sort of state machine.
The things I'd like to discuss are:
1. A nice background story
2. Ideas on how to best structure/formulate the instructions
3. Thoughts on how I've setup the canonical data (it's inspired by the canonical data of `circular-buffer`)
I've done a basic implementation of the exercise in C#: https://github.com/exercism/csharp/pull/2403

Add `split-second-stopwatch` exercise

---

exercises/crypto-square/canonical-data.json

54 character plaintext results in 8 chunks, not 7.
Discussed in https://forum.exercism.org/t/crypto-square-inaccurate-test-case-description/16878

Crypto Square: fix test case description

---

exercises/intergalactic-transmission/canonical-data.json
exercises/intergalactic-transmission/instructions.md
exercises/intergalactic-transmission/introduction.md
exercises/intergalactic-transmission/metadata.toml

This is  a proposal for a [parity bit exercise](http://forum.exercism.org/t/add-new-practice-exercises/16050/12).
I've created a proof of concept: https://github.com/exercism/csharp/pull/2398
Note, I wasn't quite sure how best to represent byte data in the JSON. I've used an array of strings with the hex values  as Visual Code was telling me "expected comma" if I didn't use the string.

Add intergalactic-transmission exercise

---

exercises/simple-cipher/description.md
exercises/simple-cipher/metadata.toml

See [forum discussion](https://forum.exercism.org/t/simple-cipher-change-proposal-rewrite-the-description/17380)
Key improvements:
* Remove mentions of "Steps" and "Extension".
* Replace "Caeser cipher" with "Vigenère cipher" to accurately match
what is being asked.
* Use a format in line with the other cipher exercises.

Rewrite the Simple Cipher description.

---

exercises/protein-translation/description.md

...at http://forum.exercism.org/t/tweak-language-and-formatting-in-protein-translation-description-md/17005/72

Protein Translation: Rewrite per discussion

---

bin/format-array.rb
exercises/flower-field/canonical-data.json
exercises/flower-field/instructions.md
exercises/flower-field/introduction.md
exercises/flower-field/metadata.toml
exercises/minesweeper/.deprecated

See:
https://forum.exercism.org/t/suggestion-deprecate-minesweeper-for-flower-field/17967

[ Flower Field ] Deprecate minesweeper for flower-field

---

exercises/variable-length-quantity/canonical-data.json

The existing test cases are all either:
- Ending or beginning with a 1
- All ones or all zeros
This could lead to faulty implementations

variable-length-quantity: add more test cases

---

exercises/luhn/instructions.md

The instructions works through an example number, `066 123 478`. However, in one location is is incorrectly written as `066 123 468`.

fix last number to check in luhn/instructions.md

---

exercises/triangle/description.md

Make the description explicit about degenerate triangles. See [forum thread](https://forum.exercism.org/t/triangle-tests-dont-cover-the-case-where-a-b-c-degenerate-triangle/18754/).

Triangle: explicitly exclude degenerate triangles

---

exercises/line-up/canonical-data.json
exercises/line-up/instructions.md
exercises/line-up/introduction.md
exercises/line-up/metadata.toml

Proposed in [a forum thread](https://forum.exercism.org/t/new-exercise-ordinal-numbers/19147) for review
- Names are chosen without Unicode characters
- Test cases are are not covering all edges
Thanks for comments / corrections of wording and naming. The exercise name might be changed also.
Edit: `f-puzzles.com` have not updated their TLS certificate, that's why the link checker currently fails.

Add new exercise: line-up
