- sieve.md
> Sieve: Added Clarification Algorithm is Inclusive

- sublist.md
- sublist.yml
> Improve sublist readme

- custom-set.json
It's big.  I'm finally ready to add this as I have a test program in Go ready to use it.  As usual when I assembled this I went through existing test programs and combined and consolidated things.  The section at the end with mixed types is still kind of strange.  I don't use it in Go.  Someone who can actually use the data might fix it up someday.
> add custom-set.json

- bob.json
- leap.json
A couple of common first exercises.
> add bob.json, leap.json test data

- rna-transcription.md
thymidine is the nucleoside that contains the nucleotide thymine
http://rosalind.info/glossary/dna-string/ (source of the exercise)
http://en.wikipedia.org/wiki/Thymidine
http://en.wikipedia.org/wiki/Thymine
> correct T nucleotide name

- tournament.md
This is to support the updated Go version of the exercise where this is part of the test suite.
> Clarify how ties in ordering should be resolved

- nth-prime.md
See: https://github.com/exercism/xruby/issues/95
> Make it clear you're not supposed to use standard libraries to implement nth-prime

- acronym.md
- acronym.yml
Metadata for new problem acronym.
[Problem added to Ruby track](https://github.com/exercism/xruby/pull/97)
> Added acronym problem metadata

- poker.md
- poker.yml
This is a somewhat more involved exercise due to poker hand evaluation having various corner cases (such as flushes being based on suits and pretty much everything else being based on ranks).
> Add poker exercise

- pov.md
- pov.yml
A proposal to add a graph re-parenting exercise.
There isn't much in the way of graph orientated exercises, so I felt this would fill a gap (on the more challenging side maybe).
An implementation has been prepared in clojure (see xclojure for the pull-request).
Possible extensions: require users to implement `path-to`
> Added POV metadata

- error-handling.md
- error-handling.yml
This is a focus exercise, so it doesn't require figuring out an algorithm, only applying some standard error handling strategies.
> Add error handling exercise

- hello-world.md
- hello-world.yml
This addresses exercism/rossconf#4, towards goal [#12](exercism/rossconf#12), by adapting the suggestion and text on exercism/exercism.io#2021. The purpose of this exercise is to serve as an introduction to Exercism.
The hello-world exercise will take an input for the caller's name. If a name is given, the program will say "Hello, #{name}!", and will otherwise spout "Hello, world!"
> Adapt hello-world exercise metadata to be an Exercism introduction

- README.md
- counter.md
- counter.yml
- doc/alternatives.md
- doc/coding/fetching-exercises.md
- doc/coding/refactoring-exercises.md
- doc/coding/submitting-exercises.md
- doc/contributing/contributing.md
- doc/contributing/git-workflow.md
- doc/discussing/hibernation.md
- doc/discussing/nitpicking-code.md
- doc/getting-help.md
- doc/getting-started.md
- doc/installing/configuring-the-cli.md
- doc/installing/installing-the-cli-on-linux.md
- doc/installing/installing-the-cli-on-mac.md
- doc/installing/installing-the-cli-on-windows.md
- doc/installing/installing-the-cli.md
- doc/installing/troubleshooting.md
- doc/installing/understanding-path.md
This fixes https://github.com/exercism/rossconf/issues/10
It has task-oriented directories now:
doc/          # General documentation
installing/   # Everything you need to get up and running.
coding/       # Programming the solutions to the exercises.
discussing/   # Giving and receiving feedback.
contributing/ # Participating in the project.
> Please pull newly created x-common/doc/

- react.md
- react.yml
This exercise is intended to make people play with the observer pattern.
> Add react exercise

- wordy.md
This informs about the type of problem this should be considered, as
mentioned in exercism/xruby#116
> Verbal, not written, word problem

- wordy.md
> Correct regular answer.

- hexadecimal.yml
The description mentioned ruby and gems, it now applies to all languages.
> changed description of problem hexadecimal to remove terms specific to Ruby

- word-count.json
word-count.json now has a base set of test cases for the word-count exercise.
> Added core set of test cases for word-count

- gigasecond.json
I am a little uncomfortable with the consistency of the JSON files and generators. I've added these messages and kept the structure the same, but feel as though some JSON refactoring across all the tests and generators may be required?
> Added messages to JSON test file

- hello-world.json
Removed last silly test and the message arrays
> Added hello world test definition

- raindrops.json
Removed the last test with the 12_121 number. I feel this test adds no value, and introduces unnecessary complexity into the test generation to create a test that passes style checks.
> Added raindrops.json test definition file

- strain.md
Also added just a little more exlanatory text.
> Mention possibility of other strain function names

- react.md
In response to discussion at https://github.com/exercism/xgo/issues/189
> clarify react

- meetup.json
No test cases for fifth weeks.  See https://github.com/exercism/exercism.io/issues/2142 (and some discussion in individual languages, like https://github.com/exercism/xgo/issues/151.)
> meetup common test data

- run-length-encoding.json
- run-length-encoding.md
- run-length-encoding.yml
Run-length encoding a real classic.
> Add new exercise run length encoding

- pangram.json
- pangram.md
- pangram.yml
We have `anagrams` and `palindromes` so we can't leave out `pangrams`. I think it's a nice short and simple task for beginners.
> Add new exercise pangram

- rail-fence-cipher.json
- rail-fence-cipher.md
- rail-fence-cipher.yaml
`simple-cipher` and `atbash-cipher` definitely need a companion. Meet `rail-fence-cipher`.
> Add new exercise rail fence cipher

- atbash-cipher.json
> atbash-cipher: Adding test JSON

- difference-of-squares.json
Fixing exercism/todo#85
Trimmed off a couple outliers from the Ruby and C# tests. I wasn't sure they made sense across the entire spectrum of languages that implement this problem and that didn't really add much in terms of the central task.
> difference-of-squares: adding test JSON

- acronym.json
> Acronym: Adding test JSON

- allergies.json
> Allergies: adding JSON test file

- two-bucket.json
Fixing exercism/todo#160. 
Is this clear enough or does it need some clarifying comments?
> two bucket: adding test JSON

- anagram.json
exercism/todo#68 pull request part of @codebar @ladieswhocode for the 24 pull requests event.
> Created a json file for the anagram exercises

- largest-series-product.json
These are a union of the existing tests among various language tracks.
Various error and boundary cases have been added as well.
Issues:
Issue #164
https://github.com/exercism/todo/issues/104
> largest-series-product: Add JSON test data

- luhn.json
[Here](https://github.com/exercism/todo/issues/110) for the discussion.
> Created luhn.json

- nth-prime.md
> Fixed plurality disagreement in nth-prime summary

- simple-linked-list.md
- simple-linked-list.yml
Only mention singly linked list and that they may be used to implement
LIFO stacks. At this point there is no need to mention things like
persistent data structures and immutability.
> Clarify documentation

- hello-world.md
The old link was broken, so I replaced it with an inline command as it's not too complex.
> Update hello-world.md workflow.

- linked-list.md
- linked-list.yml
The description and blurb for this problem seemed very confusing and contained incorrect information.
1) The original blurb and description specifically mentioned *singly linked lists*, but the goal of the exercise was to write a *doubly linked list* (or alternatively a *circular linked list*). See [Wikipedia](https://en.wikipedia.org/wiki/Linked_list) for the definitions and explanations.
2) The text was filled with references to "deques", without any explanation of the term (it's short for **d**ouble-**e**nded **que**ue). These deques were compared with arrays, but as I understand it, an array, like a linked list, is a possible implementation of a deque, which is a more abstract concept. See [this explanation on Quora](https://www.quora.com/What-is-the-difference-between-a-deque-and-a-do …
> Rewrite of the linked-list problem.

- CONTRIBUTING.md
This is my first try at explaining rebasing.
> Added a section on rebasing

- leap.json
- leap.md
This may help in adding per-test messages upon failure.
This is the type of message pattern that I was referencing in [this comment](https://github.com/exercism/x-common/issues/230#issuecomment-212222865).
> A little more descriptive Leap Year test titles

- bracket-push.json
start working on tests for bracket-push exercise
> add bracket-push test definition

- isogram.json
- isogram.md
- isogram.yml
This PR adds an exercise called isogram. Found on [Wikipedia](https://en.wikipedia.org/wiki/Isogram)
[JavaScript exercise PR](https://github.com/exercism/xjavascript/pull/198)
> Add Isogram exercise

- change.json
- change.md
As suggested here https://github.com/exercism/xphp/pull/79#issuecomment-218271354 by @kytrinyx
> Add change problem data

- wordy.md
Added explicit reference to order of operations to make instructions slightly clearer, see exercism/xjavascript#187
> Clarify README for wordy

- flatten-array.json
- flatten-array.md
- flatten-array.yml
first time adding metadata, would like people to review it and let me know if any problem exist
> added metadata for flatten-array question

- alphametics.json
1. case to check puzzles without a solution.
2. case to check puzzles with leading zero values.
> Alphametics: add two cases to test invalid puzzles

- pangram.md
Identifies the alphabet used, which is ASCII, case insensitive, A
through Z.
> Identify the alphabet used.

- bracket-push.json
Tests for a class of problems where an unopened bracket is closed for
solutions which only track opened brackets.
> Updated bracket-push tests

- CONTRIBUTING.md
The content of the docs directory is described in detail in the x-api CONTRIBUTING gude.
> Add link to description of docs directory.

- CONTRIBUTING.md
https://github.com/exercism/todo/issues/182
@Insti how does this look?
> update contributing guide to include track-specific contributing views

- TOPICS.txt
> Fix incorrectly grouped topic

- diamond.md
> Make spaces explicitly visible in diamond kata

- CONTRIBUTING.md
> Documentaton: Improve the Porting to another exercises documentation

- CONTRIBUTING.md
As suggested in: https://github.com/exercism/x-common/pull/307#discussion_r73289379
Replace 'the' with 'a'
> Documentation: Fix minor grammar issue in CONTRIBUTING.md

- bob.md
Fixes https://github.com/exercism/x-common/issues/360
> Remove the `Instructions` section in bob.

- exercises/connect/description.md
> Remove reference to 'black' and 'white' in description.

- CONTRIBUTING.md
Introduce the Track Anatomy section from the x-api's CONTRIBUTING.md to
according to https://github.com/exercism/x-api/issues/130
> Introduce Track Anatomy section from x-api

- exercises/raindrops/description.md
- exercises/raindrops/metadata.yml
I think that "has X as a factor" is more common wording for what the question asks, than "contains X as a factor".
Also fixed a typo in person agreement, in the blurb metadata.
> raindrops: Minor edit to description text, typo fix

- exercises/bowling/canonical-data.json
Reverts exercism/x-common#418
I need to apply #416 first!
> Revert "[Bowling] Add edge case with fill balls in a last-frame strike"

- exercises/run-length-encoding/canonical-data.json
Two new edge cases originally part of #434 now here on their own.
> run-length-encoding: Add simple edge cases

- exercises/hello-world/description.md
In Exercism "language" refers to the programming language name, (e.g.
C++), whereas Track ID refers to the identifier used on Exercism (e.g.
cpp).
> hello-world: Rename language to track ID

- exercises/sublist/canonical-data.json
> sublist: Add digits edge case test

- exercises/all-your-base/canonical-data.json
This conforms with the majority of the canonical data files I have seen.
> Change all-your-base canonical data to use an expected key.

- exercises/tree-building/description.md
The current description uses a rather hard to read description. I've tried to reword it to be more clear. Furthermore, I've added a sample tree to show how it can look like.
> Reword tree building problem and add example tree

- exercises/raindrops/description.md
`10` is a factor of `30` and was left out of the factors list in the problem description.
> Raindrops update: 10 is also a factor of 30

- TOPICS.txt
The switch statement is a distinct concept from if-else control-flow.
> topics: change if/else to conditionals

- TOPICS.txt
> TOPICS.txt: add Equality

- exercises/perfect-numbers/description.md
- add links to aliquot sum and Nicomachus
- provide examples of perfect, abundant, and deficient numbers
- provide instruction statement at bottom
- references #447
> perfect-numbers: description clarification

- exercises/bank-account/metadata.yml
> bank-account: Update short description. Closes #498

- exercises/run-length-encoding/description.md
> Speicfy input values for run-length encoding to fix #238

- exercises/rotational-cipher/cannonical-data.json
- exercises/rotational-cipher/description.md
- exercises/rotational-cipher/metadata.yml
I tried to add this to xrust. Realized I needed to add it here first.
> added rotational-cipher exercise

- exercises/difference-of-squares/metadata.yml
Excerpt from the fuller description for this problem (my emphasis):
> Hence the difference between **the square of the sum** of the first ten natural numbers and **the sum of the squares** is 2640
This PR updates the short description to match the component order of the full description.
> difference-of-squares: make short description consistent

- exercises/counter/.deprecated
Original deprecation in #407, for #383 and #80.
Trend of adding replacement and issue added in #532.
> counter: add explanation and issue to deprecated file

- exercises/point-mutations/.deprecated
Original deprecation in #406, for #384 and #184.
Trend of adding replacement and issue added in #532.
> point-mutations: add replacement and issue to deprecated file

- exercises/word-search/description.md
> word-search: update description example to match most common impl

- exercises/palindrome-products/description.md
93 * 99 isn't a palindrome, the factors are 91 and 99
> Mistake in largest palindrome product

- exercises/acronym/canonical-data.json
> acronym: Make exercise schema-compliant

- exercises/hello-world/canonical-data.json
> hello-world: Make exercise schema-compliant

- exercises/word-count/canonical-data.json
> word-count: Make exercise schema-compliant 

- exercises/scrabble-score/canonical-data.json
> scrabble-score: Make exercise schema-compliant

- exercises/wordy/canonical-data.json
> wordy: Make exercise schema-compliant

- exercises/robot-simulator/canonical-data.json
> robot-simulator: Make exercise schema-compliant

- exercises/secret-handshake/canonical-data.json
> secret-handshake: Make exercise schema-compliant

- exercises/triangle/canonical-data.json
> triangle: Make exercise schema-compliant

- exercises/difference-of-squares/canonical-data.json
> difference-of-squares: Make exercise schema-compliant

- exercises/etl/canonical-data.json
> etl: Make exercise schema-compliant

- exercises/nucleotide-count/canonical-data.json
> nucleotide-count: Make exercise schema-compliant

- exercises/ocr-numbers/canonical-data.json
> ocr-numbers: Make exercise schema-compliant

- exercises/meetup/canonical-data.json
> meetup: Make exercise schema-compliant

- exercises/meetup/description.md
> meetup: updated description.md to include additional clarification.

- exercises/bowling/canonical-data.json
This one was almost complaint. Just needed to fix the version!
Related to #625.
> bowling: Make exercise schema-compliant

- exercises/sum-of-multiples/canonical-data.json
> sum-of-multiples: Make exercise schema-compliant

- exercises/custom-set/canonical-data.json
> custom-set: Make exercise schema-compliant

- exercises/alphametics/canonical-data.json
> alphametics: Make exercise schema-compliant

- exercises/phone-number/canonical-data.json
> Make phone-number exercise compatible with the json schema

- exercises/dominoes/canonical-data.json
> dominoes: Make exercise schema-compliant

- exercises/flatten-array/canonical-data.json
> flatten-array: Make exercise schema-compliant

- exercises/pangram/canonical-data.json
> Make pangram exercise JSON Schema compliant

- exercises/largest-series-product/canonical-data.json
> largest-series-product: Make exercise schema-compliant

- exercises/rail-fence-cipher/canonical-data.json
> rail-fence-cipher: Make exercise schema-compliant

- exercises/rotational-cipher/canonical-data.json
> rotational-cipher: Make exercise schema-compliant

- exercises/space-age/canonical-data.json
> space-age: Make exercise schema-compliant

- exercises/transpose/canonical-data.json
> transpose: Make exercise schema-compliant

- exercises/variable-length-quantity/canonical-data.json
> variable-length-quantity: Make exercise schema-compliant

- exercises/wordy/description.md
There is no `times` in the canonical data for this exercise.
> Replace 'times' with 'multiplied by' for 'wordy'

- CONTRIBUTING.md
Add documentation of `ignore_pattern`
Improve documentation of `test_pattern`
Rename section so the anchor tag works.
(These commits can be squashed.)
> Update track configuration file (config.json) documentation

- exercises/connect/description.md
Updated description with reference to Issue: #212
> connect: Updated description to show the possibility of an unfair game

- README.md
> doc: remove inaccurate line from README.md

- TRACK_MAINTAINERS.md
This PR moves the Pony track from "Orphaned" to "Endangered".
> Update Pony track status

- TRACK_MAINTAINERS.md
Did read the instructions carefully enough.   Myself and kotp are the only two presently maintaining this track.
> Changed track status to endangered

- exercises/collatz-conjecture/canonical-data.json
- exercises/collatz-conjecture/description.md
- exercises/collatz-conjecture/metadata.yml
Add the collatz conjecture exercise in #803
> add collatz conjecture exercise

- CONTRIBUTING.md
I've opened an issue for it: https://github.com/exercism/docs/issues/23
> Delete stub about writing test generators

- exercises/forth/canonical-data.json
Not all languages handle unicode well.
> Removing unicode tests.

- exercises/scale-generator/description.md
> scale-generator: fix table markdown

- exercises/collatz-conjecture/canonical-data.json
Largest number of steps for number less than one million.  This is loosely based on the Euler Project.  It asks for the number less than 1 million that has the most steps.
> collatz-conjecture: add test case for a large number

- CONTRIBUTING.md
Hello!
I presume that it's OK in the future for such small, non-content changes to be "Commit[ed] directly to the master branch." Just being careful at the first PR ;-)
Cheers!
> fix ToC listing

- exercises/complex-numbers/canonical-data.json
- exercises/complex-numbers/description.md
- exercises/complex-numbers/metadata.yml
This exercise is about writing your own complex numbers implementation.
What does this teach?
- Operator overloading in those languages that support it.
- How testing for float operations works because you cannot assume an exact result (for some of the tests).
- Complex numbers themselves, which may be used in other exercises. (I have some ideas but nothing concrete yet.)
---
The tests are fairly basic for now and there are probably many cases that aren't covered so this is just a starting point.
> New exercise: complex numbers

- exercises/spiral-matrix/canonical-data.json
- exercises/spiral-matrix/description.md
- exercises/spiral-matrix/metadata.yml
I just found [this exercise](https://www.reddit.com/r/dailyprogrammer/comments/6i60lr/20170619_challenge_320_easy_spiral_ascension/) in [r/dailyprogrammer](https://www.reddit.com/r/dailyprogrammer/), and it seems to be a good fit for Exercism.
The exercise is really simple, but it allows very distinct solutions:
- Simple matrix filling, element by element.
- Recursive building without rotations.
- Recursive building with rotations.
- Non-recursive building with a recursive element formula.
- Non-recursive building with a non-recursive element formula.
The original problem asked for printing a properly formatted matrix, but I just used lists of lists in the `canonical-data.json` to avoid forcing one more string manipulation exercise. This way each track can decide by itself what would be …
> spiral-matrix: New exercise proposal.

- exercises/hamming/canonical-data.json
as explained in https://github.com/exercism/problem-specifications/pull/844#issuecomment-310842590
> fix versioning

- CONTRIBUTING.md
as suggested in https://github.com/exercism/problem-specifications/pull/844#issuecomment-310843654
> mention versioning details

- CONTRIBUTING.md
> Remove references to config.json's ignore key

- CONTRIBUTING.md
> Fix broken link to CLI doc

- CONTRIBUTING.md
The request-new-language-track repository has an issue template and documentation that describes the correct process.
> Fix instructions about requesting a new track

- exercises/palindrome-products/description.md
Also fix `it's` vs `its` typos.
> Clarify given range defines factors not product

- CONTRIBUTING.md
> Fix link to PR guidelines

- exercises/house/canonical-data.json
> house: implement canonical-data.json

- TOPICS.txt
This is meant to normalize topics to snake_case notation as discussed earlier.
Also relates to #888 
Your feedback is welcomed
> Normalizes topics to snake_case notation

- exercises/pig-latin/canonical-data.json
> pig-latin: tests for Y as a vowel

- exercises/isogram/description.md
Fix of issue #824 - isogram: spaces and hyphens not described.
Add details of how spaces and hyphens are acceptable, and an example of an isogram including hyphens.
> isogram: Update spec to include info about spaces/hyphens.

- exercises/change/metadata.yml
This link no longer works, and I couldn't find an updated one.
> change: remove broken link

- exercises/pascals-triangle/canonical-data.json
> Remove null error case from pascals-triangle canonical data

- exercises/palindrome-products/description.md
I find the palindrome-products description somewhat verbose, this is a shorter and I hope clearer version.
> Simplify palindrome-products description

- exercises/complex-numbers/description.md
Adding detailed description as some users might not be familiar with complex numbers.
New content includes definitions of operations on complex numbers and lists the operations that need to be implemented.
Closes #933.
> complex-numbers: add detailed description

- exercises/two-fer/description.md
> two-fer: remove the section on test-driven development

- exercises/phone-number/description.md
Follow-up from the dart track's PR: https://github.com/exercism/dart/pull/77
> phone-number: Fix typo in Readme

- exercises/rna-transcription/canonical-data.json
I merged #1027 too quickly.  Sorry about that.
I missed a couple of changes to the test data.
First change, bump the version.
> rna-transcription: Update canonical data

- exercises/secret-handshake/metadata.yml
Fixes broken link in `secret-handshake` metadata.yml
> secret-handshake: fix broken link

- exercises/all-your-base/canonical-data.json
#996 Updated the schema for canonical data. So I am updating the all-your-base exercise's json to reflect the change.
> all-your-base: Update json for changes to "input" policy

- exercises/anagram/canonical-data.json
#996 Updated the schema for canonical data. So I am updating the exercise's json to reflect the change.
> anagram: Update json for new "input" policy

- exercises/beer-song/canonical-data.json
#996 Updated the schema for canonical data. So I am updating the exercise's json to reflect the change.
> beer-song: Update json for new input policy

- exercises/flatten-array/canonical-data.json
> flatten-array: Apply new "input" policy

- exercises/difference-of-squares/canonical-data.json
> difference-of-squares: Apply new "input" policy

- exercises/diamond/canonical-data.json
> diamond: Apply new "input" policy

- exercises/crypto-square/canonical-data.json
> crypto-square: Apply new "input" policy

- exercises/connect/canonical-data.json
> connect: Apply new "input" policy

- exercises/collatz-conjecture/canonical-data.json
> collatz-conjecture: Apply new "input" policy

- exercises/change/canonical-data.json
> change: Apply new "input" policy

- exercises/say/canonical-data.json
> say: Apply new "input" policy

- exercises/word-count/canonical-data.json
> word-count: Apply new "input" policy

- exercises/sum-of-multiples/canonical-data.json
> sum-of-multiples: Apply new "input" policy

- exercises/pangram/canonical-data.json
> pangram: Apply new "input" policy

- exercises/triangle/canonical-data.json
> triangle: Apply new "input" policy

- exercises/wordy/canonical-data.json
> wordy: Apply new "input" policy

- exercises/hello-world/canonical-data.json
> hello-world: Apply new "input" policy

- exercises/zebra-puzzle/canonical-data.json
> zebra-puzzle: Apply new "input" policy

- exercises/variable-length-quantity/canonical-data.json
> variable-length-quantity: Apply new "input" policy

- exercises/twelve-days/canonical-data.json
> twelve-days: Apply new "input" policy

- exercises/sublist/canonical-data.json
> sublist: Apply new "input" policy

- exercises/spiral-matrix/canonical-data.json
> spiral-matrix: Apply new "input" policy

- exercises/sieve/canonical-data.json
> sieve: Apply new "input" policy

- exercises/secret-handshake/canonical-data.json
> secret-handshake: Apply new "input" policy

- exercises/rotational-cipher/canonical-data.json
> rotational-cipher: Apply new "input" policy

- exercises/rna-transcription/canonical-data.json
> rna-transcription: Apply new "input" policy

- exercises/leap/canonical-data.json
> leap: Apply new "input" policy

- exercises/roman-numerals/canonical-data.json
> roman-numerals: Apply new "input" policy

- exercises/markdown/canonical-data.json
> markdown: Apply new "input" policy

- exercises/pascals-triangle/canonical-data.json
> pascals-triangle: Apply new "input" policy

- exercises/perfect-numbers/canonical-data.json
> perfect-numbers: Apply new "input" policy

- exercises/phone-number/canonical-data.json
> phone-number: Apply new "input" policy

- exercises/pig-latin/canonical-data.json
> pig-latin: Apply new "input" policy

- exercises/food-chain/canonical-data.json
> food-chain: Apply new "input" policy

- exercises/nucleotide-count/canonical-data.json
> nucleotide-count: Apply new "input" policy

- exercises/nth-prime/canonical-data.json
> nth-prime: Apply new "input" policy

- exercises/minesweeper/canonical-data.json
> minesweeper: Apply new "input" policy

- exercises/anagram/canonical-data.json
> Anagram: Improve Test Coverage

- exercises/two-bucket/canonical-data.json
> two-bucket: apply lowerCamelCase rule to variables

- exercises/custom-set/canonical-data.json
> custom-set: Apply new "input" policy

- exercises/custom-set/canonical-data.json
A few cases were missed in #1137.  See #996 for policy reference.
> custom-set: apply "input" policy

- exercises/clock/canonical-data.json
> clock: apply "input" policy

- exercises/rational-numbers/canonical-data.json
- exercises/rational-numbers/description.md
- exercises/rational-numbers/metadata.yml
A description, metadata, and canonical data for a problem in implementing rational numbers.
> New problem: rational-numbers

- exercises/palindrome-products/canonical-data.json
> palindrome-products: apply "input" policy

- exercises/ocr-numbers/canonical-data.json
> ocr-numbers: apply "input" policy

- exercises/poker/canonical-data.json
> poker: apply "input" policy

- exercises/protein-translation/canonical-data.json
> protein-translation: apply "input" policy

- exercises/proverb/canonical-data.json
> proverb: apply "input" policy

- exercises/queen-attack/canonical-data.json
> queen-attack: apply "input" policy

- exercises/rail-fence-cipher/canonical-data.json
> rail-fence-cipher: apply "input" policy

- exercises/raindrops/canonical-data.json
> raindrops: apply "input" policy

- exercises/rectangles/canonical-data.json
> rectangles: apply "input" policy

- exercises/reverse-string/canonical-data.json
> reverse-string: apply "input" policy

- exercises/tournament/canonical-data.json
> tournament: apply "input" policy

- exercises/two-fer/metadata.yml
The exercise was originally made to have the same format as the old hello-world exercise:
provide a default value if none is passed, and use the passed argument when present.
This let us simplify hello-world so that it is a simple check to ensure that everything is
wired together correctly.
That said, there are languages where implementing this is non-trivial, so while we did make the
exercise to replace the old hello-world, it doesn't necessarily follow that it would always
directly follow a hello-world exercise.
I tagged you, @sjwarner-bp since you're listed as having touched that file recently ✨
> two-fer: Remove assumption about track ordering

- exercises/all-your-base/canonical-data.json
> all-your-base: apply lowerCamelCase policy

- canonical-schema.json
> Fix typo in canonical-schema.json

- exercises/pov/canonical-data.json
> pov: Apply new "input" policy

- exercises/list-ops/canonical-data.json
> list-ops: Apply new "input" policy

- exercises/word-search/canonical-data.json
> word-search: Apply new "input" policy

- exercises/forth/canonical-data.json
> forth: Apply new "input" policy

- exercises/grep/canonical-data.json
> grep: Apply new "input" policy

- README.md
> README: Apply input object policy

- exercises/yacht/canonical-data.json
- exercises/yacht/description.md
- exercises/yacht/metadata.yml
Create the three files that give a short description of the problem: a metadata file, a description file and a canonical test data file.
An implementation for the go track to come.
> yacht: create problem specification for scoring a single hand of yacht.

- exercises/scale-generator/description.md
* Removed most mentions of terms that were irrelevant ("diminished interval") or undefined ("accidentals").
* Removed irrelevant table
* Some light reformatting
Closes #1202
> scale-generator: Clarifying description.

- exercises/kindergarten-garden/canonical-data.json
closes #1213
Signed-off-by: Matthew Roseman <mroseman95@gmail.com>
> Kindergarten-garden: removed outdated comment in canonical-data.json

- exercises/sieve/description.md
At least in the Haskell track, everybody implements trial division. I hope the modified language makes it clearer that they are not implementing the proper algorithm.
> sieve : trial division avoiding hints

- exercises/yacht/description.md
Remove extraneous white space per #1208.
> yacht: remove whitespace from description

- exercises/armstrong-numbers/description.md
> armstrong-numbers: Fix math error in description

- CONTRIBUTING.md
> CONTRIBUTING.md: Fix "Git basics" broken link

- exercises/hamming/description.md
I was really puzzled by this sentence; I think it tries to say the opposite it currently says.
This is a proposal to fix the wording. Cheers from ROSS conf! :tada:
> hamming: fix wording regarding sequences of different length

- exercises/grade-school/canonical-data.json
closes #561
[description](https://github.com/exercism/problem-specifications/blob/master/exercises/grade-school/description.md)
This testdata is based on implementations of this exercise in the csharp and Delphi tracks.
> grade-school: add canonical data

- exercises/yacht/description.md
sorry, squashing has deleted my pull request...
continue from https://github.com/exercism/problem-specifications/pull/1258#issuecomment-402799501
> yatch: clarification about the combination

- exercises/affine-cipher/canonical-data.json
- exercises/affine-cipher/description.md
- exercises/affine-cipher/metadata.yml
I think I got everything correct for this PR.  Let me know if you want to see a bash example.sh that can pass all the tests.
closes #1260
> affine-cipher: New Exercise

- exercises/bob/description.md
> bob: limit scope of incoming messages

- exercises/complex-numbers/description.md
> complex-numbers: reword explanation of `e^(a + bi)`

- exercises/rna-transcription/canonical-data.json
> rna-transcription: add test for empty sequence

- exercises/allergies/canonical-data.json
One of the solutions I mentored returned True for all allergies that had a  score lower than the total test score. This test should catch this.
> Allergies: add testcase for checking "allergicTo" 

- exercises/sgf-parsing/canonical-data.json
> sgf-parsing: add canonical-data.json

- exercises/bracket-push/canonical-data.json
> bracket-push: Add test to prevent erroneous solutions.

- exercises/clock/canonical-data.json
As explained [here](https://github.com/exercism/rust/pull/635) in the rust branch, this test helped me find a flaw in my solution which otherwise passed all the tests.
Please tell me if I messed up the format! :)
> clock: add test case for comparing 24:00 and 00:00 clocks

- exercises/twelve-days/canonical-data.json
- exercises/twelve-days/description.md
> Twelve-Days: Punctuation fix

- exercises/rest-api/canonical-data.json
- exercises/rest-api/description.md
> rest-api: clarify list ordering

- exercises/robot-simulator/canonical-data.json
> robot-simulator: remove intermediate methods from test data

- exercises/two-fer/metadata.yml
fixes https://github.com/exercism/exercism/issues/4361
There wasn't any info about what additional work needed to be done when updating a source link (probably because it isn't done to often, but still...) So I decided to submit the PR, find out, and add the docs 😄
> [two-fer] update source link

- exercises/rest-api/canonical-data.json
> rest-api: fix inconsistent decimal format

- exercises/phone-number/canonical-data.json
It looks like the "code" was missing in some error messages.
> Phone-Number: Resolved some inconsistencies in error messages.

- exercises/high-scores/canonical-data.json
- exercises/high-scores/description.md
These updates address issues that were raised after the first implementation (#1378 )
> high-scores: multiple improvements

- exercises/gigasecond/canonical-data.json
The README depicts given a moment.....  Not given a birthdate.
> gigasecond: inputs are moments not birthdates

- exercises/sgf-parsing/canonical-data.json
@ RE: @elyashiv in https://github.com/exercism/python/pull/1615#issuecomment-444123399
This test case is mentioned in the README, but is not yet present in the canonical data.
> sgf-parsing: add test case for multiple properties

- exercises/saddle-points/canonical-data.json
> saddle-points: fix a Row index

- exercises/difference-of-squares/description.md
The 'Difference of Squares' exercise basically involves computing the sum of the first N integers, and the sum of the first N squares. Although there are standard formulas for both of these, I've noticed that students almost never use them. Virtually without exception, every solution I see uses loops.
This PR adds a hint to the problem description as follows:
> You are not expected to discover an efficient solution to this yourself from first principles; research is allowed, indeed, encouraged. Finding the best algorithm for the problem is a key skill in software engineering.
Fixes #1421 .
> difference-of-squares: hint at formulas

- exercises/space-age/canonical-data.json
> space-age: restrict seconds to fit within 32-bit int range

- exercises/grains/description.md
Also clarify that the task is to calculate the number of grains on a _given_ square, not on "each" square.
> grains: clarify square numbering convention (1-based, not 0-based)

- TOPICS.txt
A specific form of polymorphism see https://en.wikipedia.org/wiki/Operator_overloading
> TOPICS.txt: add operator_overloading

- exercises/knapsack/canonical-data.json
- exercises/knapsack/description.md
- exercises/knapsack/metadata.yml
I was looking through the available problems and realised Knapsack was not in them.
0-1 Knapsack is a classic problem and its not trivial if your doing it for the first time! Can we include it as part of this website?
I have attached the basic required files. (I can add in more tests if the exercise is approved)
> Knapsack: Proposal for new exercise 

- README.md
A few more favourites might also be added.
> Add link to editor/linter for canonical-data

- exercises/dot-dsl/description.md
- exercises/dot-dsl/metadata.yml
Please let me know if it's too wordy.
A big thanks to everybody that helped me on the issues page!
fixes #1537
> Clarify goal in the DOT DSL blurb and description

- exercises/space-age/description.md
- Move Earth into its proper position in the solar system
- Make wording more consistent
> [Space Age] Put Earth in it's proper order

- TOPICS.txt
We have a number of exercises that are about data structures, but
the topic was missing.
See https://github.com/exercism/javascript/issues/712
/fyi @alirezaghey @SleeplessByte @ErikSchierboom
> Add data structures to topic list

- exercises/matrix/canonical-data.json
Fix whitespace issue introduced by #1576, closes #1577.
Not sure if the extra whitespace is breaking anything yet, but best to get it fixed as quickly as possible and no telling how soon @DagmarTimmreck will be back at desk.
> matrix: fix whitespace issue

- exercises/micro-blog/canonical-data.json
- exercises/micro-blog/description.md
- exercises/micro-blog/metadata.yml
This is an exercise requiring students to truncate unicode strings. #1507
> Add micro-blog exercise

- exercises/grade-school/canonical-data.json
- exercises/grade-school/description.md
*Whole roster query* - case description is altered according to the discussion #1623 results.
Closes #1623
> #1623 `grade-school` canonical data does not correspond to the exercise description

- exercises/bob/canonical-data.json
Resolves #1630 
Replaces ambiguous `DMV` with `dentist`.
> Bob: Replaces DMV with dentist

- exercises/resistor-color/description.md
Resolves #1546.
I know there's already a PR but it seems it hasn't been updated since July last year and I was doing this exercise today in the Ruby track and it got me really confused.
> Resistor Color: Add requirements of the exercise

- exercises/two-fer/description.md
I don't think it's great anyways but I'm tired of seeing students submit X as the variable name because of picking up some subliminal hint here.
> two-fer: Update description.md

- exercises/simple-linked-list/metadata.yml
Previous link was no longer working properly, so use web.archive.org
need this before merging https://github.com/exercism/rust/pull/935
> Update Simple Linked List metadata

- exercises/luhn/description.md
apophenia - noun
"the tendency to perceive a connection or meaningful pattern between unrelated or random things"
compare: pareidolia - noun
"to perceive a specific, often meaningful image in a random or ambiguous visual pattern"
- Merriam Webster's
> Fix apophenia error slowing student progress

- exercises/palindrome-products/description.md
For me it took a while to understand that we calculate product of exactly two numbers. BTW in the [original problem](https://projecteuler.net/problem=4) it is stated clearly.
> Palindrome Products: refine the problem

- .github/CODEOWNERS
(mostly because I'm too lazy to request your review manually but this probably makes sense given the earlier discussion)
> CI: Add codeowners

- canonical-schema.json
(view the commits separately for a more readable diff)
> Add reimplements to schema

- STYLE-GUIDE.md
@SaschaMann Does this suffice? 🙂
> Add esoteric example

- exercises/nucleotide-count/description.md
See also #1716.
It is possible that my social commentary is a bit on the nose here, but I like it enough that I'm leaving it for now.
> Update nucleotide-count description

- .github/workflows/rebase.yml
> CI: Add /rebase command

- exercises/rational-numbers/description.md
If `b₁ = 0`, then `r₁` is not a rational number anyway.
From https://github.com/exercism/problem-specifications/pull/1655/files#r421573667
> rational-numbers: Remove redundant factor

- .github/workflows/rebase.yml
Additional details [here](https://github.com/cirrus-actions/rebase/commit/f72b20de85657401499fc29a910469d7663a78dc) and [here](https://bugs.chromium.org/p/project-zero/issues/detail?id=2070&can=2&q=&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary&cells=ids).
> [CI] Bump rebase action to fix CVE-2020-15228

- .github/workflows/ci.yml
Let's remove this until #1728 has been resolved properly to avoid build errors on master.
> [CI] Only run immutability check on PRs

- workflows/README.md
- workflows/configlet.yml
See https://github.com/exercism/github-actions/issues/14
> Use main branch for configlet-ci

- exercises/hamming/description.md
The note how to handle error is not suitable for inclusion in different languages.
With Exercism v3, tracks can add their track-specific instructions by adding an instructions.md.tpl file. See [the spec](https://github.com/exercism/docs/blob/main/anatomy/tracks/practice-exercises.md#file-docsinstructionsappendmd).
> hamming: remove implementation note on how to handle errors

- exercises/saddle-points/canonical-data.json
> saddle-points: Add comments about ordering

- exercises/luhn/canonical-data.json
See https://github.com/exercism/rust/pull/1228
> [luhn] Update canonical-data.json

- TOPICS.txt
Added the following topics: `unicode`, `iterators`, `closures` as asked in #1794
> Added topics closures, iterators, unicode

- exercises/tournament/canonical-data.json
> Tournament: ensure points are sorted numerically not lexically

- exercises/markdown/canonical-data.json
> markdown h7 test case should return a paragraph

- exercises/two-bucket/description.md
Followup to #1832.
Goals:
- maintain current problem with current limitations/scope of the exercise
- clarify the requirements of programs when generating a solution (or finding there is no solution)
close #1832
> Clarify problem description of two-bucket

- exercises/complex-numbers/canonical-data.json
As discussed here: https://github.com/exercism/problem-specifications/issues/1852
Added one test for each of the 4 basic operations: addition, subtraction, multiplication and division. The first operand is a complex number and the second is an integer.
> Add test cases for operations between complex and real numbers

- exercises/pov/description.md
Fixes #1874. Please see issue description for more details.
Note that this PR focuses on the issue linked above. (I think the description has some more unrelated issues.)
> [POV] Change description from graph to tree

- exercises/scale-generator/description.md
The instructions are very unclear about what the task at hand requires so I'm adding clear directives for the student to follow.
See https://github.com/exercism/problem-specifications/issues/1640
> scale-generator: add clear directives

- exercises/space-age/canonical-data.json
resolves  exercism/problem-specifications#1891
> space-age: add nonexistent planet to tests

- CONTRIBUTING.md
This addresses:
* single sentence per line
* minor formatting changes
* minor tyopgraphical fixes
Message-Id: <20211224204253.1630934-3-keeperotphones@gmail.com>
> Markdown style for Exercism

- exercises/triangle/description.md
The description said "the sum of the lengths of any two sides length of the third side." I fixed this here. Feel free to reword it. :smile:
> Fix a triangle inequality note

- exercises/largest-series-product/canonical-data.json
> Largest-Series-Product: Change error text for test case where span is negative.

- exercises/hello-world/description.md
As mentioned in https://github.com/exercism/problem-specifications/issues/1850#issuecomment-1013375228 - not sure whether the issue should be closed after this is merged or not.
> Update hello world description

- exercises/bowling/canonical-data.json
Following exercism/rust#916 I'm adding this test.
> Bowling: Add new test

- exercises/saddle-points/description.md
Change two saddle point references in this specification from column, row format to row, column format to be consistent with the canonical data.
Closes #1947
> Change saddle point references to row, column

- exercises/word-search/canonical-data.json
> word-search: Add test case for false-positives

- exercises/bowling/metadata.toml
> Fix bowling game copy

- exercises/acronym/description.md
Added examples to the task to clarify the bit the input and output. #1890
> #1890 Added examples for `Acronym` task

- exercises/secret-handshake/description.md
For someone unfamiliar with binary, it's not immediately obvious that 19 can be viewed as 3+16. Directly presenting the solution for the exemplary input of 19 without this context might confuse the reader wondering how one arrives at the presented solution before it is explained in the following sentence.
> secret-handshake: Make examples in instructions.md clearer

- .github/workflows/action-format.yml
- README.md
- bin/reorder-keys
- canonical-data.schema.json
- Add script to reorder test case keys
- ci: reorder keys as part of /format
I still have some testing to do, to see if this works.
> reorder keys in format

- exercises/acronym/description.md
Align the requirements with test cases.
Co-authored-by: Glenn Jackman <glenn.jackman@gmail.com>
> Specify how to handle punctuation

- exercises/rectangles/description.md
> 2028-clarify-language-rectangle-exercise

- exercises/high-scores/description.md
Adds "most" before "addictive" for grammatical purposes.
> Small grammar fix

- exercises/luhn/canonical-data.json
edit:
Closes https://github.com/exercism/problem-specifications/issues/2054
> luhn: test-case covering the usage of %5==0

- exercises/roman-numerals/description.md
Nova Roma's website uses the http connection scheme leaving anyone following that link vulnerable with unencrypted traffic. This enables an easier MITM attack which we want to avoid for the target audience who may not know better.
Additionally the link that has been used with the substitute (Imperivm Romanvm) has their information presented in a wiki format which is easier to consume and more in-depth. Most of the information is illustrated in tables.
Imperivm Romanvm has a converter akin to that which is presented within Nova Roma's website however the one by Imperivm Romanvm presents the answer in an easier to read form and details why the number is like it is. This can be illustrated through imagery which I will present below.
Nova Roma's website also doesn't represent the current …
> Update Roman Numeral with secure link and deeper information

- CONTRIBUTING.md
Trivial link format correction to guidelines.
> Fix: porting link format

- exercises/say/canonical-data.json
As stated in the [PR #1169 from the Elixir track](https://github.com/exercism/elixir/pull/1169), it is possible that all tests passed but some numbers are still wrong.
Wrong numbers that I found were between 20 and 1000.
> say: Add more tests

- exercises/dominoes/canonical-data.json
> dominoes: Add test case with separate three-domino loops

- exercises/palindrome-products/canonical-data.json
Made the test descriptions consistent.
> [Palindrome Products] Consistent test names

- exercises/armstrong-numbers/canonical-data.json
Someone look over my shoulder... first use of configlet. :)
Please see: https://github.com/exercism/raku/pull/540#issuecomment-1176314917
> [armstrong-numbers] Two new test cases

- exercises/leap/description.md
I missed another spot in the big one-sentence-per-line overhaul (#2118).
(I'm assuming we'll keep finding stray lines that need to be fixed. That was a real mess.)
> Fix broken line in leap description

- README.md
Slightly more descriptive summary of the purpose of this project.
> More descriptive summary

- .github/workflows/ci.yml
- exercises/affine-cipher/description.md
Fixes (I hope!) the issue found in #2096  without waiting for #2108 .
> Fix markdown comment

- exercises/crypto-square/description.md
> [Crypto-Square Instructions] Typo and clarification

- exercises/space-age/description.md
Add a note about "year" values and link to [Wikipedia/year](https://en.wikipedia.org/wiki/Year#Summary)
Closes #2060 
Inspired by @dsletten and that PR.
> Space Age: add a Note about various "year" values

- exercises/simple-cipher/description.md
See https://forum.exercism.org/t/simple-cipher-exercise-description/2597 for discussion.
There is zero context for this having anything to do with siblings, so let's stick to the initial theme about Caesar.
> Remove random references to siblings.

- exercises/matching-brackets/description.md
The string can also contain other characters
Closes #2187
> Clarify matching-brackets description

- exercises/binary-search/instructions.md
- exercises/gigasecond/introduction.md
- exercises/pangram/introduction.md
- exercises/sieve/instructions.md
Having double-checked against the styleguide, I see that we should be using four tildes unless there are special circumstances.
Since there are no special circumstances here, I've swapped out the backticks for tildes.
> Fix special blocks formatting

- exercises/binary-search/introduction.md
As @kotp pointed out in a downstream PR, the word number can refer to a musical number, like what someone would perform on stage, or a mathematical number, like what you would use to count.
In this introduction we talk about songs, confusing the issue about what number refers to.
This adds a parenthetical to clarify which type of numbers we mean.
> Tweak wording in binary search introduction

- exercises/binary-search/instructions.md
Even though there is a caution block, this brings attention to that
requirement where we are describing the solution to the problem.
Reference background discussion in exercism/ruby#1502
> [Binary Search] Emphasis "sorted" in the algorithm listing

- exercises/killer-sudoku-helper/description.md
Closes https://github.com/exercism/images/issues/4
> Change image URLs from v3-files to s3

- exercises/saddle-points/instructions.md
Minor fix. Make instruction match with example matrix.
> saddle-points: Fix row values in instructions

- exercises/saddle-points/instructions.md
> Update instructions for saddle-points

- exercises/list-ops/description.md
See https://forum.exercism.org/t/misleading-foldr-tests-in-python-track-list-ops/6215/11 for discussion
> List Ops: drop fold function ordering from the problem spec

- README.md
The current count is incorrect and being specific seems unnecessary.
> Update README.md with inspecific quantity of exceptions

- exercises/perfect-numbers/description.md
As per @kotp 's suggestions on track raku :
https://github.com/exercism/raku/pull/669
> [perfect-numbers] Join broken line and add colon

- exercises/grains/canonical-data.json
Not every language has exceptions.
Fixes: #2197
> grains: don't say "raises an exception"

- exercises/pythagorean-triplet/metadata.toml
Discussed in https://forum.exercism.org/t/blurb-for-pythagorean-triplet/8262
> Pythagorean Triplet no longer mentions product

- exercises/ledger/canonical-data.json
Change dates in entries and expected to match with description
> Fix typo in ledger test case

- exercises/leap/introduction.md
The list items lacked some consistency regarding the ending of the sentences, so I've added a period after every line instead of just some. 'youtube -> YouTube' fix is courtesy of @IsaacG .
(Agreed by @iHiD on [Discord](https://discord.com/channels/854117591135027261/1196534481994137622))
> Fixing a few spelling and puncuation issues

- exercises/list-ops/metadata.toml
This wasn't ready to be merged. Should have been a draft. Sorry.
Reverts exercism/problem-specifications#2390
> Revert "Add deep dive data to list-ops"

- exercises/list-ops/metadata.toml
Reverts exercism/problem-specifications#2391
> Add deep dive data to list-ops

- exercises/two-bucket/description.md
Based on discussion https://forum.exercism.org/t/wording-in-two-bucket-exercise/8371/9, I have changed starting bucket to initial starting bucket.
> Changed wording for two bucket exercise.

- exercises/two-fer/instructions.md
- exercises/two-fer/introduction.md
See https://forum.exercism.org/t/clarify-two-fer-instructions/10411
> Update two-fer instructions.md

- exercises/zebra-puzzle/introduction.md
See [forum](http://forum.exercism.org/t/48in24-exercise-05-07-zebra-puzzle/10614/3).
> Zebra puzzle link rendering

- exercises/pig-latin/instructions.md
Forum post at http://forum.exercism.org/t/48in24-exercise-05-28-pig-latin/11343/8
> Fix typo in pig-latin instructions

- exercises/pig-latin/instructions.md
Fixes a typo in the instructions in section "Rule 3"
> [Pig Latin] Typo in the instructions

- exercises/affine-cipher/description.md
Also, the part that says `length of alphabet - 1` can be confusing.
Is there another rewording?
> Add some punctuation

- exercises/resistor-color-duo/description.md
- exercises/resistor-color-trio/description.md
- exercises/resistor-color/description.md
See this [forum thread](https://forum.exercism.org/t/resistor-color-in-c/11621)
> Change resister colors in description to lowercase to match spelling in the problem data

- exercises/hamming/description.md
Related to https://forum.exercism.org/t/typo-in-hamming-instructions/12412.
I added spaces around the commas on line 14 and adjusted the casing for Hamming Distance consistently. The description uses Hamming Distance but the implementation note uses Hamming distance. [Wikipedia refers to it as Hamming distance](https://en.wikipedia.org/wiki/Hamming_distance) so I opted for that here.
> Update hamming text

- exercises/knapsack/instructions.md
- exercises/knapsack/introduction.md
As [discussed in the forum](https://forum.exercism.org/t/non-criminal-knapsack-story-sherpa/12479), being a sherpa is much more legal than being a thief.
> Knapsack: Make Bob a Sherpa

- exercises/knapsack/instructions.md
- exercises/knapsack/introduction.md
Reverts exercism/problem-specifications#2470
> Revert "Knapsack: Make Bob a Sherpa"

- .lycheeignore
http://forum.exercism.org/t/problem-specifications-check-links-job-failing/13070
> Link checker to ignore www.udacity.com (poker exercise)

- exercises/sublist/description.md
Update sublist description, replacing `sub-sequence` with `contiguous sub-sequence`
http://forum.exercism.org/t/sublist-make-instructions-more-precise/12111
> sublist: contiguous sub-sequence

- exercises/pythagorean-triplet/metadata.toml
Forum thread
https://forum.exercism.org/t/blurb-for-pythagorean-triplet/13852
> Correct blurb for the pythagorean-triplet exercise

- exercises/eliuds-eggs/introduction.md
I added appropriate alternate text for the SVG images.
I kept the ASCII Art for the interactive prompt but adjusted for a fence post error in the second example.
--
[New exercise suggestion: Pop Count](https://forum.exercism.org/t/new-exercise-suggestion-pop-count/7632) ( forum.exercism.org )
[eliuds-eggs: Reword exercise restrictions #2497](
https://github.com/exercism/problem-specifications/pull/2497#issuecomment-2481542061) ( github.com )
> [ Eliud's Eggs ] Four SVG images

- exercises/change/instructions.md
- exercises/change/introduction.md
Forum thread
https://forum.exercism.org/t/a-story-for-the-change-exercise/14086
Changes:
- Rephrased instruction
- Removed edges cases (see forum)
> Add a story to the change exercise

- exercises/phone-number/instructions.md
- exercises/phone-number/introduction.md
Forum thread
https://forum.exercism.org/t/a-story-for-the-phone-number-exercise/14213
There are a few minor changes compared to the forum version, but nothing substantial.
> Add a story to the phone-number exercise

- exercises/pascals-triangle/introduction.md
> Fix small typo in introduction

- exercises/rna-transcription/metadata.toml
Forum thread at https://forum.exercism.org/t/update-blurb-for-rna-transcription/14789/1
> Update rna transcription blurb

- exercises/anagram/instructions.md
Forum discussion: https://forum.exercism.org/t/14816/
> Remove references to "sets" and ordering in the anagram instructions

- exercises/simple-cipher/description.md
As discussed [here](https://forum.exercism.org/t/follow-casing-conventions-in-simple-cipher-docs/15657)
> Renaming Caesar Cipher to Caesar cipher (lower case)

- exercises/flatten-array/instructions.md
- exercises/flatten-array/introduction.md
Forum
https://forum.exercism.org/t/a-story-for-the-flatten-array-exercise/16056
> Add a story to the flatten-array exercise

- exercises/meetup/instructions.md
Update "five values" to "six values" to account for the new week-type.
> Fixed tiny typo inside Meetup instructions

- exercises/wordy/canonical-data.json
Round out the Wordy test cases per [this forum thread](https://forum.exercism.org/t/amending-wordy-tests-add-more-negative-number-scenarios-check-for-zero-operands/17859/8).
Additional cases:
* What is 0?
* What is -123?
* What is 0 plus 2?
* What is 3 plus 0?
> Wordy: add "What is 0?", "What is -123?" and addition with 0.

- exercises/triangle/description.md
See [forum topic](https://forum.exercism.org/t/triangles-clarify-what-a-degenerate-triangle-is/19418)
> Triangles: clarify degenerate triangles

- exercises/line-up/metadata.toml
> Title Case for line-up title

- .lycheeignore
based on https://github.com/exercism/problem-specifications/actions/runs/18350966237/job/52270551424
> lychee fix: exclude projecteuler.net
