gigasecond.json
Add two test cases, one with non-zero seconds but no late-in-the-day roll over, and one just before midnight causing roll over to another day.  Discussion at Go issue https://github.com/exercism/xgo/issues/122.
=> gigasecond.json: add test cases

hamming.json
Hope the comment is okay.  I know there's a conversation somewhere about unequal length strings but I didn't find it.  My opinion is that ignoring excess length is incorrect, although I know several languages do it that way currently.
=> add hamming.json

linked-list.yml
According to the source_url the problem is called Singly-Linked List
https://github.com/exercism/x-common/blob/master/linked-list.md
We already have a https://github.com/exercism/x-common/blob/master/simple-linked-list.yml
Using this description would be more accurate for the problem name itself used in the JSON files in each track.
=> Rename problem to "Singly-Linked List"

alphametics.md, alphametics.yml
This one goes in the category "challenge".
=> Add alphametics exercise

bowling.md
Please note that I don't think I've ever played a game of bowling in my life, so it could be I broke the description of the rules.
=> Make bowling readme less object-oriented specific.

bowling.md
=> Bowling: Improved clarity of scoring system

hello-world.yml
The comma is necessary for the test to authenticate in Python (and also in the other examples I checked, though I did not check all of them).
=> Add comma in "Hello, world!" instruction blurb

lens-person.md, lens-person.yml
=> Add lens-person Haskell-specific exercise

accumulate.md
Like the caveat about Erlang, it should be pointed out that using `MAPCAR` is the standard Lisp-y way of doing things - the alternative is the Common Lisp `LOOP` macro, which actually isn't very idiomatic of Lisp in general.
=> Point out that using MAPCAR is idiomatic Lisp

robot-simulator.md
* Eliminate redundancy in instructions.
* Eliminate confusing language about constrained rooms of different sizes,
appears to have been legacy text irrelevant to this problem.
* Eliminate step headers (also legacy?).
* Clarify that coordinates increase when moving north and east.
=> Slim down robot-simulator README

.travis.yml, README.md, bin/jsonlint
This is a useful sanity check to have as we start adding shared
test data.
It uses the `jq` library, which is a compiled C binary. It might be a bit heavy-handed, since `jq` is actually all about parsing and querying JSON on the command-line, but the other options were to install NPM to use a javascript library, or to use Ruby or Python, or build a small sanity-checker in Go. Since jq already exists and it's light-weight, I figured that was the best choice right now.
I didn't find any mature bash libraries that could validate json.
Another option would be to use `curl` to hit jsonlint.com--but somehow that feels a bit dirty.
=> Add a script to verify json syntax

bank-account.md
The bank account challenge is fairly uncommon, perhaps due to the fact that most languages don't have trivial support for concurrency.
Of the 3 examples I've found thus far (go, erlang, clojure) 2 of them reinterpreted (or misinterpreted) the bank closure paragraph as account closure; clojure ignored it entirely.
So, let's make the theory reflect practice instead of the other way around.
=> Make README match tests as best as I can determine

protein-translation.md
Because cystine is something else entirely.
Minor, but I am a protein scientist and care about such things.
=> Fixes "Cysteine" typo

robot-name.md
Result of discussion from issue #130 creating more clarity in the expected program output.
=> stricter definition of robot-name generator instructions regarding randomness and collisions

CONTRIBUTING.md
I'd like to add a CONTRIBUTING document to this repository with suggestions and guidelines for track maintainers, which we could then link people to when we ask if they'd like to be added as a maintainer on a track.
I don't know what should go into it, but here are some suggested starting points, based on a discussion I had recently with a new maintainer.
**PRs**
- If there are multiple maintainers, how do we avoid diffusion of responsibility?
- When should we ask for a second opinion when merging vs just merging right off the bat?
- How do we deal with typos and simple fixes? (just commit to master? Create a PR and then merge it yourself so the others get a notification?)
**When creating a problem**
- What behaviors should be explicitly specified in the readme?
- Should corner cases be …
=> WIP! Create contributing guide specific to tracks and exercises

food-chain.json
Attempt to fix exercism/todo#91.
As noted in the JSON itself, half the languages that implement this exercise test a `verse` method while the other half only test for the full song. 
I decided to split the difference by putting both the verses and the full song in the JSON. If an exercise only wants the full song, its generator can just grab the `full song` test data, ignore the start/end verse, and get down to business.
=> Food Chain: Test JSON created

pig-latin.json
This is a proposed fix for exercism/todo#125.
The tests all take an input string and compare the output to an expected string, so the test cases all have the same structure.
Some languages provide a named test for each case, and some group them together into parameterized tests. I've included descriptions at both levels so that the generators can use one or both types of description.
What do you think?
=> Add shared inputs/outputs json for Pig Latin exercise

hamming.json
Just fixes a small typo that I noticed when building another file.
=> Fix typo in Hamming test definitions

alphametics.json
Solves exercism/todo#67
I changed the name of the last Lua test to no longer reference "any boolean expression". That seemed too large a scope for this exercise. Also, the test didn't seem to cover that description very thoroughly.
=> Alphametics: Adding test json

sum-of-multiples.md
I just ran into this problem and got severely confused. The only way I figured out that the default behavior is to use `[3,5]` was by looking at an example solution, so I added a line making it explicit.
I also change the example to include a multiple of both 3 and 5. I thought this would be a nice hint that the list should be unique.
=> sum-of-multiples: Clarifying problem

simple-linked-list.md
In the simple-linked-list README we have the following example Ruby code:
~~~ruby
Element.to_a(nil) #=> []
Element.from_a([]) #=> nil
Element.reverse(nil) #=> nil
one = Element.new(1, nil)
one #=> <Element @datum=1, @next=nil>
one.datum #=> 1
one.next #=> nil
two = Element.new(2, one)
two #=> <Element @datum=2, @next=<Element @datum=1 @next=nil>>
Element.to_a(two) #=> [2, 1]
Element.reverse(two) #=> <Element @datum=1 @next=<Element @datum=2 @next=nil>>
range = Element.from_a(1..10)
range.datum #=> 1
range.next.next.next.next.next.next.next.next.next.next.datum #=> 10
~~~
However in `simple_linked_list_test.rb` we have the following test:
~~~ruby
def test_empty_list_operations
skip
assert_equal [], Element.from_a([]).to_a
assert_equal [], Element.from_a([]).reverse.to_a
end
~~~
The issue …
=> simple-linked-list: update Ruby example to include null object pattern

largest-series-product.json
Cases involving 0 spans are understandably tricky. Some have argued that
LSP('', 0) should be an error because it takes the max of an empty list.
An example is https://github.com/exercism/xclojure/issues/49.
I agree that taking the max of an empty list is zero.
I disagree that LSP('', 0) takes the max of an empty list.
There is exactly one 0-character string in the empty string (or any
other string), that being the empty string.
The product of that is 1, as the identity element of multiplication.
Since there is reasonable chance for confusion, it is best to add
explanatory comments.
=> largest-series-product: Comment on tricky cases

protein-translation.md
Use the rich diff to see the difference when the markdown is rendered
=> Fix markdown table formatting for protein-translation

word-count.json
In exercism/xpython#234 we discussed how adding a second
word in the normalization case might allow
some languages to use sorted counts as a normalization-agnostic
assertion.
I don't know that this will work in practice as allowing people to normalize to a different case, since all the other tests have lowercase words.
=> word-count: tweak normalization test case

octal.yml
These descriptions need to be language-agnostic since they are shown for
each language. #100 did the same for hexadecimal.
=> octal: Remove Ruby-specific terms

linked-list.md
This is an addition to pull request #188 which has already been merged. As mentioned by @NobbZ there and in issue #193, the track specific instructions for Elixir and Erlang mentioned an incorrect alternative solution. 
I left these instructions in during the rewrite because I wasn't sure how relevant or important they were for those tracks.
This PR removes the outdated/incorrect paragraph.
=> Update linked-list to remove outdated instructions

simple-cipher.md
There are two instances of 'Caeser' in `simple-cipher`. This PR changes the typos to 'Caesar'.
=> Fix typo of 'Caeser' in simple-cipher

diamond.md, diamond.yml
This PR adds the [diamond kata](http://claysnow.co.uk/recycling-tests-in-tdd/) as an exercise. This kata has become popular as a means to show how property-based testing can help you implement an algorithm correctly. See e.g http://blog.ploeh.dk/2015/01/10/diamond-kata-with-fscheck/.
=> Add diamond kata exercise

anagram.json
It seems that the intent is for passing candidates to be returned unchanged.
=> Fix expected output of an anagram test

largest-series-product.md, largest-series-product.yml, series.md, series.yml
It was unclear whether "consecutive" meant consecutive in *numerical
value* or simply *positionally adjacent*. Due to this problem's origin
in Project Euler, it was the latter.
To avoid any confusion this commit does the following:
* Replace the word "consecutive" in .yml files with "contiguous"
* Clarifies in the .md files that the series of digits only need be
positionally adjacent, not consecutive in numerical value.
* Uses examples in .md files that should make clear that numerical value
is not important.
This should prevent any further confusion of the form expressed in the
two issues
* https://github.com/exercism/xruby/issues/244
* https://github.com/exercism/xruby/issues/262
This is the first subtask of #197.
=> series, largest-series-product: clarify "consecutive"

clock.json
The existing test suite was not rigorous enough in testing the equality
of two clock values. Specifically, it was unable to compare two clocks
where the times were offset by 24 hours. For example,
clock{0, 1}
clock{0, 1441}
Since there are 1440 minutes in a 24 hour period, the time on the second
clock should be wrapped around, making it equal to the first.
This new test will catch this situation.
=> Add additional equality test to clock exercise

tree-building.md
- Use correct form of "its"
- Capitalize "id" as "ID"
- "an parent" => "a parent"
=> Tree Building grammar and capitalization fixes

sum-of-multiples.json
This is a synthesis of the existing tests in current tracks.
A short attempt to discern the history of the various tests:
Almost all tracks have the [3, 5] cases in common, as well as the
[7, 13, 17] and [43, 47] case. Indeed, these cases were present since
the first known sighting of sum-of-multiples at
https://github.com/exercism/exercism.io/commit/607be68494d30487c001303b6dc56c2b7b975409.
The [3, 5] to 100 case was added after discussion in
https://github.com/exercism/todo/issues/20 and
https://github.com/exercism/exercism.io/issues/2486. Most tracks had
adopted them at the time of this PR.
The [4, 6] and [5, 6, 8] cases arose from discussion in
https://github.com/exercism/exercism.io/issues/2341 - some tracks, but
not all, had adopted these tests at the time of this PR.
The [5, 25] …
=> Add sum-of-multiples.json

queen-attack.json
https://github.com/exercism/todo/issues/133
While implementing Queen Attack for Rust
(https://github.com/exercism/xrust/pull/89), I surveyed all current
implementations of this exercise and documented which tests they used.
That full list of tests is here:
https://gist.github.com/IanWhitney/dd34f8a16c730f3cd77c
In order of prevalence, the five most common test types cover:
1. Can 2 queens attack each other?
2. [Can 2 pieces occupy the same
space](https://github.com/exercism/xelixir/blob/0965c4e107de68979a493b82f9f0859773fcb83b/exercises/queen-attack/queen_attack_test.exs#L26)?
3. [Comparing string representations of the
chessboard](https://github.com/exercism/xelixir/blob/0965c4e107de68979a493b82f9f0859773fcb83b/exercises/queen-attack/queen_attack_test.exs#L33)
4. [Does a chessboard start …
=> Add standard tests for Queen Attack

clock.json
In the Go track I've seen a lot of people who only account for a clock
overflowing once in either direction. As the README describes the
problem, any overflow should be corrected, even if it accounts for
several days.
The second problem that I've seen a lot is people who adjust in the
display method, which means that the clocks would fail the equality
check. We weren't verifying equality against overflow, however, so we
didn't catch this.
I also removed two redundant test cases.
=> clock: add more test cases to canonical test data

queen-attack.json
Fixing my copy & paste errors that @petertseng noticed in https://github.com/exercism/x-common/pull/211
=> Update queen-attack test expectations

queen-attack.json
As discussed here:
https://github.com/exercism/x-common/pull/211#issuecomment-202596536
=> Split queen-attack tests into creation and attacking

rna-transcription.json
There is no biological basis for RNA->DNA transcription.
A couple of people suggested that we could rephrase this and make the
question _Given this RNA, what DNA sequence could produce it?_, but
it seemed simpler to simply remove it.
There is also the question of whether or not having the reverse
transcription helps guide people to a better/more generic solution.
I think that this is one place where we could have the discussion on the
website about hard-coding vs not.
See https://github.com/exercism/x-common/issues/148
=> rna-transcription: remove rna->dna cases from canonical data

sieve.json
This comes from a discussion we had in the xrust track
https://github.com/exercism/xrust/pull/97
Typically tests are ordered from the simplest case to the most
complex/edge-case. Putting the simplest test first lets students get a
passing test faster.
I think this re-ordered set of Sieve tests follows
this standard. The simplest test -- finding no primes -- is now first.
Followed by finding just 1 prime, then a few primes, then a lot of
primes.
=> Reorder Sieve tests

dominoes.json
Closes https://github.com/exercism/todo/issues/87
=> dominoes: Add JSON test data

pangram.json
this commit adds 3 total tests
- adds a non-pangram to resolve #222
- adds a pangram with underscores
- adds a non-pangram where some letters have been replaced by numbers
the latter two are designed to detect solutions that rely on counting
the number of word characters (which include numbers and underscoe)
=> add pangram tests

hello-world.md
The README for hello-world contained a duplication of the word "be", which I've removed.
=> hello-world: Remove duplicate word "be"

sum-of-multiples.md
As noted in https://github.com/exercism/discussions/issues/2, while #198
to remove the [3, 5] defaults is in flight, we should mark it as such in
the README.
This avoids confusion in the form of "Oh, this track doesn't implement
the defaults in the README, so I'll add them", reversing the work we've
done to make the exercise consistent across all tracks.
=> sum-of-multiples: Note change in flight in README

variable-length-quantity.md, variable-length-quantity.yml
Unfortunately JSON doesn't support the byte types so I couldn't add test cases :(
This PR goes hand in hand with https://github.com/exercism/xgo/pull/322
=> new variable length quantity problem

crypto-square.md
This PR is to address #190 .  
@petertseng asked if the output should be chunked.  My opinion, shared with @jtigger,  is that it should be, as it was in the original exercise that inspired this problem, and chunking the output fits aesthetically with the idea of creating a visual 'square' which is what the original users of this method would have done.
We're hoping we can get some consensus on the content of the README, then as a next step add a `config.json` for this exercise.  Thanks all!
=> Edit README to clarify exercise instructions (crypto-square)

crypto-square.json
Mentioned in #190, but I don't see that this has its own issue
Currently [18 tracks](http://x.exercism.io/problems/crypto-square) implement this exercise. I did [a survey](https://gist.github.com/IanWhitney/4912b100cca0b02a5c3ce21096a3e673) of their test suites and found that they fell into two types:
Type One: Test Just Encoding
--
- [python](https://github.com/exercism/xpython/blob/master/exercises/crypto-square/crypto_square_test.py)
- [lisp](https://github.com/exercism/xlisp/blob/master/exercises/crypto-square/crypto-square-test.lisp)
- [go](https://github.com/exercism/xgo/blob/master/exercises/crypto-square/crypto_square_test.go)
- [elixir](https://github.com/exercism/xelixir/blob/master/exercises/crypto-square/crypto_square_test.exs)
Follow this approach. Just an `encode` method (or …
=> Add crypto-square.json

custom-set.json
Discussed here: https://github.com/exercism/discussions/issues/10
I'm trying to improve custom_set in two ways:
1. Reducing the test suite, to remove redundancy or uninteresting
implementations.
2. Changing test order to improve flow
Reducing the test suite
----
The previous test suite contained 74 tests, which is a lot. I haven't
checked all the exercises, but it's the biggest test suite that I've
come across.
If all of those tests provided value (exposing corner cases, improving
implementations, etc.) then that's fine. But I found there to be a lot
of duplicate tests. With the subset/union/etc tests, a student's
implementation is usually done by the 2nd or 3rd test, so the remaining
tests didn't provide any additional value.
So I have removed the tests that seemed redundant.
The tests …
=> Shrink & clean up custom_set.json

tournament.md
Based on the conversation here: https://github.com/exercism/xrust/issues/122
This addresses a few problems that @ijanos had
- What do the column headers mean?
- How are points awarded?
- What is the input format?
There's still a need for a default test json file, but that can come in a different PR.
=> Update Tournament readme with more details

sublist.json
The test data is based off the python tests for the sublist example:
https://github.com/exercism/xpython/blob/master/exercises/sublist/sublist_test.py
=> sublist: Add JSON test data

scrabble-score.json
This supersedes PR #161 (preserving the work done by @SwamWithTurtles, thereby giving credit where credit is due).
Question: Should we have a case that has punctuation (which should not be scored)?
I don't like that the description for the non-English letter is a sentence whereas all the others are sentence-fragments, but that's the only case where more explanation is needed, I think.
=> Implement canonical dataset for scrabble-score problem

wordy.json
Currently 13 tracks implement this problem. The full list of each track's tests can be found [over at this gist](https://gist.github.com/IanWhitney/3fe2e8ca98d2c6ef37dccb313172f69b)
Of the 13, 11 tracks share the exact same test suite. Those are the tests that I have canonized in this json file.
Python and Scala each have their own tests. But the behavior under test is mostly the same.
Python checks for [some additional failure cases](https://github.com/exercism/xpython/blob/master/exercises/wordy/wordy_test.py#L52)
Scala [allows students to implement powers](https://github.com/exercism/xscala/blob/master/exercises/wordy/src/test/scala/WordProblemTest.scala#L63) as extra credit.
I can see putting some of the Python failure tests in here, but I wanted to get more feedback before making …
=> Add canonical tests for Wordy

custom-set.json
The goal of this change is to ensure that no tests that require set equality in an assertion precede the tests for set equality. This allows each set of tests to introduce as little new functionality as possible (assuming that tests are completed from top to bottom).
For example, the `add` tests assert set equality to determine whether `add` is implemented correctly, but these tests precede the `equal` tests which explicitly test the set equality method. Without this change, set equality and adding new elements to a set are both introduced in the `add` tests. After this change, the `equal` tests precede the `add` tests so that set equality is implemented prior to its use in the `add` tests.
Note that the `equal` tests were maintained below the `subset` tests to gently encourage set …
=> Reorder custom-set tests to improve flow

markdown.json, markdown.md, markdown.yml
It would be great to have some more refactoring exercises, and one that is easy
to write both poorly and well is a Markdown parser. This is just the outline
for that, but it does include a pretty basic set of tests that cover a small
subset of Markdown syntax.
This is in response to the discussion [here](https://github.com/exercism/discussions/issues/24) about adding more refactoring
exercises.
=> Adding Markdown refactoring exercise

etl.md
I might be misunderstanding this, but I believe this is an error.
Letter "A" doesn't score highly in Basque or Latin. If you check the [scoring tables on Wikipedia](https://en.wikipedia.org/wiki/Scrabble_letter_distributions), you'll see those numbers are the *frequency* of the letters. This is: letter "A" appears 14 times in the Basque version; still scores a single point.
I've been looking for other examples, bit it would appear only Pinyin Chinese scores more than 1 for an "A". I have altered the examples to be about letter "E" instead.
=> “A” appears 14 times, doesn’t score 14 points

triangle.md
We had a confused user of the Elm track because elm-test does not have a "skip" concept (https://github.com/exercism/xelm/issues/66). It seems to me that this sort of instruction would be more suitable as a comment in the test file for now.
The other option might be just qualify this note a bit.
=> Remove track specific wording from triangle readme

accumulate.md
As shown in the [example solution](https://github.com/exercism/xelixir/blob/master/exercises/accumulate/example.exs) it can be done in Elixir without using a named module, like Enum.reduce. In fact its probably confusing to suggest so.
=> removes an elixir specific clause that is not necessary

all-your-base.json, all-your-base.md, all-your-base.yml
This is the first my first exercise submission, so try to be nice! :grin: 
Partial solution to #276.
I haven't carefully checked the cases to see if everything is right, so there are probably some errors.
=> Add exercise all-your-base.

robot-simulator.json
Looking at the tracks that currently implement this problem the core tests seemed
to be
- Turn and check bearing/direction
- Place and check coordinate/position
- Move and check bearing & coordinates
The [F# track](http://exercism.io/exercises/fsharp/robot-simulator) (along with some others) had what seemed to be the most thorough yet small test suite, so I've largely copied their approach here.
There were some variant tests that I haven't included, but that I mentioned in the descriptin.
- Handling invalid directions
- Handling invalid instructions
- Defaults for position and direction
These are good things to have, but they aren't currently mentioned in the readme, so I left those tests out.
The [Go implementation](http://exercism.io/exercises/go/robot-simulator/readme) is a particular …
=> Common Test Suite for Robot Simulator

rectangles.json
This is a union of the three existing tests:
* https://github.com/exercism/xlua/blob/master/exercises/rectangles/rectangles_spec.lua
* https://github.com/exercism/xpython/blob/master/exercises/rectangles/rectangles_count_test.py
* https://github.com/exercism/xrust/blob/master/exercises/rectangles/tests/rectangles.rs
Closes https://github.com/exercism/todo/issues/136
=> rectangles: Add JSON test data

ocr-numbers.json, ocr-numbers.md
The tests come from the existing implementations. Most languages that
currently implement this problem use the exact same tests. The tests of
failures only exist in Python and Swift, but I thought they were useful
so I included them here.
While I've kept the existing tests, I have reordered them so that they
follow the problem as described in the readme. The problem progresses
from handling just single binary numbers, then garbling, then long binary
strings, then decimal numbers, then multi-line numbers.
I have also reworked the readme, clarifying the steps of the problem.
=> Add ocr-numbers test suite, update description

robot-name.md
The definition of this problem led to some confusion in the scala exercise's test case. Some languages have exercises that expect differing formats for the robots names. This is an attempt to make it explicit and clear to the end-users and the exercise creators to avoid this ambiguity.
An example of this issue can be found in this PR: https://github.com/exercism/xscala/pull/123
If this PR is accepted, I will be more than happy to check the languages that have the "Robot Name" problem to make sure the tests for the "Robot Name" exercises are consistent.
=> Explicitly describe robot name format

raindrops.md, raindrops.yml
Giving a new rule where a non-prime number is expected to be a factor,
this should not fail.
fixes #294
=> Raindrops: The factors are given, with no need to be prime.

triangle.md
"or equal to" was missing.
In mathematics, the triangle inequality states that for any triangle,
the sum of the lengths of any two sides must be greater than or equal to
the length of the remaining side.
Source: https://en.wikipedia.org/wiki/Triangle_inequality
=> Correct definition for the Triangle inequality

tournament.json
For the most part, the existing implementations all used the same tests:
* https://github.com/exercism/xcsharp/blob/master/exercises/tournament/TournamentTest.cs
* https://github.com/exercism/xfsharp/blob/master/exercises/tournament/TournamentTest.fs
* https://github.com/exercism/xgo/blob/master/exercises/tournament/tournament_test.go
* https://github.com/exercism/xrust/tree/master/exercises/tournament/tests
* https://github.com/exercism/xswift/blob/master/exercises/tournament/TournamentTest.swift
xgo is the clear outlier: Whereas all other tracks ignore invalid lines,
xgo declares that inputs with invalid lines cause an error (but empty
lines and comments are okay). Please refer to discussion in #286 where
we decide how to make this consistent across tracks.
For now, these tests follow …
=> tournament: Add JSON file

tournament.md
"Only accept" was a bit vague - this commit changes the mesage to say
that invalid line are ignored, and the tournament scored without them.
This is in line with the behavior of all current tracks. If reviewers
wish a change to this behavior, we can discuss that in a separate PR.
(Note that the go track is an exception, but it clearly states it is an
exception in its test suite visible to students)
Closes #286
Closes https://github.com/exercism/xrust/issues/122
=> tournament: clarify behavior on invalid lines (ignore)

transpose.md, transpose.yml
In reference to rust implementation <https://github.com/exercism/xrust/pull/151>
=> transpose: add .md and .yml

connect.json
It's related to the exercise on exercism/xruby#398.
Based on concerns presented on exercism/xruby#396.
=> connect: adding examples for connect exercise

binary.json
Adds test data for "binary" exercise for exercism/xruby#394.
Thank you so much for your time!
=> binary: Add test data for "binary" exercise

tournament.md
Note that this sentence was added in #254 and previously was not
present. No track has a test case that tests this condition (equal
points, unequal number of wins).
Because of a combination of various factors:
* Teams play each other no more than once
* Four teams per group
* Wins award three points and draws one
It's not possible to have a tie with teams with unequal numbers of wins.
At the minimum:
* One team (A) would get one win and zero draws.
* One team (B) would get zero wins and three draws.
That's not possible, since at least one draw from team B would be
against team A, giving team A an extra point and breaking the tie.
We *can* solve this by breaking any one of the above three conditions.
If we would like to, we should make that explicit decision and edit the
JSON test cases to …
=> tournament: Remove tiebreak in favor of more wins

connect.json
I think these are important since they're an interesting case for when a
start space in the search is also a goal space. I advocate for this in
original #297.
=> connect: Add cases for 1x1 boards

binary.json
Resolves #303
Does this seem like it covers all of the cases in the original? It felt to me like a number of the grouped assertions were testing the same thing, so I didn't include them all. I'm totally open to adding them, I just couldn't think of distinct names for all of them 😄!
Also, there has been some discussion about what the `expected` value should be. Both `null` and `-1` seem appropriate to me. I only chose to go with `-1` because I saw it used in the `hamming` data, so I assumed that was the standard. If this isn't the case, I'm happy to change it!
Thank you so much for your time and feedback! 😄
=> binary: split error case tests

anagram.json
rationale in individual commit messages
Closes #248 (I know #248 said it should be for newbies but I didn't see #248 when I made this PR, and saw the duplication in https://github.com/exercism/xhaskell/pull/224 and resolved to do something about it)
=> anagram: fix typo s/indentical/identical; rm duplicate cases; rm all "string argument" cases

raindrops.json
In all cases, the description is just the string representation of the
input number. This seems redundant and unnecesary, and I would like to
invoke "Don't repeat yourself" and remove these messages.
=> raindrops: remove redundant description from JSON file

triangle.json
Pursuant to dicussion in #202, we won't have cases where a + b = c.
Examples are (2, 4, 2, Isosceles) and (1, 3, 4, Scalene).
As of this writing, 21 tracks implemented triangle:
* https://github.com/exercism/xcsharp/blob/master/exercises/triangle/TriangleTest.cs
* https://github.com/exercism/xcpp/blob/master/triangle/triangle_test.cpp
* https://github.com/exercism/xclojure/blob/master/exercises/triangle/test/triangle_test.clj
* https://github.com/exercism/xcoffeescript/blob/master/exercises/triangle/triangle_test.spec.coffee
* https://github.com/exercism/xlisp/blob/master/exercises/triangle/triangle-test.lisp
* https://github.com/exercism/xecmascript/blob/master/exercises/triangle/triangle.spec.js
* https://github.com/exercism/xelixir/blob/master/exercises/triangle/triangle_test.exs
* …
=> triangle: Add JSON test data

hello-world.md, hello-world.yml
As https://github.com/exercism/exercism.io/issues/2746 rightfully
explains, the wording of "program" implies that the student is expected
to write a full program with a main function (or equivalent entry point
in language of choice).
Further, the wording of "greets" slightly implies that the function is
expected to put the result on STDOUT.
To remedy this, "program" is replaced with "function" and we specify
that the function should return the greeting.
Note that as #321 states, this is just one of many problems that has
"write a program" in its description. However, the "greets" -> "returns"
wording is an issue not covered by #321, so we deal with it here.
Closes https://github.com/exercism/exercism.io/issues/2746
=> hello-world: Be more function-oriented, not program-oriented

sgf-parsing.md, sgf-parsing.yml
In SGF, the node labeled `dd` is the 4-4 point, not the 3-3 point.
Also, SGF stands for [Smart Game Format](http://senseis.xmp.net/?SmartGameFormat), not Standard Game Format.
Neither of these will affect the actual exercise, but it's always worth getting the terms right in the README.
=> Fix minor mistake in sgf-parsing exercise

grep.json, grep.md
The current `grep` exercise is a bit odd. If mentions that the user should implement a function that returns pairs of line numbers and matching lines. However, this does not easily fit the latter suggestion that the `grep` function should also support flags, of which one flag is intended as only listing file names.
In this PR, I've reworded the exercise to make it more like you're re-implementing the Unix `grep` command, as now it expects just a string to be output (which should correspond to the string output by the `grep` command).
Furthermore, I've added a suite of test cases.
=> Add grep test data and update readme

simple-cipher.md
Change made to make the examples language agnostic. I replaced the
code with written examples in the two cases where it made sense
and removed the final example as translating it didn't translate
well to plain English
=> Remove Ruby code examples from simple-cipher README.

secret-handshake.md
Left both examples in as they were originally. It is worth noting
that the first example passes an integer and the second a string
to demonstrate that the exercise expects both types to be handled.
PR submitted in response to issue #171.
=> Remove Ruby examples from secret-handshake README.

sum-of-multiples.md
This partially reverts 1f0ad90774e3922558c39f8aa3ccd81b83b1c99f,
which partially reverted 89308fd925b604e84fb652d8b72ee74ca231474b.
The default behavior was added in #157 as a result of confusion in
https://github.com/exercism/exercism.io/issues/2654. Since then, we have
decided the way forward is to remove the default behavior altogether, as
discussed in https://github.com/exercism/x-common/issues/198.
This commit should be held until all tracks have removed their
expectations of default behavior.
=> sum-of-multiples: Mark as no longer under revision

TOPICS.txt
This list is intended for track maintainers to use in order to add arrays of topics to
each exercise in the track's config.json file.
=> Add list of topics for richer exercise metadata

roman-numerals.yml
This is the current blurb: "Write a function to convert from normal numbers to Roman Numerals: e.g."
I think the "e.g." should be removed.
👍 
Otherwise it reads like this:
># Roman Numerals
>Write a function to convert from normal numbers to Roman Numerals: e.g.
>The Romans were a clever bunch. They conquered most of Europe and ruled
it for hundreds of years. They invented concrete and straight roads and
even bikinis. One thing they never discovered though was the number
zero. This made writing and dating extensive histories of their exploits
slightly more challenging, but the system of numbers they came up with
is still in use today. For example the BBC uses Roman numerals to date
their programmes.
=> Remove unnecessary 'e.g.'

raindrops.md
The raindrops Readme is a little misleading by talking about prime factors. Raindrop-speak cares if a number is divisible by certain numbers. While those numbers do happen to be prime, their primeness shouldn't matter to solve this exercise. In the ruby track I've seen several folks require the `Prime` class to solve the exercise.
TBH, I would probably not use the word 'factor' at all & instead use 'divisible by'. Was 'divisible by' avoided to not give away the idea of using modulo too easily?
=> update raindrops.md to not focus on prime factors

sublist.json
In some languages, it is necesary to ensure that no pair of the four
possible expected values are equal. Otherwise, an essentially-empty
implementation may pass tests without actually doing any useful work.
Example: https://github.com/exercism/xpython/issues/342
This same warning was added to the triangle JSON file in #311.
=> sublist: Warn about comparing values

binary-search.json
Following the instructions proposed by @IanWhitney in #230, I created the missing json file with the test data for binary-search. Once this is merged https://github.com/exercism/todo/issues/73 can be closed.
There are two open issues regarding the exercise:
#234 - Following (and agreeing with) the majority there I did not include checking for sorted input. I also included a respective comment in the json file. The issue can be closed once the new test data is propagated through the tracks.
#244 - I included a comment with the summary of what was discussed there but the issue seems only partly addressed by this as there are additional ideas on how/where to address the issue.
=> binary-search: add json test data

all-your-base.md
The README of the new(ish) all-your-base exercise claims that the three example numbers are the same, but they aren't; the final zero was accidentally left off the trinary example. This PR fixes it, so that the claim on the README's final line will actually be true.
It also provides a perfect opportunity for mashing two memes together in the commit log. :sunglasses:
=> Fix incorrect example in all-your-base README

CONTRIBUTING.md
While reading the contributing guide I found some very minor errors that I
wanted to fix. This just corrects spelling and makes links to both give
more information and make the format a little more consistent.
=> [Docs] Small fixes to the Contributing Guide

CONTRIBUTING.md
The contributing guide has a section for squashing. In that section,
interactive rebasing was mentioned, however a different technique was
used to squash the commits.
This adds some high level instructions under the Rebasing section on how
to interactively rebase commits in order to squash commits.
=> [Docs] Adding a section for interactive rebasing

bin/jsonlint
We restructured the exercise files to live under exercises/:slug/*. This updates
the json linting script to look for the json files in their new location.
Fixes #371
=> Validate json files in new location

README.md
We recently reorganized the problem files, and the README was still
referencing the old filenames and locations.
This makes makes the new file structure explicit, and also fixes references
to files that were referred to using their old names and locations.
Fixes #372
=> Update documentation about problem data files

exercises/grep/canonical-data.json
Without this test, a solution to the "grep" exercise could get away with just ignoring the "-x" flag and having it not affect the code's behavior.
Fixes #368.
=> Test that "match entire lines" flag works properly

exercises/pascals-triangle/canonical-data.json
In surveying the current implementations, I found 2 main approaches:
- Test 1, 2, 3, 4, 5 and 20 without any boundary checking
- [Ruby](https://github.com/exercism/xruby/blob/e50b1cbeabc3a82c1ed7800da112b0984dbbf01c/exercises/pascals-triangle/pascals_triangle_test.rb) is a good example
- Test 4 & 6 rows, and test boundaries
- [Kotlin](https://github.com/exercism/xkotlin/blob/02ecc5a70719f0b0e741992f33879f880f7c407f/exercises/pascals-triangle/src/test/kotlin/PascalsTriangleTest.kt)
is a good example
Also, some languages exposed specific functions for `rows` and `last_row` while some relied on built-in functions for this behavior.
In this approach I'm trying to meld what I see as the best of these worlds.
`Rows` and `Last Row` functions
----
I think these functions should be implemented by …
=> Standard test suite for pascals-triangle

exercises/pov/description.md
The following information is inferred from the supposition that in the
bottom graph the path from 6 to 9 is `6 2 0 3 9` as specified later in
the README:
In the top graph: 1, 2, 3 are all children of 0.
In the bottom graph: Only 0 is a child of 2, and 1 and 3 are children of
2.
However, the same ascii art was being used to describe both situations,
which makes it appear as if 1 and 3 are children of 2 in the original
graph. If that is the case, then one would believe that the path from 6
to 9 should be `6 2 3 9`. In addition, there would be no explanation for
how the rearranged graph got to be the way it is.
In general, this ascii art's branching strategy makes it appear as if
there is a path between two siblings, because they connect at a point
other than the parent node.
This commit …
=> pov: Redraw to avoid confusion about edges between siblings

exercises/raindrops/canonical-data.json
I added new tests for edge cases after opening issue #434 on the Ruby track.  https://github.com/exercism/xruby/issues/434
=> raindrops: include edge cases in tests

nth-prime.json
Adding JSON test data to go along with my [xruby generator](https://github.com/exercism/xruby/pull/411)
=> nth-prime: Add JSON test data

exercises/isogram/description.md
When the blurb from the metadata of isogram:
> Determine if a word or phrase is an isogram
is combined with the description text, the resulting exercise
description becomes redundant.
> Determine if a word or phrase is an isogram. Determine if a word or
> sentence is an isogram. An isogram ...
So, this commit removes the redundant part from `description.md`.
=> Remove redundancy from the description of isogram

exercises/hello-world/description.md
Should allow reading of the rendered README.md easier if viewing in a restricted window.
I am not sure if this is even needed but I thought I would say anyway. I don't mind going through the rest of the ```description``` files and doing the same but I am aware this could be overkill.
When viewed through a restricted window in vim the README for a ```hello-world``` exercise was looking like this:
A quick format and it now looks like this:
=> Amended hello-world/description.md to be formatted to 80 chars.

exercises/flatten-array/description.md, exercises/flatten-array/metadata.yml
This fixes a minor typo. Nill is the verb whereas nil is the noun.
=> Use nil instead of nill in description/blurb

exercises/markdown/canonical-data.json
Currently, the tests and example both specify that the the HTML "bold" tag is `<em>`. This is incorrect; it would actually render as italic. `<strong>` renders as bold.
Option would either to parse as `<i>/<b>` or `<em>/<strong>`. Markdown parsers render bold as `<strong>`, and italics as `<em>`; this PR brings the exercise in line with this - `<em>` has been changed to `<strong>`,  `<i>` has been changed to `<em>`, .
Note that this PR was originally submitted against the xelixir repo (& was merged): https://github.com/exercism/xelixir/pull/257
=> Incorrect markup in markdown excercise

exercises/pov/canonical-data.json
Existing implementations:
* https://github.com/exercism/xclojure/blob/master/exercises/pov/test/pov_test.clj
* https://github.com/exercism/xfsharp/blob/master/exercises/pov/PovTest.fs
* https://github.com/exercism/xgo/blob/master/exercises/pov/pov_test.go
* https://github.com/exercism/xhaskell/blob/master/exercises/pov/test/Tests.hs
* https://github.com/exercism/xlua/blob/master/exercises/pov/pov_spec.lua
The tests are a combination of the existing tests.
The trees used:
* Singleton (present in all)
* Simple tree: X, parent, sibling (present in Clojure, Go, Lua)
* Large flat tree: X, parent, three siblings (present in all)
* Deeply nested tree: "singly-linked list" as a tree (present in all)
* Target has children: X, parent, two children (present in all*)
(in Clojure, Go, Lua, this case …
=> pov: Add canonical data

exercises/alphametics/canonical-data.json
This change addresses the issues outlined in #395. Using only addition simplifies the exercise to focus on one thing.
=> Simplify alphametics. Fixes #395

exercises/say/canonical-data.json
This is to close https://github.com/exercism/todo/issues/142.
The test cases were quite homogeneous in the different tracks. I ignored the following outliers:
- A couple of tracks added one or two more numbers, in OCaml there a lot more numbers (especially all the "teeens" are tested), Ruby adds a couple more big numbers. I don't think the additions add much value for the exercise.
- The test for the upper bound is missing in Haskell and Go, Go instead let's people solve the exercise the max_int value. I prefer to have the upper bound in place (and covered by a test) as in the description of the exercise.
For discussion: The description in my PR and in the existing tests currently only contains the number that is tested instead of a real description. This is not "best practice" but …
=> say: adding canonical-data.json

exercises/word-count/canonical-data.json
Related to https://github.com/exercism/xruby/pull/448
Add four additional test cases:
- Handles cramped lists: Tests that words separated by commas and no spaces are counted.
- Handles expanded lists: Tests that words separated by commas and new lines are counted.
- With apostrophes: Checks that words with apostrophes are also counted as words.
- With quotations: Checks that words with quotations are also counted as words.
=> Add word count cases

exercises/bowling/canonical-data.json
This is based on my work implementing this problem for Rust
https://github.com/exercism/xrust/pull/213
I'm addressing a few things here.
- The description at the top is now about implementing the tests, not
about the problem domain.
- I've reordered the test to (hopefully) make things flow more smoothly.
I found that the previous set of tests introduced concepts in kind of a
mix, instead of one at a time.
They are now:
- Score a 0 point game
- Score a game with no spares/strikes
- Spares
- Simple spare
- Spare with bonus
- Spare in last frame
- Strikes
- Simple strike
- Strike with bonus
- Strike in last frame
- Exceptions
Some other changes:
- Updated descriptions. My goal here was to try to clearly state what
bit of scoring logic was being tested in each test, without relying too
much …
=> Update bowling canonical-data

exercises/forth/canonical-data.json
Existing tests:
* https://github.com/exercism/xelixir/blob/master/exercises/forth/forth_test.exs
* https://github.com/exercism/xfsharp/blob/master/exercises/forth/ForthTest.fs
* https://github.com/exercism/xhaskell/blob/master/exercises/forth/test/Tests.hs
* https://github.com/exercism/xrust/blob/master/exercises/forth/tests/forth.rs
* https://github.com/exercism/xscala/blob/master/exercises/forth/src/test/scala/ForthTest.scala
All tracks had the exact same tests, with two exceptions:
First, The "All non-word characters are separators test". In particular,
F# chose not to include the Ogham space mark, and I argue the same in
https://github.com/exercism/xhaskell/pull/388.
The Ogham space mark adds no additional value (it is just another space
character) and is confusing (it is visually too …
=> forth: Add canonical data

exercises/acronym/canonical-data.json
From the  PHP example it isn't clear if the H and P come from "Hyptertext" and "Preprocessor" or from "HP" in the "PHP" at the front. GIMP makes it clear that it should just use the first letter of all caps words.
=> add GIMP acronym

CONTRIBUTING.md
This is a proposal for #230. Unfortunately none of the people that participated in the discussion there made the actual pull request. So I took the liberty of putting it all together in the hope that this does not offend the original contributors to the discussion, especially @IanWhitney and @petertseng.
The discussion about notes/comments/msg that spawned off in #230 is not solved in this PR as it should lead to a change in the [readme](https://github.com/exercism/x-common#test-data-format-canonical-datajson) etc. and is not directly connected to the contribution guide.
For discussion: I would like to add a comment under point 4 about how to think about including edge cases. Any suggestions about how to better formulate the consensus there that seems to be something like "avoid including …
=> contribution-guide: adding section of extracting shared test data

exercises/pig-latin/canonical-data.json
A consonant+qu should be moved to the end of the word, but not a vowel+qu. I've added a test case for this, as I've seen multiple solutions where this rule wasn't followed exactly.
=> add test case for vowel plus 'qu'

exercises/anagram/canonical-data.json
Removes unicode specific test cases for anagram. This refers to #413.
=> remove non-ascii test cases from anagram

exercises/bowling/canonical-data.json
The previous test does not quite capture the behavior.
If the first fill fill is a non-strikes, then the total fill-ball score
must be less than 10.
But, if the first fill ball is a strike, then the total fill-ball score
must be less than 20. Because that first fill-ball strike resets the
pins.
I had what I thought was a working implementation but it totally missed
the 2nd case. Adding a test to cover that case.
=> [Bowling] Add edge case with fill balls in a last-frame strike

exercises/bowling/canonical-data.json
I noticed some inconsistent casing in the test descriptions for this exercise.
=> Fix bowling description text case and typo

exercises/bowling/canonical-data.json
Fixes the mess I made of @IanWhitney's PR: #418 
* Add edge case with fill balls in a last-frame strike
The previous test does not quite capture the behavior.
If the first fill fill is a non-strikes, then the total fill-ball score
must be less than 10.
But, if the first fill ball is a strike, then the total fill-ball score
must be less than 20. Because that first fill-ball strike resets the
pins.
I had what I thought was a working implementation but it totally missed
the 2nd case. Adding a test to cover that case.
* Add edge case test for final-strike fill balls
This test checks that the fill balls validate correctly if the 2nd ball
is a strike.
=> [Bowling] Add edge case with fill balls in a last-frame strike (Re-applies #418)

bin/jsonlint
During CI bin/jsonlint checks the validity of the exercise json files using the external `jq` program.
This patch checks that `jq` is installed and provides an error message and guidance on where to look for instructions on installing if it is not present.
This is useful if you try to run bin/jsonlint on your development system and do not already have `jq` installed.
Before:
Erroneous invalid json messages due to command failing due to lack of `jq` rather than because of invalid json.
```
$ bin/jsonlint 
Invalid json: exercises/acronym/canonical-data.json
<snip many many more messages like this.>
Invalid json: exercises/wordy/canonical-data.json
```
After:
```
$ bin/jsonlint 
'jq' is not installed.
See https://stedolan.github.io/jq/download/ for installation instructions.
```
=> [bin/jsonlint] Add check for `jq` before running linter.

exercises/grains/canonical-data.json
Current implementations of this exercise are all nearly identical, so
creating a canonical test set was just a matter of documenting the
existing tests.
Some languages do not include the error-handling tests, but I think they
are valuable to include as the boundaries they test are part of the
problem domain.
=> Grains: Add canonical-data.json file

exercises/triangle/canonical-data.json
As discussed here: https://github.com/exercism/x-common/issues/379
Converts the tests so that they are checking the property of a triangle
and not its type (or type stand-in like symbol/atom/etc.).
I've removed some duplicative tests, but I believe I've still covered
all the edge cases that were part of the old test suite.
=> Triangle: Update tests to check properties, not types

exercises/alphametics/canonical-data.json
Add a few more easy cases so people can be a little more sure their solution is working before they run up against memory/time constraints\* when trying to solve the harder problems. 
Re-order the problems in order of difficulty.
Rename tests to match number of letters in the result.
\* The naive implementation of a solution tends to be O(n!)
=> [Alphametics] Add more easy cases.

exercises/raindrops/description.md
i believe that technically 1 and n are always factors of number n.
but more importantly--not including them in the examples leads to failures in the tests.
`raindrops_test.go:14: Convert(3) = "3", expected "Pling".`
that is, one can say the factors of 3 are either--
`[]int{1, 3}`
or
`[]int{}`
the tests expect 3 to be in the factor list, so i think it makes sense to include 1 and n in the examples :)
=> raindrops: include 1 and n in factor list in examples

exercises/food-chain/canonical-data.json
The current test for multiple verses checks for two consecutive
verses (from 1 to 2) which leaves room for interpretation.
It is unclear whether the solution should simply concatenate two (or
more, when variadic functions are available) possibly non-consecutive
verses or return a range of consecutive verses from start to end. As
observed in the Go track, this ambiguity results in differing
solutions which makes them harder to compare.
This commit changes the multiple verses test to cover two non-
consecutive verses (1 and 3). With the change, only a solution
returning a range of consecutive verses is accepted.
See exercism/xgo#412
=> food-chain: resolve ambiguity in multiple verses test

exercises/run-length-encoding/canonical-data.json
This removes the two unicode test cases as discussed in #428.
I also added one test case with an empty string and one with only chars that occur once. *If you would prefer those non unicode changes in a separate PR, just ask.*
=> run-length-encoding: Remove non-ASCII test cases

exercises/pangram/canonical-data.json
In https://github.com/exercism/x-common/issues/428 the decision was made
to remove non-ascii test cases from exercises that are not explicitly
about extended character set handling.
This PR removes the non-ascii test cases from the `canonical_data.json`
for this exercise.
=> pangram: Remove non-ascii test cases.

exercises/bowling/canonical-data.json
We have tests for:
* Rolling 11 in a single roll
* Rolling 5 then 6
* Rolling 5 then 6 after a last-frame strike
So it appears we are missing the test for rolling an 11 after a
last-frame strike. Let's add it.
=> bowling: Add tests for more than 10 after last frame

exercises/raindrops/canonical-data.json
Unlike the other canonical-data I have seen, the tests have no description.
I'm writing a test generator for the xocaml stream - it fails due to this.
=> Add descriptions for the raindrops tests.

exercises/pangram/canonical-data.json
=> pangram: Add case-insensitive test

exercises/leap/canonical-data.json
description adheres to the schema: leap year / standard year, then **either** the century **or** the year number itself.
No testcases have been altered/added/removed.
Related: https://github.com/exercism/discussions/issues/104
=> leap: Make the test descriptions consistent

exercises/isogram/canonical-data.json
This removes the two unicode test cases as discussed in #428. One test case was an isogram with German umlauts, the other one was a French word with a duplicated character with accent (also non-ASCII). I don't think we loose anything here without those test cases that isn't covered by the remaining ones.
I also added descriptions for the test cases and a test case with an empty string. *If you would prefer those non unicode changes in a separate PR, just ask.*
=> isogram: Revise canonical test data

exercises/minesweeper/canonical-data.json
an input containing only "8" implies that the student solution is
supposed to read a board with numbers and fill in the mines, which is
contrary to all other tests (read a board with mines, fill in the
numbers)
=> minesweeper: remove number from input, add mines

exercises/wordy/description.md, exercises/wordy/metadata.yml
- replace "step" with the slightly more accurate "iteration" in headers.
- remove language-specific instructions (referring to "delete `skip`")
- remove redundant examples; the canonical data should be the source of
variation.
- we're trying to avoid referring to "the program" or "write a
program"
=> wordy: trim-up description

exercises/leap/canonical-data.json
- only test cases remain that are necessary
- they have a clear description to help providing good names for tests
related: #462
=> leap: Rewrite the test cases and their descriptions

exercises/phone-number/canonical-data.json
Phone Number exercise tests have some variations across tracks. eg. for invalid numbers [ruby](https://github.com/exercism/xruby/blob/master/exercises/phone-number/phone_number_test.rb) expects a string of all(10) zeroes while [rust](https://github.com/exercism/xrust/blob/master/exercises/phone-number/tests/phone-number.rs) expects `None`.
It also differs from the Readme with implementing getting `country-code` from number and `pretty-printing` the number. I feel these should not be part of the exercise. Would like to know what others think.
Closes https://github.com/exercism/todo/issues/124
=> Phone-Number: Add Canonical data

exercises/sum-of-multiples/description.md
description updated to mention limits,
https://github.com/exercism/xgo/issues/340#issuecomment-238150900
=> sum-of-multiples: update description

.travis.yml, bin/check_required_files_present
Adds a bash script and travis configuration update to run it to check that all exercises have both a `description.md` and a `metadata.yml` file.
Note: This only checks for existence and does not validate the contents in any way.
=> CI check to verify required exercises files exist.

exercises/variable-length-quantity/description.md
delta-time seems to only be meaningful in the context of MIDIs. We are
dealing with just arbitrary integers, with no mention of domain.
The limit of a 28-bit int (0x0fffffff) is specific to MIDIs, whereas
variable-length quantities can deal with arbitrary sizes.
So why limit to 32-bits? Because it is a common size for languages, and
some language tracks already have tests that assume that the limit is
0xffffffff, so we might as well match them.
Closes #485
Closes exercism/xrust#224
=> variable-length-quantity: Limit to 32-bit int, not 28-bit int

exercises/luhn/canonical-data.json, exercises/luhn/description.md
I'm addressing a few different things here:
1. The tests exposed functionality that is not needed
The `addends` and `check_digit` methods aren't needed by clients of this
code, and I didn't see that students got any benefit from explicitly
implementing them. The presence of these tests pushed students towards a
particular implementation, which we [try to
avoid](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#improving-consistency-by-extracting-shared-test-data)
> The test cases should not require people to follow one very specific
way to solve the problem, e.g. the tests should avoid checking for
helper functions that might not be present in other implementations.
To fix this I've removed tests of `addends` and `check_digit`.
2. The tests were duplicative.
There's not a …
=> luhn: Update Luhn tests and description

exercises/variable-length-quantity/canonical-data.json
Implementing tracks:
* https://github.com/exercism/xcsharp/blob/master/exercises/variable-length-quantity/VariableLengthQuantityTest.cs
* https://github.com/exercism/xfsharp/blob/master/exercises/variable-length-quantity/VariableLengthQuantityTest.fs
* https://github.com/exercism/xgo/blob/master/exercises/variable-length-quantity/variable_length_quantity_test.go
* https://github.com/exercism/xlua/blob/master/exercises/variable-length-quantity/variable-length-quantity_spec.lua
* https://github.com/exercism/xphp/blob/master/exercises/variable-length-quantity/variable-length-quantity_test.php
* https://github.com/exercism/xrust/blob/master/exercises/variable-length-quantity/tests/variable-length-quantity.rs
All have pretty much the same tests.
Notable exceptions:
* Only PHP has the …
=> variable-length-quantity: Add canonical data

exercises/circular-buffer/canonical-data.json
The circular-buffer exercise was first added in 2014 May at #9, with
Ruby and Javascript as the initial implementing tracks:
* exercism/xjavascript#17
* exercism/xruby#17
Implementing tracks:
* https://github.com/exercism/xcsharp/blob/master/exercises/circular-buffer/CircularBufferTest.cs
* https://github.com/exercism/xdlang/blob/master/exercises/circular-buffer/circular_buffer.d
* https://github.com/exercism/xecmascript/blob/master/exercises/circular-buffer/circular-buffer.spec.js
* https://github.com/exercism/xerlang/blob/master/exercises/circular-buffer/circular_buffer_tests.erl
* https://github.com/exercism/xfsharp/blob/master/exercises/circular-buffer/CircularBufferTest.fs
* https://github.com/exercism/xgo/blob/master/exercises/circular-buffer/circular_buffer_test.go
* …
=> circular-buffer: Add canonical data

exercises/secret-handshake/canonical-data.json, exercises/secret-handshake/description.md
The time has come to help the abandoned #159 get merged.
Implementing tracks:
* https://github.com/exercism/xcsharp/blob/master/exercises/secret-handshake/SecretHandshakeTest.cs
* https://github.com/exercism/xecmascript/blob/master/exercises/secret-handshake/secret-handshake.spec.js
* https://github.com/exercism/xfsharp/blob/master/exercises/secret-handshake/SecretHandshakeTest.fs
* https://github.com/exercism/xgo/blob/master/exercises/secret-handshake/secret_handshake_test.go
* https://github.com/exercism/xhaskell/blob/master/exercises/secret-handshake/test/Tests.hs
* https://github.com/exercism/xjavascript/blob/master/exercises/secret-handshake/secret-handshake.spec.js
* https://github.com/exercism/xlua/blob/master/exercises/secret-handshake/secret-handshake_spec.lua
* …
=> secret-handshake: Add canonical data (revives #159)

exercises/luhn/description.md
Add notes on edge cases for Luhn in the description, and add a 0 length string test.
=> Note on luhn description for single digits

exercises/luhn/canonical-data.json
While implementing these tests for Rust I found that the final test was
not well written (my fault!)
https://github.com/exercism/xrust/pull/247
I added the alphabetical character to an already-invalid string. So the
test doesn't show anything useful.
Instead the test should show that a known-valid string is made invalid
by the inclusion of a non-digit
=> Luhn: Update test of non-digit

exercises/rectangles/canonical-data.json, exercises/rectangles/description.md
In the final canonical test case for this exercise, we count rectangles whose sides have length 1. Such rectangles have slightly odd-looking representations:
```
++
++
```
```
+-+
+-+
```
```
++
||
++
```
etc.
I updated the example to include a rectangle of this type to avoid an unpleasant surprise at the end of the exercise. Thoughts?
=> rectangles: update with 1xN, Nx1, 1x1 cases

CONTRIBUTING.md
In various tracks, I sometimes see contributors forget to do this, and
perhaps one cause is that the requirement isn't mentioned here (various
tracks link to this document to explain how to port an exercise to their
track).
Luckily, this gets caught by configlet (assuming the track is running
Travis CI and hasn't removed configlet), but it would be good to let
contributors to know of this up front.
Decision: This text explcitly mentions the `"exercises"` key, rather
than the deprecated `"problems"` key.
The following procedure:
gem install trackler --ignore-dependencies
grep -L exercises ~/.gem/ruby/$RUBY_VERSION/gems/trackler-2.0.6.10/tracks/*/config.json
says that only two tracks lack the `exercises` key: Ceylon and PL/SQL
* a PR https://github.com/exercism/xplsql/pull/16 is open for …
=> CONTRIBUTING: remind about adding to config.json

exercises/lens-person/metadata.yml
At the time it was added (#97), indeed [Haskell][haskell] was the only
implementing track, and it was marked Haskell-specific.
However, the [Scala][scala] track has also implemented this exercise.
I predict it is confusing for Scala students to see "Haskell specific"
in the list of the Scala exercises. The proposal is to change it to
"specific to languages with immutable data".
[haskell]: https://github.com/exercism/xhaskell/pull/84
[scala]: https://github.com/exercism/xscala/pull/157
Lenses can be a fit for any language that has immutable data and data
structures that can be nested.
In such a language, updating a deeply-nested field can be a lot of work,
but made easier with lenses. This exercise demonstrates the use of
lenses and is applicable to **any** language with immutable data, …
=> lens: mark as immutable-data-specific, not Haskell specific

exercises/prime-factors/canonical-data.json
Added canonical-data.json for the prime factors exercise [exercise description here](https://github.com/exercism/x-common/blob/master/exercises/prime-factors/description.md).
Addresses https://github.com/exercism/todo/issues/129
=> prime-factors: add canonical data

exercises/etl/canonical-data.json
After scouring the existing test suites, I noticed that a few of them [Python, for example] (https://github.com/exercism/xpython/blob/master/exercises/etl/etl_test.py) include keys that are not just single letters but words.  I've included one extra case at the bottom that tests that case.  Not sure if it's something we want to include here or not.
=> etl: Add canonical data

exercises/book-store/canonical-data.json
Descriptions have been shortened so as to make the json nicer for automatic test generators, so test case functions do not end up being too long.
=> book-store: shortened test descriptions

exercises/trinary/canonical-data.json
Added data for trinary exercise.
Included 3 tests around invalid trinary strings.  This is basically a union of all invalid tests that I saw across different tracks and it matches with the [exercise description](https://github.com/exercism/x-common/blob/master/exercises/trinary/description.md).
This addresses this issue on the `todos` repo: https://github.com/exercism/todo/issues/158
=> trinary: Add canonical-data.json

exercises/nucleotide-count/canonical-data.json
Nucleotide count description: https://github.com/exercism/x-common/blob/master/exercises/nucleotide-count/description.md
=> nucleotide-count: Add canonical-data.json

exercises/scrabble-score/canonical-data.json
After the discussion in #509 , here is proposed addition to the canonical data.
Feel free to pick nits!
If we really wish to stick to "proper, scrabble-approved word", I could make multiple cases for 
"the" 
"quick"
"brown"
"fox"
"jumps"
"over"
"lazy"
"dog"
But in my personal opinion that obscures the intended purpose. The complete alphabet is the shortest way to express the complete alphabet, and thereby makes the intent the clearest. Anything else just muddles the waters (IMHO).
=> scrabble-score: add alphabet completeness test

exercises/atbash-cipher/canonical-data.json, exercises/forth/canonical-data.json, exercises/forth/description.md, exercises/scrabble-score/canonical-data.json
#441
Originally tracked as #527
FYI @Insti @petertseng
=> multiple problems: Remove non-ASCII characters to fix #441

exercises/list-ops/canonical-data.json
Problem description [here](https://github.com/exercism/x-common/blob/master/exercises/list-ops/description.md) - albeit brief.
This is a first cut submit.  It most certainly needs revision.  If we can answer the following questions, I think I can make a second revision that should be pretty good.
Things to think about:
* Is the function representation clear enough? - see this discussed here: https://github.com/exercism/todo/issues/152#issuecomment-275889363
* Do we need to represent `foldl` and `foldr` in tests or is `reduce` sufficent?  After looking through 8 test suites from the existing implementations I found the following
* Many suites cover very large lists (0..100000) but that seems unreasonable to write into a json file... `"list": [0,1,2,3,4... lots more ... 99999, 100000]` ... …
=> List Ops: add canonical data

exercises/food-chain/description.md
Previously, the README contained duplicate text of the blub from [metadata.yml](https://github.com/exercism/x-common/blob/master/exercises/food-chain/metadata.yml#L2):
This fix removes the identical blub text from the README.
=> food-chain: remove repeated blurb text from README

exercises/change/canonical-data.json
The current error cases ask us to ensure that two types of targets are
invalid:
* targets smaller than the smallest coin
* negative targets
These are both reasonable.
I would react with chagrin if this led student solutions to assume that
these are the only two cases in which one could fail to meet the target
i.e. they assume that any target > the smallest coin is valid.
This commit proposes adding a case that disproves that - the target is
larger than even the largest coin, but you will not be able to get a
combination that reaches the target.
=> change: Add case for target > coins, but still can't make

exercises/run-length-encoding/description.md
=> run-length-encoding: make description consistent with test cases

exercises/luhn/canonical-data.json
The luhn test suite didn't cover a lot of cases, including:
- Strings of zeros
- Non-alphabetic characters
- Numbers which are only valid if you reverse the string
This updates the test suite to cover these.
Let me know if I'm doing anything wrong.
Refs: https://github.com/exercism/xrust/pull/253
=> luhn: Add more tests

exercises/run-length-encoding/canonical-data.json
Change the format of the canonical data json for the
run length encoding exercise to be the same as that for
the other multi-function exercises.
This is more useful for test generators (certainly the Ocaml
one).
Descriptions also updated to be a little clearer.
=> Make canonical data for RLE test generator friendly.

exercises/difference-of-squares/description.md
Updating this for legibility based on watching a new programmer solve the exercise.
=> difference-of-squares: tidy up description

exercises/nucleotide-codons/.deprecated
=> nucleotide-codons: deprecate in favour of protein-translation

exercises/book-store/canonical-data.json
It is important to us that descriptions explain **why** a case is being tested.
To this end, I explain in the description why the 11223345 case is being tested: Because you cannot greedily add books to a single group in this case. You have to know that two groups of four is cheaper than five plus three.
If this is not made clear, people may make assumptions that greedy is the correct way to go, as in: https://github.com/exercism/xcsharp/issues/181
To contrast this, immediately after I add a case where you should greedily add books to a single group: 4 + 2 is cheaper than 3 + 3.
I do not have in mind right now a better description for any other case in this file.
=> book store: Explain importance of greediness vs non-greediness

exercises/binary/.deprecated, exercises/hexadecimal/.deprecated, exercises/octal/.deprecated, exercises/trinary/.deprecated
=> deprecated file added for Binary and related

exercises/luhn/description.md
This updates the luhn examples to operate on even-length strings. This reinforces the idea that the numbers to be doubled are counted from the _right_, not from the _left_. (The previous odd-length example string did not emphasize this distinction.)
=> luhn: update examples to reinforce manipulating from the right

CONTRIBUTING.md
=> CONTRIBUTING.md: update pull request guidelines

README.md
Note that while there is a new schema proposed in #336, it's believed by me that everything being said in this PR is still applicable even when that schema is applied:
* msg will still be gone
* descriptions will still follow the principles
* errors will still be defined as they are in #401
So this may be evaluated without having to wait for #336
=> README: bring expectation of canonical-data.json values (description, errors, no msg) up-to-date

exercises/pascals-triangle/canonical-data.json
pascals-triangle: Clarify test case descriptions to distinguish between zero rows and null/no rows.
=> pascals-triangle: Clarify test case descriptions

exercises/hello-world/canonical-data.json, exercises/hello-world/description.md, exercises/hello-world/metadata.yml
As discussed in #520, the exercise `hello-world` is too complex to fulfill its purpose and we decided to simplify it.
The new test suite will simply expect the string **"Hello, World!"**, and will serve mainly as a sanity check that everything is working.
This change may disrupt some tracks that already have it implemented, so we are scheduling the merging of this PR to allow the @exercism/track-maintainers to sync track-specific changes with `x-common`.
The merging is tentatively scheduled to: **2016-02-20 00:01 UTC** +-1 day 😄
Please direct any question/critic to #520, so that we can keep the discussion focused there.
Closes #520.
=> hello-world: Change to always expect "Hello, World!"

exercises/counter/metadata.yml, exercises/error-handling/metadata.yml, exercises/lens-person/metadata.yml, exercises/nucleotide-codons/metadata.yml, exercises/react/metadata.yml, exercises/rectangles/metadata.yml, exercises/variable-length-quantity/metadata.yml
As discussed in exercism/x-common#597, it seems there is no reason to keep information about deprecation or exercise classification in the `metadata.yml` files.
Closes #597
=> metadata.yml: Remove nonstandard metadata (cleanup)

exercises/bowling/canonical-data.json
The JSON file currently says "When to error is also left up to your
implementation", but we should instead be explicit.
Let's say I `roll 5`, then `roll 6`, then `roll 0` 18 times.
Okay, that's 20 rolls, that's a full game, so I can take the score now,
right?
Now I try to take the score and find that I get an error. Argh!
In the absolute best case, the error result from score would be so kind
to tell me that my `roll 6` way back there was invalid, but in the worst
case it might not, and I would be left to my own devices to figure out
what happened, since there was no feedback on any of the individual
rolls.
This commit proposes that invalid rolls be made explicit right when the
roll is made, not at some unspecified time in the future (when
attempting to take the score of the game). This …
=> bowling: be more explicit about when errors should happen

CONTRIBUTING.md
The description for the link says:
* to get a list of all the exercises that can be ported to a track
* for example here is the list of exercises that have not yet been implemented for the Ruby track
This clearly indicates that we want to go to the url which shows list of exercises that are present correctly at relative path _/todo_ not _/contribute_. In fact, _/contribute_ link redirects to _/todo_ link for the list of exercises still unimplemented.
So, we can avoid this always needed redirect for ease of use.
=> Correct unimplemented exercises link in CONTRIBUTING.md

exercises/hello-world/description.md
I think it could be worthwhile to clarify what "says" means in the exercise description. Often, "Hello, World!" programs print `Hello, World!` to the screen, but the Exercism exercises I've seen instead ask for a function that returns the string `Hello, World!`.
Because "says" could sound like it's figuratively referring to printing to the screen, and because a learner familiar with "Hello, World!" programs might expect to write a program that prints `Hello, World!` to the screen, I think "returns the string" might be clearer here.
Thoughts?
=> hello-world: clarify "says"

exercises/perfect-numbers/canonical-data.json
Closes #575. See that issue for background information. Please contribute any new comments in this PR. Thanks!
I attempted to follow the proposed canonical data spec from https://github.com/exercism/x-common/pull/602. If you spot any deviations from the proposal, please let me know and I can correct them. cc @rbasso for his expertise and validation 😄 [One thing I was unsure of: whether it is expected that inputs/outputs always be strings, or whether other data types (as used for inputs here) are permitted by that spec.]
=> perfect-numbers: add canonical data

exercises/diamond/canonical-data.json
Closes #556. See that issue for background information. Please contribute any new comments in this PR. Thanks!
I'm far from a property-based testing expert, so my explanation in the test data comment is likely clumsy. Please feel free to explain how to refine it!
I attempted to follow the proposed canonical data spec from https://github.com/exercism/x-common/pull/602. If you spot any deviations from the proposal, please let me know and I can correct them. cc @rbasso for his expertise and validation 😄
=> diamond: add canonical data

exercises/change/canonical-data.json
All the current positive test cases include 1 unit coin in available coins and it's could be confusing.
This commit proposes a new test case that is positive but not includes 1 unit coin in the input.
=> change: Added a positive case without 1 unit coin available

README.md, canonical-schema.json
In exercism/x-common#336 (`canonical-data.json` standardisation discussion), it was recently discussed a JSON Schema to capture the fundamental structure needed for `canonical-data.json` files.
After a lot of discussions and a few iterations, the [resulting schema](https://github.com/exercism/x-common/issues/336#issuecomment-280550277) proposed seems stable and mature enough to become at least a recommended standard, IMHO.
This proposal was designed with the following goals:
- Keep/improve human-readability.
- Keep it flexible enough to allow designing any reasonable test suite.
- Make it more regular and machine-readable.
There where naturally some trade-offs, as it is impossible to satisfy these objectives completely, but I think we got a good balance here.
To get a first impression of …
=> Add JSON Schema for 'canonical-data.json' and update the README.md

exercises/leap/canonical-data.json
=> leap: Make exercise schema-compliant

exercises/book-store/canonical-data.json
=> book-store: Make exercise schema-compliant

exercises/all-your-base/canonical-data.json
=> all-your-base: Make exercise schema-compliant

exercises/anagram/canonical-data.json
=> anagram: Make exercise schema-compliant

exercises/allergies/canonical-data.json
=> allergies: Make exercise schema-compliant

exercises/atbash-cipher/canonical-data.json
=> atbash-cipher: Make exercise schema-compliant

exercises/bob/canonical-data.json
=> bob: Make exercise schema-compliant

exercises/raindrops/canonical-data.json
=> raindrops: Make exercise schema-compliant

exercises/rna-transcription/canonical-data.json
=> rna-transcription: Make exercism schema-compliant

exercises/run-length-encoding/description.md
The description incorrectly stated that white spaces 
would be passed through unchanged (details #613).
=> run-length-encoding: Fix incorrect description

exercises/run-length-encoding/canonical-data.json
=> Adds tests for whitespace and lowercase characters for the "Run Length Encoding" exersize

exercises/change/canonical-data.json
=> change: Make exercise schema-compliant

exercises/grains/canonical-data.json
=> grains: Make exercise schema-compliant

exercises/luhn/canonical-data.json
=> luhn: Make exercise schema-compliant

exercises/binary/canonical-data.json
=> binary: Make exercise schema-compliant

exercises/pig-latin/canonical-data.json
=> pig-latin: Make exercise schema-compliant

exercises/say/canonical-data.json
=> say: Make exercise schema-compliant

exercises/trinary/canonical-data.json
=> trinary: Make exercise schema-compliant

exercises/crypto-square/canonical-data.json
=> crypto-square: Make exercise schema-compliant

exercises/queen-attack/canonical-data.json
=> queen-attack: Make exercise schema-compliant

exercises/rotational-cipher/canonical-data.json
Should effectively be the same test as the one above it due to modulus
math, but was also literally the same test.
=> rotational-cipher: match test data to description (26 -> 0)

exercises/nth-prime/canonical-data.json
=> nth-prime: Make exercise schema-compliant

exercises/minesweeper/canonical-data.json
=> minesweeper: Make exercism schema-compliant

exercises/pascals-triangle/canonical-data.json
=> pascals-triangle: Make exercise schema-compliant

exercises/connect/canonical-data.json
=> connect: Make exercise schema-compliant

exercises/binary-search/canonical-data.json
=> binary-search: Make exercise schema-compliant

exercises/perfect-numbers/canonical-data.json
Original description
> Non-negative integer is rejected (not a natural number)
could be interpreted as suggesting that _any_ non-negative integer should be rejected. This is not the case. New description
> Zero is rejected (not a natural number)
reflects intent much better.
=> perfect-numbers: fix misleading test description

exercises/custom-set/canonical-data.json
~~**Warning:** This PR is based on #672, and should not be merged before it. Only the third commit is new.~~
As suggested in [this comment](https://github.com/exercism/x-common/pull/672#discussion_r105240340), this PR chances the a description in the canonical data, and so it also bumps the PATCH version number.
=> custom-set: Fix description that doesn't match property name

exercises/gigasecond/canonical-data.json
=> Gigasecond: Schema Compliance

exercises/food-chain/canonical-data.json
=> food-chain: Make exercise schema-compliant.

exercises/circular-buffer/canonical-data.json
=> circular-buffer: Make exercise schema-compliant.

exercises/bracket-push/canonical-data.json
=> bracket-push: Make exercise schema-compliant

exercises/gigasecond/canonical-data.json
=> Fix "Gigasecond: Schema Compliance"

exercises/isogram/canonical-data.json
=> Make isogram exercise JSON Schema compliant

exercises/anagram/canonical-data.json
There are some tracks that generate their test suits and use the description field as name for the test function/method.
If this would get merged. Do we change the version to 1.1.0 or 1.0.1?
*Note: Don't know if the new names are so great but I couldn't find different ones.*
=> anagram: Rename duplicated test case description

exercises/markdown/canonical-data.json
=> markdown: Make exercise schema-compliant

exercises/list-ops/canonical-data.json
=> list-ops: Make exercise schema-compliant

exercises/rectangles/canonical-data.json
=> rectangles: Make exercise schema-compliant

exercises/react/canonical-data.json
=> react: Make exercise schema-compliant

exercises/forth/canonical-data.json
=> forth: Make exercise schema-compliant

exercises/prime-factors/canonical-data.json
=> prime-factors: Make exercise schema-compliant

exercises/run-length-encoding/canonical-data.json
=> run-length-encoding: Make exercise schema-compliant

exercises/sublist/canonical-data.json
=> sublist: Make exercise schema-compliant

exercises/pov/canonical-data.json
You probably want to review commit-by-commit (but hey don't let me tell you what to do, if you want to review the whole thing at once you are free to do it!).
I suppose there can still be a reformatting too (you'll notice a `"cases": [{`) line but...
1. Since `testGroup` is necessarily and both types that might be elements of it are objects, I have absolutely no compunction about putting the `[{` on the same line!
* Unfortunately, I did not apply the same treatment to the inner `cases`, sorry.
2. Keeping that diff small!
3. Okay, if you *really* want me to reformat, I can, but I wanted to make sure that there are no *other* changes that people want, because then I would have to rebase and blow away my reformatting.
=> pov: Make exercise schema-compliant

exercises/roman-numerals/canonical-data.json
We'd like some descriptions so that roman-numerals can be brought into
compliance with the schema, as in #625.
Closes #451 via replacement
=> roman-numerals: add descriptions

exercises/pov/canonical-data.json
We had already removed these in #704, but I forgot to remove the
comments.
=> pov 1.1.1: remove comments about `trees` section

exercises/roman-numerals/canonical-data.json
=> roman-numerals: Make exercise schema-compliant

exercises/two-bucket/canonical-data.json
=> two-bucket: Make exercise schema-compliant

exercises/two-bucket/canonical-data.json
Fix a [silly mistake](https://github.com/exercism/x-common/pull/713#pullrequestreview-26441727) from #713.
=> two-bucket: Fix exercise name in canonical data

exercises/tournament/canonical-data.json
=> tournament: Make exercise schema-compliant

exercises/phone-number/canonical-data.json
=> phone-number: Correct test to more-than check vs equal-to check

exercises/phone-number/canonical-data.json
There are two tests concerning 11 digit numbers.  One test says they are valid when the digits start with one.  The other test states that 11 digits is invalid, but doesn't state why.  The two tests seem to be contradicting each other.
=> phone-number: Clears up contradiction re: why 11 digits is invalid

exercises/simple-cipher/description.md
The example image for the [Simple Cipher][1] exercise is currently broken.
This PR replaces this broken link with a working one from [Caesar Cipher][2] Wikipedia page.
[1]: http://exercism.io/exercises/haskell/simple-cipher/readme
[2]: https://en.wikipedia.org/wiki/Caesar_cipher
=> Simple Cipher: Fix Broken Image

exercises/simple-cipher/description.md
=> simple-cipher: correct minor misspelling

exercises/triangle/description.md
I thought the description for triangle was a little wordy, so I shortened it.
Happy to revert on this if anyone thinks the text is not an improvement, but the line at the top:
> The program should raise an error if the triangle cannot exist.
should be changed, as not all languages would idiomatically raise errors in this case.
=> Simplify triangle description.

CONTRIBUTING.md, README.md
As discussed in #673, this PR adds the test data versioning policy to the README.
=> Add test data versioning policy to README.md

exercises/protein-translation/description.md
The URL link to wikipedia was missing a closing parentheses. This caused the link to incorrectly render.
=> Fix missing closing paren in protein-translation

exercises/flatten-array/canonical-data.json
I think it's always good to have test cases for the scenario where nothing needs to be done.
Like the empty string test case in other exercises, this new test case checks that a list without nested lists stays untouched.
=>  flatten-array: Add test case for no nesting

exercises/bracket-push/canonical-data.json
This helps cover broken stack-based implementations
=> bracket-push: add a test case

exercises/book-store/canonical-data.json
Sorry, for this micro change. I just couldn't resist. If all the other numbers have up to 2 trailing zeros ...
=> book-store: Add missing trailing zero

exercises/isogram/canonical-data.json
I used this exercise in an entry-level Python course and a participant
came up with the following attempt:
def is_isogram(s):
if s == '':
return True
t = s.lower()
for c in t:
if t.count(c) > 1:
return False
else:
return True
Note how the loop is unconditionally aborted after the first iteration.
However, all the test cases of the existing test suite run green with
this wrong solution.
The added test case fixes this, i.e. the above fails and the example
solution still succeeds.
=> Add negative isogram case where word starts with a unique letter

exercises/two-bucket/canonical-data.json
Adds one test where `goal == start_bucket` (one step)
and a second test where `start_bucket != goal_bucket`.
=> two-bucket: Add additional tests

exercises/crypto-square/canonical-data.json
The test case for the first `plaintextSegments` test case had a wrong type (string vs. array).
Let me know how it looks.
=> Fixed type of the first plaintextSegments test

exercises/phone-number/canonical-data.json, exercises/phone-number/description.md
Removes the part about how to test, as we have other docs for that. Now it also describes the telephone number system in a bit more detail.
Changes some test that used an invalid number but assumed it was valid.
Adds two tests that check the range of 2-9 for the first digit of the area and the exchange code.
Adds a test with a valid telephone number with country code and punctuation.
=> phone-number: Rewrite description and add tests

exercises/word-search/canonical-data.json
Closes #591.
Notes/thoughts:
- Single grid is used for all tests. The likelihood that a practitioner will hard-code the actual search logic in any way is low.
- Grid used for all tests matches the updated grid from the exercise `description.md`; Go track will need to update that to match this spec.
- Test cases for each of the 8 possible word directions are cumulative, which allows better matching of the problem statement ("given a puzzle and a list of words") and a more explicit prompt to "build up" the search capability piece-by-piece. All existing tracks would need to change to accommodate this new input structure, I believe.
Feedback welcome! 👂
=> word-search: add canonical data

exercises/clock/canonical-data.json
This PR does a cleanup of the canonical data of the `clock` exercise. It contains the following changes:
1. The word "Test" is removed from the test group descriptions, as that is superfluous (it is a test group description after all)
1. I've split the add and subtract test into separate groups. This makes things more sensible for test data generators.
I've bumped the PATCH version number, as I believe that according to the README, this qualifies as a patch version bump.
=> Cleanup canonical-data for clock

exercises/saddle-points/canonical-data.json
Closes #582.
Notes:
- Per https://github.com/exercism/discussions/issues/41, the row/column identification tests found in several tracks represent testing intermediate implementation details and should be removed.
- Larger matrices have been removed from the tests; they did not exercise anything that was not already covered (except possibly for differing matrix dimensions?)
- Readme example is included as the first exercise; the majority of tracks already test this and it's a nice start point.
- Empty example is included; only a few tracks currently test this, but it's a nice boundary case.
- Multiple saddle points test uses the more-common matrix as found in e.g. xcsharp. xpython and xscala will need to update their multiple saddle points tests.
- Example with saddle point in the lower …
=> saddle-points: add canonical data

exercises/scrabble-score/description.md
scrabble-score description contained some Ruby style symbols.
=> Remove Rubyism in description.

exercises/rail-fence-cipher/canonical-data.json
It doesn't seem to add value to state that these are tests! That should
be self-evidence from their presence in this file, no?
I don't have evidence that this a documented principle that MUST be
followed, nor do I have evidence that anyone is being hurt by the
presence of the words "test to", but I propose it to see what people
think.
=> rail-fence-cipher 1.0.1: Remove "test to" from all descriptions

exercises/phone-number/canonical-data.json
> Your task is to clean up differently formated telephone numbers by removing punctuation and the country code (1) if present.
Letters are not punctuation and this is not primarily a string parsing exercise.
So remove the test using `1a2b3c4d5e6f7g8h9i0j` as input.
=> phone-number: Remove test using malformed input.

exercises/tournament/canonical-data.json, exercises/tournament/description.md
The previous version of these tests "threw you in at the deep end." and expected you to have a fully formed solution immediately.
This PR adds a series of smaller, simpler tests that can be incrementally passed while building up to a full solution.
Included: Removal of test for malformed input data.
This is not a problem about string parsing, so it is OK to expect that all test input will be valid.
=> tournament: Start with simpler tests / remove invald input test.

exercises/kindergarten-garden/canonical-data.json
Closes #565
Notes:
- The default students indicated in the README are assumed, and alternate students are indicated as input when appropriate.
- While some tracks tested all 12 students for the full garden, it only seemed necessary to include a few tests here.
=> kindergarten-garden: add canonical data

CONTRIBUTING.md
https://github.com/exercism/configlet/pull/13 added support for track configurable example solution patterns.
This PR documents the usage of that key in `config.json`
=> Document the config.json `solution_pattern` key.

exercises/dominoes/canonical-data.json
There have always been nine elements, ever since the origin of this test
in https://github.com/exercism/xrust/pull/13#discussion_r115148635
The description incorrectly claimed ten.
=> dominoes 1.0.1: correctly declare nine elements in largest case

exercises/robot-name/description.md
The previous description of this problem was unclear about 
This patch removes the ambiguity by clearly stating that "every existing robot has a unique name."
This PR is an alternative to #748 which seeks to make the name uniqueness an extension,
and https://github.com/exercism/x-common/issues/731 which proposes removing it completely.
(commits can be squashed.)
=> Robot name uniqueness clarification

TRACK_MAINTAINERS.md
https://github.com/exercism/discussions/issues/97 investigated the status of all Exercism language tracks. This file is intended to continue and maintain that process in a community driven manner.
My intention is for this version to be merged and then further PR's can fill out/update the rest of the information.
See "Ruby" under the "Maintained" section for an example of what information I think there should be for each track.
Ideally a bot could keep it updated, but until someone writes one we will just have to do it manually.
=> Add a file to keep track of track maintainers.

exercises/difference-of-squares/canonical-data.json
See #789.
Zero is by some definitions regarded as a natural number, so an implementation should be able to handle this case, as well as the edge case of 1.
Summary of changes:
- Add tests for edge cases 0 and 1
- Remove test for input 10 (there are tests for 5 and 100 and if the implementation works for these numbers, it most likely also works for 10)
- Bump version number of the test suite to 1.1.0
I think the [description](https://github.com/exercism/x-common/blob/master/exercises/difference-of-squares/description.md) is ok, no need to include 0 there as it has anyway no influence on the result.
=> difference-of-squares: add tests for boundary cases

exercises/poker/canonical-data.json
=> Add canonical-data for poker

exercises/acronym/canonical-data.json
Closes #787.
Remove the `HyperText Markup Language` test case from `acronym` so that there are no mixed-case (camel-case) test cases in this exercise.
Version number of test suite bumped to 1.1.0.
=> acronym: remove test case with mixed-case phrase

exercises/acronym/description.md, exercises/binary/description.md, exercises/bowling/description.md, exercises/change/description.md, exercises/connect/description.md, exercises/dot-dsl/description.md, exercises/error-handling/description.md, exercises/flatten-array/description.md, exercises/food-chain/description.md, exercises/forth/description.md, exercises/grade-school/description.md, exercises/hello-world/description.md, exercises/linked-list/description.md, exercises/list-ops/description.md, exercises/markdown/description.md, exercises/minesweeper/description.md, exercises/paasio/description.md, exercises/pig-latin/description.md, exercises/pov/description.md, exercises/scale-generator/description.md, exercises/simple-cipher/description.md, exercises/simple-linked-list/description.md, exercises/twelve-days/description.md
In #775 the first line of the description (which is/was the blurb.) was sometimes missing a
period.
This PR adds periods in the appropriate places.
This no longer exactly matches the output of the old readme, but makes the
description more grammatically correct.
=> Add period to end of first description line.

exercises/two-fer/canonical-data.json, exercises/two-fer/description.md, exercises/two-fer/metadata.yml
This is meant to be right after hello-world introducing users to basic
programming constructs as well as TDD which will be used in all later
exercises.
Discussion regarding this is [here](https://github.com/exercism/x-common/issues/548).
Closes #757.
=> Implement the two-fer exercise

CONTRIBUTING.md
Referencing issue [#27](https://github.com/exercism/docs/issues/27) in docs repo.
Hello. I deleted the track-level linting guidelines from CONTRIBUTING.md. However, this time, I did not remove the header and instead added a link to the [maintaining-a-track/](https://github.com/exercism/docs/tree/master/maintaining-a-track) directory in the docs repo as placeholder.
=> Moved track-level linting with configlet guidelines

exercises/secret-handshake/canonical-data.json
I saw a solution which just returned an empty list for all numbers >= 32. This is obviously wrong, as the 5 least significant bits should define the sequence of signals, no matter how large the number is. However, the current test suite tests only 32, and so all the tests passed for this solution.
I added therefore a couple of test cases for numbers > 32.
Not sure if the problem description should also be updated to make this clearer.
=> secret-handshake: remove tests for numbers > 31

CONTRIBUTING.md
This was about how to extract canonical data. The [improving consistency across tracks](https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/improving-consistency-across-tracks.md) document now covers both extracting and using canonical data.
=> Delete documentation about canonical data

CONTRIBUTING.md
This has been moved and elaborated upon in https://github.com/exercism/docs/pull/35
I've more or less rewritten the entire doc, as there was a fair amount of outdated and confusing information both here in the contributing guide and in the "fixing exercise readmes" document.
=> Delete documentation about updating exercise READMEs

exercises/twelve-days/description.md
The fenced code block does not contain Ruby.
Matters because some editors highlight the content of fenced code blocks, and you get `true`, `in`, and others colored.
=> Remove "ruby" from fenced code block

exercises/proverb/description.md
Fixes proverb lines not rendering with newline separators; adds quote formatting to proverb.
=> proverb: fix description formatting

exercises/dominoes/canonical-data.json
It was "can-chain", but most other exercises have "expected" as the expected output of a property being tested.
=> Update dominoes canonical-data expected key

CONTRIBUTING.md
This has been moved and elaborated upon in
https://github.com/exercism/docs/tree/master/maintaining-a-track
> Maintaining a language track generally consists of [...]
This is under "perform common tasks" at the bottom of the README:
https://github.com/exercism/docs/tree/master/maintaining-a-track#perform-common-tasks
> Ideally a track will have several maintainers, for two reasons [...]
I've opened an issue for this, since I don't think it belongs in the maintainer docs (exercism/docs#21).
> Reviewing/Merging Pull Requests [...]
Some of this is in the README (under "Collaborate"), some of it is fleshed out in its own document:
https://github.com/exercism/docs/blob/master/maintaining-a-track/reviewing-a-pull-request.md
The "use branches" and "claim issues" bit is summarized under …
=> Delete documentation about maintaining a track

CONTRIBUTING.md
This has been moved and elaborated upon in
https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/porting-an-exercise.md
=> Delete documentation about porting exercises

CONTRIBUTING.md
Referencing issue [#24](https://github.com/exercism/docs/issues/24) in [docs repository](https://github.com/exercism/docs).
I've deleted the PR guidelines portion from CONTRIBUTING.md as they are planned to be moved to the docs repo.
=> Moved documentation on pull request guidelines

exercises/all-your-base/canonical-data.json
Both [xjava](https://github.com/exercism/xjava/issues/519) and [xcsharp](https://github.com/exercism/xcsharp/pull/178#issuecomment-308018694) ran into issues regarding input validation for this exercise. In particular, when writing a test that verifies an initial base of 1 is invalid, it's unclear what the initial list of digits should be:
```
const int inputBase = 1;
var inputDigits = new[] {}; // inputDigits is also invalid; which error should we throw...?
```
```
const int inputBase = 1;
var inputDigits = new[] {0}; // an argument could be made for this combination being a valid representation of 0...
```
```
const int inputBase = 1;
var inputDigits = new[] {0, 1}; // inputDigits is also invalid; which error should we throw...?
```
This was exacerbated by the ordering of the current …
=> all-your-base: update test case ordering

exercises/bowling/canonical-data.json
Make the usage of _can not_ and _cannot_ consistent throughout the file. Also add a missing `more` in one of the descriptions.
Since these changes are mostly cosmetic, I am not sure if a patch-level bump to the `version` key is required here. Please tell me if that is the case, so I can update it accordingly.
=> bowling: Make descriptions consistent

CONTRIBUTING.md
It looks like the URI changed for each language repo. This PR changes the link in CONTRIBUTING.md to follow that convention instead of relying on GH to redirect us
=> Change CONTRIBUTING to link to correct lang repos

exercises/rna-transcription/canonical-data.json
Because RNA & DNA are biochemically defined abbreviations, they should not be in lower-case, unless there is a technical reason (like in `property` fields or in slugs).
=> rna-transcription: correct abbreviations in user-facing descriptions

exercises/phone-number/description.md
The formatting of this example was wonky, and the example was unclear as a result.
Also includes a couple other misc. formatting fixes.
=> phone-number: clarify README example

exercises/collatz-conjecture/canonical-data.json
Super small change, but I noticed this is screwing up some test generators
=> Collatz-conjecture: remove trailing space in test name

exercises/pangram/canonical-data.json
From what I can see, the last test case is inteded to catch incorrect
programs such as this, which don't take into account different-cased
duplicates:
```haskell
isPangram = (== 26) . length . nub . filter isAlpha
```
However the above program passed the final test as the count of distinct
upper and lower case characters is 27, rather than 26.
This commit changes the test text to a non-pangram that has exactly 26
distinct upper and lower case characters, which causes the above,
incorrect program to fail.
Similar incorrect programs that checked if the count of distinct letters was >=, rather than exactly = to 26, would have correctly failed the existing test.
=> fix pangram test for duplicate mixed-case chars

exercises/forth/canonical-data.json
I think it's a reasonable edge case that's not covered by the existing tests.
=> Add test for Forth that an operator can be overridden.

exercises/pangram/description.md
An update for https://github.com/exercism/problem-specifications/issues/842. Clarifies that non-ASCII symbols should not be present at all, compared to them being present, but ignored.
=> pangram: character set issue, closes #842

CONTRIBUTING.md
I want to resolve [#26](https://github.com/exercism/docs/issues/26) in the docs repo with this PR. 
This will remove the Anatomy of an Exercise section (keeping the heading) that will be moved to the docs repo. Also, I added a (currently broken) link to what I assume will be the new location in the docs repo.
=> Moved anatomy of an exercise from CONTRIBUTING.md to docs repo

CONTRIBUTING.md
The word `and` is not needed in the sentence.
=> fix grammar error

exercises/list-ops/canonical-data.json
Closes #826.
Note that I bumped the major version of the tests since this is a breaking change; the representation of the accumulation function used in the fold tests was changed to highlight that the _same_ function is being used in the direction-dependent tests. This should help mitigate confusion regarding what is meant when we declare that the given accumulation function is 'direction-dependent'. See e.g. https://github.com/exercism/java/pull/671#discussion_r125188010 for context.
Questions:
- when writing `x / y`, is there a common way to indicate that this represents integer division in particular? I think that would be useful for implementors.
- would it be useful to include a link to https://en.wikipedia.org/wiki/Fold_(higher-order_function)#Linear_folds to help implementors …
=> list-ops: update foldl/foldr tests

exercises/rotational-cipher/canonical-data.json
Rotating by 0 seems to be an easier starting point that rotating by 1, and leads to more of a natural progression (rotate by 0 -> 1 -> 26, rather than 1 -> 26 -> 0).
=> rotational-cipher: improve test case order

TOPICS.txt
Related to the "Security" topic, but more specific (accurate?), would apply to
atbash-cipher, rotational-cipher and simple-cipher among others.
=> topics: add cryptography

CONTRIBUTING.md
I reorganized things in the docs repository, and checked the track documentation for broken links
but forgot to check the problem-specifications repo.
=> Fix link to moved content

exercises/accumulate/description.md
Elixir-specific portion added:
https://github.com/exercism/exercism.io/pull/1136
Lisp-specific portion added:
https://github.com/exercism/problem-specifications/pull/98
Elixir-specific portion removed because the `Enum.reduce` was not
necessary:
https://github.com/exercism/problem-specifications/pull/274
The reason to suggest removing this Lisp-specific now is slightly
different:
It doesn't seem to make much sense to include this Lisp-specific
sentence in non-Lisp tracks.
See that http://x.exercism.io/problems/accumulate indicates this
exercise is only implemented by one Lisp-like language (Clojure) and 19
non-Lisp-like languages.
It could be possible for the tracks that desire this clause to place it
in .meta/HINTS.md. It is easy to **add** content to the description.md,
but it is not …
=> accumulate: remove Lisp-specific portion

exercises/hamming/canonical-data.json
=> Hamming: Updates canonical-data.json to comply with schema

exercises/space-age/description.md
Inspired by https://github.com/exercism/kotlin/pull/100.
Consistent with the rounding policy used by the [canonical data](https://github.com/exercism/problem-specifications/blob/281497b21dd032fbf22449dc82272df74f026305/exercises/space-age/canonical-data.json).
=> Note expected accuracy in space-age description

exercises/two-fer/canonical-data.json
I'd like to propose to rename the twofer property to instead use name. I noticed this because the C# track really can't follow the canonical data. 
For this exercise, following proper casing and convention, the call becomes TwoFer.TwoFer() which isn't legal as the method matches the name of the class.
=> Rename twofer property to name

exercises/change/canonical-data.json
I'd like to propose adding a missing edgecase test. This test invalidates an incorrect greedy algorithm which takes as many of the larger coins as possible as long as the remainder is greater than or equal to the value or the smallest coin. Currently such an algorithm will pass all of the tests.
If required, I can point to some solutions which fail this test.
=> Change: Add test for incorrect greedy algorithm

TOPICS.txt
Moved "reactive programming" to its own section along with
alternatives like OOP and functional. Added two test styles
test driven development and behavior driven development.
These all have a place in the exercises. "functional programming" will
hopefully replace a the higher-order functions topics and functional in dlang
and ocaml.
TDD is a lot of what Exercism does. I propose to limit it to the
exercise that benefit specifically from incremental development like
[sum-of-multiples](https://github.com/exercism/problem-specifications/tree/master/exercises/sum-of-multiples). That
being said, should a track use BDD that should be available in TOPICS as well.
See #884
=> topics: "style" category & entries

TOPICS.txt
See https://github.com/exercism/meta/issues/83#issuecomment-324048581
From that conversation...
@robphoenix
> Be good to also consider what to do with topics such as Control-flow (conditionals) - control_flow_(conditionals) or control_flow_conditionals?
@ihiD
> For "control_flow_conditionals" can we just have "conditionals" please?
@kytrinyx
> I think it's worth sorting this out at the TOPICS level. Configlet could do it, but it would seem more like a dark art if it's not listed the way we want it up front.
=> Simplify control flow topics

exercises/circular-buffer/canonical-data.json, exercises/circular-buffer/description.md
This pull request is in two pieces in case the change to the test cases is controversial.
The description change is to make overwrite clear for the reader. To this end another example is added and that there is a difference in behaviour when the buffer is not full.
In the test cases descriptions I exchanged the word "replace" for the word "remove". This should add clarity especially for the readers who are not native English speakers.
=> circular-buffer: Clarify overwrite

exercises/word-search/canonical-data.json
As I mentioned in #898, the goal of the PR is to improve the canonical cases to better support a test-driven approach to solving this problem:
1. The current test suite ramps up very abruptly, requiring the user to solve a significant portion of the problem just to get started.
2. The steps between each canonical case are large relative to the scope of the problem.
3. The cases could better telegraph the desired pattern of inputs and outputs, encouraging small steps forward.
4. There are unnecessary assumptions baked in, EG that the grid is 10x10, that the grid never changes, etc.
Most of the changes here are new tests, although there are a few existing tests that have been moved or slightly modified.
=> Word-Search: Add tests to support TDD workflow

README.md
`npm test` will work as described, because it's an alias for `npm run test`, but `test-one` requires the user to type `npm run test-one`
I realized this when (after making my last PR) I read the docs for the repo  ☺️
=> Correct `test-one` instructions in README

exercises/palindrome-products/description.md
REF exercism/ruby#305
REF exercism/ruby#723
It's not clear from the current examples what the requirements of this exercise are.  In fact, a furtive glance is more likely to cause confusion than give clarity.
In my opinion, this is because for the first example the solution lies within the range of the list of factors, giving on a first impression that we are looking for products that lie within this range.
I think that by listing out the entire list of products (which is small in the case of the range of 1..9) we make it more clear that we are considering all the results.
=> palindrome-product: Clarify requirements

exercises/sum-of-multiples/canonical-data.json
I'd like to propose adding an additional test case to this exercise (as well as simplify the earlier ones). I believe these test cases would be a more logical approach when tackling this problem using TDD.
Currently, for the 3rd step, it takes a bit of a leap. It's the first time we actually have to worry about the 5 (since in previous cases it could never be possible) as well as having to sum 3 multiple times to return a result of 23. 
This new test case is a little more gentle in the sense that we don't need to worry about another factor, we just need to worry about 3 + 6.
After that, we can introduce 5 (and other factors) because the student should have accomplished summing 3 multiple times, allowing them to move onto a test case that leverages multiple factors.
=> sum-of-multiples: Add up to 7 test case

exercises/protein-translation/description.md
Corrected "four stop codons" to "three stop codons" as described in issue #810
=> protein-translation: Update description.md with correct fact as in #810

exercises/nucleotide-count/description.md
I have tried to be more precise, specific and accurate.
I am not sure what you are trying to accomplish with this description, so please let me know if you need any further help if the description expands.
=> nucleotide-count: Refactoring the description

exercises/bowling/description.md
The paragraphs rambled without newlines. They are now line wrapped to match
the other exercises.
There was a missing article 'a' in the beginning. The phrasing "after the
throw" is a little confusing. Does this mean either the 2nd or 3rd throws?
No, it means they are knocked down by THIS throw. Update accordingly.
=> Bowling: wrap paragraphs and fix some minor grammar

exercises/nucleotide-count/description.md
In #913 the description of DNA was made more scientifically accurate.
However the reference to RNA is not relevant to this problem and is likely to cause confusion, so I have removed it from the description.
=> nucleotide-count: Remove reference to RNA from description

CONTRIBUTING.md
Closes: #914 
Note that the readme.md the new link points to is not complete.  It would be nice to know what happened to the old doc that the broken link pointed to.  Could that old doc be used to fill in missing information in the incomplete readme.md?
=> contributing.md: fix broken link

exercises/dot-dsl/metadata.yml, exercises/etl/metadata.yml, exercises/ocr-numbers/metadata.yml, exercises/pascals-triangle/metadata.yml, exercises/pov/metadata.yml, exercises/rna-transcription/metadata.yml, exercises/sgf-parsing/metadata.yml
In generated READMEs, the rule for converting an exercise slug to a
human-readable form is to capitalise only the first letter of each
hyphen-separated word. For example, `lorem-ipsum` will become "Lorem
Ipsum". This is true of both the Trackler and Configlet README
generators.
Trackler's README generator (see `name` function):
https://github.com/exercism/trackler/blob/master/lib/trackler/specification.rb
Configlet's README generator (see `Name` function):
https://github.com/exercism/configlet/blob/master/track/problem_specification.go
For some exercises this is not the best possible title. For example see
http://exercism.io/exercises/haskell/rna-transcription/readme and
observe that the title is "Rna Transcription", whereas "RNA
Transcription" seems more faithful to the rules (RNA, as an …
=> Add titles to exercises with non-default capitalisation/punctuation

exercises/isogram/canonical-data.json
Changed test description "isogram with duplicated non-letter character" to "isogram with duplicated hyphen", and changed the associated canonical data from "Hjelmqvist-Gryb-Zock-Pfund-Wax" to "six-year-old". This was suggested in issue #919.
=> isogram: Update canonical-data.json as in #919

exercises/crypto-square/canonical-data.json
We want to remove tests of intermediate functions in crypto-square that pry into implementation details per these issues:
- https://github.com/exercism/discussions/issues/41
- https://github.com/exercism/ruby/issues/422
This rewrites the canonical data for crypto-square so that we're only testing the expected value of the final "ciphertext" property and none of the intermediate properties.
=> crypto-square: Don't test intermediate functions

exercises/lens-person/description.md
Changed spelling from "alltogether" to "altogether" This is my very first contribution to anything, anywhere so be gentle.  I'm still learning github and git.
=> lens-person: fix minor typo in description.md

exercises/isbn-verifier/canonical-data.json, exercises/isbn-verifier/description.md, exercises/isbn-verifier/metadata.yml
This was an starter exercise in my CS class.
The exercise is really simple, depending on how much your language supports converting types and string manipulation but it can be blown up into a full grown exercise with the bonus tasks.
This teaches you some simple string manipulation combined with basic numerical calculations.
You also get to use the three datatypes of number, string and bool.
=> Add isbn-verifier exercise

exercises/robot-simulator/canonical-data.json
Closes #722.
I decided to use objects. Some people preferred arrays and some people preferred objects, but it seems like in other problems objects were preferred because they were more explicit (see #721). I don't believe we have a policy yet on whether to use arrays or objects for things like this, but I believe that objects would be a better decision. There are some situations in which it doesn't really matter and some people would prefer arrays, but there are some situations where it really would be better to have objects. Since it sometimes is desirable to have objects and only sometimes slightly preferred to have arrays, I think objects are a better default policy.
=> robot-simulator: encode position as object instead of string

exercises/sum-of-multiples/description.md
Basically what the title says. I stumbled across the duplicated sentence while doing the exercises. I was sent to this repo from my first [PR](https://github.com/exercism/rust/pull/358) in the rust repo.
=> sum-of-multiples: Removed a duplicated sentence in README

exercises/two-bucket/canonical-data.json
=> two-bucket: fix incorrect test case

exercises/queen-attack/canonical-data.json
Closes #721.
I decided to use objects, since it seems like most people were agreeing it was more explicit. I will also be using objects to encode the position for #722, which is deals with a similar issue.
=> queen-attack: represent positions as objects

exercises/zipper/canonical-data.json
Closes #593.
Of the five tracks that had already implemented this exercise, five had the exact same test cases, and the other two had the same test cases plus a few more (identical) test cases. I opted to simply list all of the test cases I found in the order they were in.
I ran the test against the `canonical-schema.json` and it said the file is valid.
=> zipper: add canonical data

exercises/nucleotide-count/canonical-data.json
Splitting #895 into single PRs.
Adding a single char input case for better TDD progression as agreed upon by @petertseng (https://github.com/exercism/problem-specifications/pull/895#pullrequestreview-69117017) and @Insti (https://github.com/exercism/problem-specifications/pull/895#discussion_r139292551)
=> nucleotide-count: Adding a single character case

exercises/markdown/canonical-data.json
Compare the case of "unordered lists" vs "With a little bit of
everything":
In the former, each list item is surrounded by `<p>` tags.
In the latter, they are not, instead being surrounded by other tags that
they otherwise had.
This could plausibly be explained by the rule "If there are any tags on
list items, don't add any, otherwise do add `<p>`" but it seems weird
because we don't usually see `<p>` for list items.
On a survey of two arbitrarily chosen Markdown parsers:
* http://parsedown.org/demo
* https://daringfireball.net/projects/markdown/
Neither emits `<p>` for the list items.
It seems they were a mistake and should be removed, unless information
to the contrary is reported at
https://github.com/exercism/problem-specifications/pull/262#discussion_r144485967
=> markdown: Do not add <p> to list items

exercises/pangram/canonical-data.json
Splitting #893 into single PRs.
Adding case with a "perfect pangram" for better TDD progression.
As suggested by ~~@petertseng (https://github.com/exercism/problem-specifications/pull/893/files#r144452355) and~~ @Insti (https://github.com/exercism/problem-specifications/pull/893#discussion_r137843067)
Edit: The suggestion from @petertseng above does not count towards this, because I misunderstood it for another issue.
=> pangram: add a case with a perfect pangram for better TDD progression

exercises/space-age/description.md
This reverts commit 7eb0dc966d843d74329c6d6475ea90a14fff440b.
In https://github.com/exercism/problem-specifications/pull/880 we
discussed that tracks may need to use a tolerance in their floating
point comparisons.
In light of this, asking students to round the answer seems strangely
arbitrary and theoretically doesn't prevent the need for having a
tolerance. Despite this, I do not currently have an example where
lacking a tolerance would have a false negative or false positive if a
floating point literal of two decimal places is compared to a value that
was rounded to two decimal places. So, then, the primary motivation is
to avoid adding requirements whose reasons are unclear.
Thus, remove the sentence completely. Tracks should add it if it is
relevant for their track.
Closes …
=> space-age: Revert "Note expected accuracy in space-age description"

exercises/crypto-square/description.md
The final example in the crypto-square description is inconsistent with the source of the exercise, the canonical data, and itself. This change does a few things to correct that:
- While the encoding method is called a "square code," we're really dealing with all sorts of rectangles, squares included. The description gets this right up until the copy before the last example, and this change clarifies that.
- In both the [source of the exercise](http://users.csc.calpoly.edu/~jdalbey/103/Projects/ProgrammingPractice.html) and [the canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/crypto-square/canonical-data.json#L47), when a "chunk" is shorter than the length of a row, a blank space is added to the end of that chunk. This change fixes that in the …
=> crypto-square: Fix description copy and example

exercises/crypto-square/canonical-data.json
This cleans up a few things about crypto-square's canonical data that I thought were worth addressing before I generated new tests in the Ruby repo to address https://github.com/exercism/ruby/issues/422.
- Removes unnecessary sub-groupings of test cases ([related discussion](https://github.com/exercism/problem-specifications/pull/922#discussion_r142604966))
- Moves the blank string test case to the top since it feels like the simplest one to get passing using TDD
- Adds a new test case
=> crypto-square: Improve test data

exercises/leap/canonical-data.json
Currently, the test suite has a loophole where it is possible to pass
all the tests with a function that simply checks if the year is evenly
divisble by 16.
This commit changes one of the test cases so that is no longer possible.
=> leap: Improve test suite to cover corner case.

exercises/hamming/canonical-data.json
I feel like the cases `"non-unique character in first strand"` and `"non-unique character in second strand"` are not clear in how the respective strand has a non-unique character.
So I suggest simplifying it. Otherwise, I would be fine with switching them as seen below. Where it's clear by the pattern of the other strand that the strand with the non-unique character doesn't follow the expected pattern.
```json
{
"description": "non-unique character in first strand",
"property": "distance",
"strand1": "AGG",
"strand2": "AGA",
"expected": 1
},
{
"description": "non-unique character in second strand",
"property": "distance",
"strand1": "AGA",
"strand2": "AGG",
"expected": 1
},```
=> Simplify two tests so the difference is easily spotted.

exercises/nucleotide-count/canonical-data.json
For whatever reason, in #951 I added the single-char-input case after the multi-char-input case.
Obviously this is bonkers and needs to be the other way around.
=> nucleotide-count: fix wrong order introduced in #951

exercises/pangram/canonical-data.json
Splitting #893 into multiple PRs.
Currently two cases check for a missing 'x'. This does not make much sense and the second case was changed to test for a missing 'h' instead, while 'h' was chosen randomly.
This improves the TDD progression and forces the user to check for more than just 'x'.
=> pangram: fix duplicative case for a missing 'x'

exercises/kindergarten-garden/canonical-data.json
Adds a disclaimer in Kindergarten-garden that names of students may differ.
Completed Issue #659.
Edit: 
There has been further discussion about what needs to happen to this problem so this PR has changed from its initial version.
The current proposal is to remove the tests for different student names. These are not specified in the description which is otherwise explicit about the names and ordering of students in the class.
Closes #659
=> kindergarten-garden: Remove tests not specified in the description

exercises/saddle-points/description.md
I noticed a small typo in the description for `saddle-points`. This PR fixes the error.
=> saddle-points: Remove extraneous 'the' from description

exercises/leap/canonical-data.json
Currently, it's possible to pass all the unit tests by checking if `(year % 100) == (year % 400)`.
This commit changes one of the test cases so that this is no longer possible. Note that this is a separate issue to #955 -- however, 1996, like 2020, is not divisible by 16, so that loophole will remain closed.
=> leap: Fix loophole in unit tests

exercises/nth-prime/canonical-data.json
This is more in line with how other exercises indicate error cases.
=> nth-prime: Use object instead of bool for invalid value

exercises/zebra-puzzle/canonical-data.json
Closes #592 
There isn't much to do on this one since there's only one static answer. But I figured I would include it for completeness.
=> zebra-puzzle: add canonical data

exercises/dominoes/description.md
Rework domino representation to avoid confusion with 2-digit numbers `23` vs. a domino `(2, 3)`.
=> dominoes: improve description readability

exercises/zipper/description.md
The adjective phrase "purely functional" should go before the noun "way" in this sentence.
=> zipper: fix word order in description

exercises/custom-set/canonical-data.json
Consider the following pseudocode
```
equals(self, other)
if self.empty
return other.empty
else
for x in self
if !other.contains(x)
return false
return true
```
This solution would return a false positive for [1, 2, 3] == [1, 2, 3, 4], but would pass all other tests for `equals`.
=> custom-set: add test for inequality of subset

exercises/isbn-verifier/canonical-data.json
isbn-verifier 1.1.0
"X is only valid as a check-digit"
https://github.com/exercism/problem-specifications/pull/924#discussion_r148174550
An implementation that unconditionally treats X as 10 will still reject
the ISBN 3-598-2X507-0
3 * 10 + 5 * 9 + 9 * 8 + 8 * 7 + 2 * 6 + 10 * 5 + 5 * 4 + 0 * 3 + 7 * 2 + 0 * 1 = 299,
and 299 is not divisible by 11.
If the intention of this test is to ensure that an implementation only
treats X as 10 in the check digit position, then a case such as
3-598-2X507-9 is needed.
The following may be run in a terminal to ensure that this ISBN does sum
to 10 under such a mistaken implementation:
ruby -e 'p "3-598-2X507-9".delete(?-).chars.reverse.map.with_index { |c, i| (c == ?X ? 10 : Integer(c)) * (i + 1) }.sum % 11'
"too long isbn" …
=> isbn-verifier: Test only the fact that each case claims to test

exercises/twelve-days/canonical-data.json
------
Resolves #590 // m-a-age
=> twelve-days: Implement canonical-data.json

exercises/food-chain/canonical-data.json
Currently, the canonical data uses the same property to get a single verse and to get multiple verses. I think it would make sense to instead use a different property for multiple verses, aptly named `verses` (plural). 
Furthermore, the single verse cases used `"start verse"`  as the input property, but to me that suggests also having an `"end verse"` property, which it doesn't. I've therefore renamed the property for the single verse cases to just `"verse"`.
=> food-chain: Make properties less ambiguous

exercises/house/canonical-data.json, exercises/house/description.md
=> house: Update to test property recite

exercises/two-bucket/description.md
The description currently specifies that buckets are represented, in
both the input and the output, as strings.
This seems overly constraining. Consider those tracks that wish to
represent these buckets as variants of a tagged union or of an enum for
the purpose of better type safety. These tracks have these options in
order to do so:
* Accept the problem-specifications README as is, but act in
contravention of it. But it is confusing if the README contradicts the
tests.
* Create a custom description.md. But this is a little unfortunate
because only two lines need to change, and it adds extra maintenance
burden to have to maintain the custom description.md. Consider that if
this description.md changes, the changes will probably need to be
copied to each custom description.md
* Add to …
=> two-bucket: Do not specify any types in description

exercises/kindergarten-garden/description.md, exercises/nucleotide-count/description.md, exercises/palindrome-products/description.md, exercises/rectangles/description.md
One might assume that we can consider a CI check that there are no
trailing spaces, but we have to be careful because some embedded strings
that serve as example outputs are expected to have trailing spaces. The
currently only example is ocr-numbers. One might consider a CI check,
but simply exclude that file.
=> description.md: rm trailing spaces

exercises/proverb/canonical-data.json, exercises/proverb/description.md
This is based on the Rust tests as implemented in exercism/rust#380.
The lack of canonical data had resulted in odd custom tests being
designed, which was reported in exercism/rust#379.
Closes #578.
=> proverb: Add canonical data.

exercises/forth/canonical-data.json
~~This PR adds a new test designed to check that an empty line (represented by an empty string) is handled/ignored and leaves the stack empty without failing.~~
This PR removed the test for empty input `[]` in line with the discussion below. This test was considered to be unexpected for the current problem description.
=> forth: Remove test for empty input

exercises/meetup/description.md
Clarify the problem description for meetup.
This PR is made up of several commits:
* Enumerate valid descriptors.
* Lowercase '*teenth' descriptors.
* Add description of what to do if there is no date.
* Note that all descriptions will be valid.
* Make descriptions consistent.
* Reformat text to fit in 80 columns. 
The goal here is to make the description less ambiguous by explicitly stating the expected date specifier strings and what to do if there is no matching date.
A consistent format for the input date specifications and only testing against valid input strings helps ensure that this remains a problem about date parsing rather than arbitrary string parsing.
The final commits reformat the text to 80 columns for consistency with other exercise descriptions.
=> meetup: Clarify description

exercises/sum-of-multiples/description.md
Changes for Issue exercism/rust#360
=> Sum-of-multiples: Add information to the description.

exercises/protein-translation/canonical-data.json
Add protein translation canonical data as per #577.
After going to implement this exercise in Java, and realising that there is not a `canonical-data.json` for the problem, I decided to do this. I have helped a friend complete this exercise on the Python track, and believe the Python tests to be very comprehensive, so I have used them as my main source of data.
Please let me know if this is too long for a `canonical-data.json`, as there are about 20 tests...
=> protein-translation: Add canonical data.

exercises/forth/canonical-data.json
This PR add tests for case insensitivity to `forth` to better match the problem description. Previously there was some testing for case-insensitivity, but it was limited to `dup` - I have removed this in favour of a block of tests for each word and type of word at the end of the canonical data.
I'm not sure whether "copies a value on the stack" on line 152 is really necessary - I'm happy to remove it if so desired.
The updated version number assumes the merge of #976 (removal of the empty test case `[]`) before this one.
=> forth: Add tests for case-insensitivity

exercises/all-your-base/canonical-data.json
all-your-base 2.0.0
In https://github.com/exercism/problem-specifications/pull/280 we made
the explicit choice to leave various cases `expected: null` where tracks
can make their own decisions (leading zeroes, the representations of
zero, whether empty sequence is acceptable as input).
There are four affected cases.
https://github.com/exercism/problem-specifications/issues/473 results in
a discussion that some post-processing is necessary, based on the
decisions that a given track makes. One might even imagine that each
individual generator may have to reimplement base translation to arrive
at the proper answers for each case.
To ease the process of translation, instead we make some canonical
choices, explicitly show what the choices are, and offer that tracks may
make a different choice …
=> all-your-base: Be decisive about zeroes

exercises/all-your-base/canonical-data.json
all-your-base 2.0.0
This uses the error object defined in
https://github.com/exercism/problem-specifications/issues/401#issuecomment-274395645
and thenceforth added to the README's **Test Data Format**.
In https://github.com/exercism/problem-specifications/pull/280 we made
the explicit choice to leave various cases `expected: null` where tracks
can make their own decisions (leading zeroes, the representations of
zero, whether empty sequence is acceptable as input).
However, since `expected: null` is also used for cases where there is
always an error (and there is no decision being left to the tracks),
it becomes unreasonably hard to tell cases in these two categories
apart.
To make this easier, all cases in the latter category (always are
errors) can canonically be marked as such.
=> all-your-base: Be explicit about error cases

exercises/isbn-verifier/canonical-data.json
The existing property does not really indicate that any validation occurs. This PR changes the property to better represent validation being done.
=> isbn-verifier: Rename property

exercises/all-your-base/canonical-data.json
The input/output bases are not positional. It would make more sense for the descriptions to refer to them explicitly, rather than an assumed order.
=> all-your-base: replace 'first' and 'second' with 'input' and 'output' in descriptions

exercises/reverse-string/canonical-data.json
All the case in the reverse-string canonical data start with "a ...", expect for the first case. To make this more consistent, I propose to change "empty string" to "an empty string".
=> reverse-string: More consistent canonical data descriptions

README.md
=> README.md: Document expected use of lowerCamelCase

README.md
Minor grammatical corrections.
Closes #1010
=> README.md: grammar corrections

exercises/pov/description.md
I noticed that there is an extra top-level heading in the `description.md` that I don't think should be there, so this PR removes it.
=> pov: Remove extraneous heading

exercises/simple-cipher/description.md
I noticed a few language-specific phrases in the `simple-cipher` description, so this PR removes them.
I'm more than happy to take suggestions on the replacement wording.
=> simple-cipher: Replace language-specific wording

exercises/protein-translation/canonical-data.json
I noticed there was some redundancy in the test names - removed it :slightly_smiling_face:
=> protein-translation: Remove repetition from canonical data

exercises/isbn-verifier/description.md
=> isbn-verifier: Include more succinct description of ISBN-10.

exercises/book-store/canonical-data.json
In the Rust track, @shybyte [implemented a very simple solver](http://exercism.io/submissions/9ede17337e074a108c69d767caa3ea79) for this problem which looked like it shouldn't work, but passed all existing test cases, and then requested my input.
I came up with a case which correctly failed their implementation. This PR adds that case to the canonical data.
=> book-store: Add test case requiring two moves to solve correctly

exercises/word-count/canonical-data.json
=> word-count: Add test for multiple whitespace

exercises/bob/canonical-data.json, exercises/bob/description.md
closes #943 
This first commit adds a description for an emphatic question.  The second commit will update the `forceful question` case with the new response I am proposing in the description.
=> Bob: Add fifth rule

exercises/armstrong-numbers/canonical-data.json, exercises/armstrong-numbers/description.md, exercises/armstrong-numbers/metadata.yml
How is this for a first draft on #1017 ?
Closes #1017.
=> armstrong-numbers: new exercise

exercises/rna-transcription/canonical-data.json
closes #977 
Replacing expected value of `null` with an error object.
propose error object:
```text
{"error": "invalid input"}
```
Let me know if the message should be re-worded.
=> rna-transcription: remove bad input tests

README.md
In #996 it was decided that the canonical data should have an explicit input key whose value is an object containing the input(s) to the code under test.
closes #1007
=> readme.md: Update example to reflect "input key as an object" policy

exercises/allergies/canonical-data.json
#996 Updated the schema for canonical data. So I am updating the allergies exercise's json to reflect the change.
=> allergies: Update json for new "input" policy

exercises/acronym/canonical-data.json
#996 Updated the schema for canonical data. So I am updating the acronym exercise's json to reflect the change.
=> acronym: Update json for new "input" policy

exercises/binary/canonical-data.json
#996 Updated the schema for canonical data. So I am updating the exercise's json to reflect the change as well as fixed one small typo.
=> binary: Update json for new input policy and fix typo

exercises/alphametics/canonical-data.json
A test case update suggested to complement this PR:
https://github.com/exercism/python/pull/1119
=> alphametics: Update canonical data. Add a test case with many addends

exercises/two-fer/metadata.yml
I implemented this exercise for Clojure and noticed the case was inconsistent. I hope this fix is ok, and the odd case was not intentional - let me know :slightly_smiling_face:
=> two-fer: fix case inconsistency

exercises/book-store/canonical-data.json
#996 Updated the schema for canonical data. So I am updating the book-store exercise's json to reflect the change.
=> book-store: Update json for new "input" policy

exercises/binary-search/canonical-data.json
#996 Updated the schema for canonical data. So I am updating the exercise's json to reflect the change.
=> binary-search: Update json for new input policy

exercises/luhn/canonical-data.json
Tiny nitpick - case wasn't entirely consistent in `luhn` tests 🙂
=> luhn: apply consistent case to tests

exercises/isbn-verifier/canonical-data.json
Implemented input objects per #996
=> isbn-verifier: add input objects

exercises/luhn/canonical-data.json
=> luhn: Apply new "input" policy

exercises/bob/canonical-data.json
=> bob: apply "input" policy

exercises/isbn-verifier/canonical-data.json
I have inserted the new test case at the end of  the test data.  I am not sure where it might fit better.
[description](https://github.com/exercism/problem-specifications/blob/master/exercises/isbn-verifier/description.md)
closes #1052
=> isbn-verifier: add empty isbn case

exercises/dominoes/canonical-data.json
=> dominoes: Apply new "input" policy

exercises/bracket-push/canonical-data.json
See #996.
I've considered various names for the input property (e.g. "expression"), but in the end I simply used "value".
=> bracket-push: Apply new "input" policy

exercises/atbash-cipher/canonical-data.json
=> atbash-cipher: Apply new "input" policy

exercises/meetup/canonical-data.json
It also adds an "expected" property, that was previously missing but now makes even more sense as the input properties are contained in a separate property.
=> meetup: Update json for new input policy

exercises/alphametics/canonical-data.json
The test contains 199 addends, not 41. Sorry
=> alphametics: Update test description

exercises/binary-search-tree/canonical-data.json
Closes #555 
Edit to add: [Description](https://github.com/exercism/problem-specifications/blob/master/exercises/binary-search-tree/description.md)
=> binary-search-tree: implement canonical-data.json

package.json, yarn.lock
As I have been updating the canonical-data.json for a few exercises, I realized the only dependency in package.json was outdated. So this PR bumps the version for ajv-cli to 2.1.0.
I had both scripts within package.json and I have not seen any issues since the upgrade.
=> problem-specifications: Update ajv-cli dependency to latest

exercises/gigasecond/canonical-data.json
=> gigasecond: Apply new "input" policy

exercises/two-fer/canonical-data.json
I've renamed the property from `name` to `twoFer`, as `name` is actually the input and what is returned is not a name, but the two-fer.
See #996
=> two-fer: Apply new "input" policy

exercises/two-bucket/canonical-data.json
=> two-bucket: Apply new "input" policy

exercises/bowling/canonical-data.json
Updates canonical data to be in compliance with #996 and #987.
=> bowling: update test data for recent policy changes

exercises/book-store/canonical-data.json
Convert "expected" output to fixed point (cents) to remove floating point values.
closes #964
=> book-store: convert to fixed point output

exercises/phone-number/canonical-data.json
The existing descriptions for invalid area codes and exchange codes both cite a range, but only test a single value. This PR tests for all values outside the valid range.
=> phone-number: add missing edge cases

exercises/list-ops/canonical-data.json
There were two formats being used to define a function:
1. A unary function where the parameter is not defined by assumed to be named `value`. Example: `value + 1`
2. A binary function where the parameters are defined by `(x, y)`. Example: `(x, y) -> x + y`
=> list-ops: Normalize format of functions

exercises/saddle-points/canonical-data.json
=> saddle-points: Apply new "input" policy

exercises/largest-series-product/canonical-data.json
=> largest-series-product: Apply new "input" policy

exercises/react/canonical-data.json
react 1.1.0
As proposed and accepted in #996
```ruby
indent = false
operations = false
ARGF.each_line { |l|
if l.include?('version')
ver = l.split(?")[3]
ver_components = ver.split(?.).map(&:to_i)
ver_components[1] += 1
ver_components[2] = 0
l[ver] = ver_components.join(?.)
end
first_non_space = l.index(/\S/)
if l.include?('"cells"')
puts ' ' * first_non_space + '"input": {'
indent = true
end
operations ||= l.include?('"operations"')
l.delete!(?,) if operations && l.strip == '],'
puts "#{'  ' if indent}#{l}"
if operations && l.strip == ?]
puts ' ' * first_non_space + '},'
operations = false
indent = false
end
}
```
---
also note the additional commit that adds `"expected": {}`, since it's required but we expect nothing other than what was already expected in `operations`.
=>  react: Move inputs (cells, operations) to input object

exercises/hamming/canonical-data.json
hamming 2.1.0
As proposed and accepted in #996
```ruby
indent = false
ARGF.each_line { |l|
if l.include?('version')
ver = l.split(?")[3]
ver_components = ver.split(?.).map(&:to_i)
ver_components[1] += 1
ver_components[2] = 0
l[ver] = ver_components.join(?.)
end
first_non_space = l.index(?")
if l.include?('strand1')
puts ' ' * first_non_space + '"input": {'
indent = true
end
l.delete!(?,) if l.include?('strand2')
puts "#{'  ' if indent}#{l}"
if l.include?('strand2')
puts ' ' * first_non_space + '},'
indent = false
end
}
```
=>  hamming: move inputs (strand1, strand2) to input object

exercises/clock/canonical-data.json
I have read through and attempted to follow all your test modification, contribution, and PR guidelines. Please accept my apology if I booted it somehow.
When working on this exercise in Ruby, I found that there was no need to write subtraction operation _per se_, because the test suite was adding negative numbers instead of subtracting positive ones.
I updated the JSON data to force the exercise to require subtraction, as stated in the [README](https://github.com/exercism/problem-specifications/blob/master/exercises/clock/description.md). 
Per [Test Data Versioning](https://github.com/exercism/problem-specifications#test-data-versioning), because I renamed a property, this qualifies as a MAJOR version change, so I updated the version to 2.0.0. Honestly, though, this feels like a MINOR …
=> clock: change "add" of negative minutes to "subtract" of positive minutes

exercises/clock/canonical-data.json
It was discussed and generally liked in #1131, to rename occurances of `"add":` and `"subtract":` with a common value name since `"property":` is already indicating the action to be taken.  `"value":` was the last suggested name given to replace `"add":` and `"subtract":`  Others were: `amount` and `quantity`.
=> clock: rename "add": and "subtract": to "value":
